### ISSUE TITLE
Metabase starts super slow if entropy is exhausted (10+min)

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#10175]
As discussed in #9698 

> Let me add my two cents for somebody who is still facing slow startup(10-60 minutes). Unfortunately, the startup is still slow after upgrading to 0.32.8 for me and shows very strange behaviour. The good news is after battling for 2 days, I have finally found the problem and the workaround.
>
> Environments tested: GCE(Ubuntu 18.04)/GCE(docker)/GKE/Windows 10/Windows 10(Docker)
> Problematic Environments: GCE(Ubuntu 18.04)/GCE(docker)/GKE
> System/VM Resources: 4 CPU,15GB RAM / 2CPU,8GB RAM
> Affected Versions: v0.32.x
>
> Strange Startup Behaviour: On a new vm, the first time i run metabase(v0.32.x) using jar or docker the startup is very quick(~1-2 mins). Every subsequent fresh run(running a second docker container on different port/stop existing metabase instance, delete db and plugin folder and run metabase again) takes almost 10-60 minutes to startup. On my local windows machine, this behaviour is not reproduced and everything works perfectly. On metabase(v0.31.2), this behaviour is not reproduced and everything works perfectly.
>
> Root Cause: There is this dependency buddy.core.codecs referenced in https://github.com/metabase/metabase/blob/master/src/metabase/util/embed.clj which is gnerating random numbers and is using java.security.SecureRandom which relies on /dev/random and /dev/urandom on linux distros which was resulting in entropy exhaustion(cat /proc/sys/kernel/random/entropy_avail was less than 100) and was blocking the metabase application until the entropy is refilled to a certain level. Normally entropy is based on keyboard strokes, mouse movement etc. but those peripherals not being available on server can result in less entropy generation, quick depletion and slow refill.
>
> Workaround: The workaround I have used for now is to install haveged as suggested by digitalocean https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged. Since then metabase is working perfectly.
> 
> Frankly speaking, I don't consider this workaround a bad one but if there is any better solution, I'd love to help in any way possible :)(Emojis aren't turned off :p).

**Comment by camsaul** [comment]
Things I'd like to address:

*  Why does Metabase need so much entropy to launch? I would assume it has to do with generating cryptographically secure random numbers. What numbers are we (or a dependency) generating? One thing I can think of off the top of my head is there are a few places where we use `java.util.UUID` (which generates cryptographically secure random numbers) to do stuff like create setup tokens and the like. 
*  Can we reduce that need for entropy? We should see if all the places we're using it need to be secure and use a different UUID impl if not -- for things like generating IDs for QueryExecutions in the application DB we don't really need the random UUIDs to be cryptographically secure. 
*  Can we detect entropy exhaustion and log a warning?

**Comment by tlrobinson** [comment]
@camsaul It sounds like it's specifically `buddy.core.codecs` (according to that comment), which I think we use for JWT. But maybe that's just where the problem manifested.

**Comment by exabrial** [comment]
Consider installing the `haveged` package

**Comment by exabrial** [comment]
This is likely due to poor design of Linux random generators. See similar stories here:
https://daniel-lange.com/archives/152-hello-buster.html The short answer... have users install haveged debian package.

The long and complicated answer: https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom

**Comment by salsakran** [comment]
@camsaul  @tlrobinson can we change our docker image to do the equivalent of `have users install haveged`?

**Comment by salsakran** [comment]
bumping this in priority because if someone tries to spin up Metabase and it isn't up in 60 minutes, that's as good as a dead instance.

**Comment by andreychirikba** [comment]
My current workaround for starting new Metabase Docker containers is: `ln -sf /dev/urandom /dev/random`

**Comment by exabrial** [comment]
https://ruleoftech.com/2016/avoiding-jvm-delays-caused-by-random-number-generation If you can simply add a JVM argument you can fix this.

**Comment by adamreis** [comment]
FYI I've not yet had success using @andreychirikba's workaround. My last Metabase startup took 7 minutes. Seems like I could fix by building my own image with `haveged` installed, but that'd be a bit tough given our current CI setup.

Relevant bit of k8s config:

```yaml
    spec:
      containers:
        - name: metabase
          image: metabase/metabase-enterprise:v1.37.0.2
          command: ["/bin/bash", "-c"]
          args:
            - ln -sf /dev/urandom /dev/random &&
              /app/run_metabase.sh
```

**Comment by adamreis** [comment]
Tried the same approach, installing `haveged` instead. No luck. Sleeping for 10s as the container doesn't immediately have internet connectivity when it's spun up.

```yaml
        - name: metabase
          image: metabase/metabase-enterprise:v1.37.0.2
          command: ["/bin/bash", "-c"]
          args:
            - sleep 10 &&
              apk add --no-cache haveged &&
              /app/run_metabase.sh
```

**Comment by adamreis** [comment]
Oof. I've fixed my issue - was due to my own bad config. I'm a k8s noob and naively copied [this default value](https://github.com/helm/charts/blob/master/stable/metabase/values.yaml#L121-L123) for the CPU resource limit from the metabase helm chart config, giving the metabase container only 0.1 CPU cores. With this removed, Metabase starts in ~25 seconds. Shoutout to @flamber for noticing suspiciously slow portions of Metabase's initialization in my log files, leading me to investigate this.

I'm still doing `ln -sf /dev/urandom /dev/random` in my entrypoint, although no longer sure whether it's necessary. I intend to leave for now, but can also test with it removed if that'd help someone else's debugging.

**Comment by robdaemon** [comment]
Okay so having been through this many times... oy.

In container installations, there is *one* `/dev/random` instance that is shared by all containers running on that host. It can easily run out of entropy. That's when the blocking starts.

Java's default PRNG provider in Linux is `NativePRNG` - if there is no settings entry for a entropy provider, it defaults to `/dev/random` and uses `/dev/urandom` as a secondary file. Problem: if you try and use `/dev/random` first, you're gonna block. 

It gets better -

If you look at the default `security.properties` file for Java 11 (see `/etc/java-11-openjdk/security/java.security`) - you'll see this:

```
securerandom.source=file:/dev/random                                                                                                              securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN
```

So, this is where you get to people doing the `ln -sf /dev/urandom /dev/random` - because, out of the box, Java is going to use `/dev/random`. And very few people mess with the default Java security properties (for good reasons.)

**Comment by zacheryph** [comment]
It's kind of frightening that this is still an issue? Exactly how much entropy does an application need that hasn't even been touched yet? Is there anyway to put a fix into the docker image or ... at a very bare minimum mention / link this issue from the `Running Metabase on Docker` page in the documentation and... how to manually work around it?

I cannot be the only one who's attempted to run the docker image to then have to search for this issue? I cannot imagine how much of a turn off this is to anyone remotely looking at Metabase (and possibly Metabase Cloud) as a solution. How many people simply give up after 15...10...5 minutes without searching for this issue and drop Metabase as a possible solution?

I imagine labelling this as a P1 bug and still being open after 3 years would also raise concern to anyone in larger organizations.

**Comment by paoliniluis** [comment]
Hi @zacheryph, Metabase is running in ~40K-50K instances around the world and only a few of them showed this behaviour on startup. In fact, this doesn't happen at all in our cloud where we run thousands of instances. If you hit this issue for some reason, it's just about adding a volume to your container:

volumes: 
    - /dev/urandom:/dev/random:ro

let us know which version are you hitting this issue and how's Metabase running (plain docker? jar? k8s? ecs? swarm? other?) so we can try to reproduce and fix. Thanks a lot in advance

**Comment by zacheryph** [comment]
THank you. Running under Docker (via Compose) for Mac on M1.

**Comment by paoliniluis** [comment]
> THank you. Running under Docker (via Compose) for Mac on M1. I wonder if this is related to there being no arm64 image :(

We have encountered a few issues while using Docker via Rosetta2, so I suggest that in the meantime you build your own arm-compatible image with my gist from here: https://gist.github.com/paoliniluis/78fe800f06fc7027a20665a429239c1e?permalink_comment_id=3951039#gistcomment-3951039

add the volume that I mentioned before to the compose file just in case, but I truly don't think that's the issue here (watch out with the RAM that you give to the container, at least 512MB should be assigned)

**Comment by dpsutton** [comment]
Seems to be no activity and not clear this is a general jvm issue or the application specifically. If we have more reports or a tenable theory we can reopen.
