### ISSUE TITLE
0.33 - Date formats are no longer applied to exports, possible regression

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#10689]
**Describe the bug**
This was previously working in older versions, and I suspect may be a regression of https://github.com/metabase/metabase/issues/5828. When I apply a format to a date field, for examples, to remove the time component, it renders correctly in Metabase itself. However, when I export the result to CSV/XLS, my chosen format is no longer applied and instead I get a full date/time string with timezone.

**To Reproduce**
1. Browse the raw data for "orders in the sample dataset"
2. Click the heading of the "created at" field and choose "formatting"
3. Click the "off" button under "show the time". The time will disappear from the created at column. Then click "done".
4. Download the full results to CSV.
5. Open the CSV in some other program (Excel, text editor, doesn't matter). The "created at" column will now contain full datetime strings, like "2019-02-11T21:40:27.892Z", even though we removed them from the column already.

**Expected behavior**
I'd expect that whatever formats I choose for the columns in the table would also apply to exported versions of that table.

**Information about your Metabase Installation:**
- Your browser and the version: Version 75.0.3770.142 (Official Build) (64-bit)

- Your operating system: OS X 10.14.1

- Your databases: MySQL

- Metabase version: 0.33.0

- Metabase hosting environment: Docker

- Metabase internal database: MySQL

**Severity**
We use Metabase to send reports directly to partners automatically via pulses. This issue  causes the formatting on those reports to break, which means that our internal staff has to format them manually before sending them out to ensure they follow the agreed upon structure. This consumes partnership management time on low-level excel tasks and creates a confusing UX for our partners.

**Comment by nickhamlin** [comment]
Ah, thanks for clarifying @camsaul! No, I wasn't aggregating by year. Just using the raw unaggregated orders data in the steps above was enough to cause the issue. That said, I did also run into a situation today where the trend visualization wouldn't recognize a query grouped by year as a valid time series input for the purposes of calculating a growth rate. Here's how to reproduce:

1.) Browse data -> Sample Data -> Orders
2.) Summarize by Created At, Grouped by Year
3.) Try to change the visualization type to "Trend". Instead of the usual number+growth rate, you'll get a "Group by a time field to see how this has changed over time" message

Not sure if this is related or should be separated out to it's own issue. If so, please let me know and I'll be glad to put it in.

**Comment by nickhamlin** [comment]
aaaand I just realized the issue I just described is already linked above and on its way to being resolved - my apologies!

**Comment by camsaul** [comment]
Fixed by #10722

**Comment by nickhamlin** [comment]
@camsaul, I just tested this in 0.36.3 as we're preparing to upgrade (from 0.33.3, it's been a while) and can confirm that the original issue described is still happening (formatting changes to date fields made in the UI are not upheld when exporting those same results to CSV/XLSX) and can still be reproduced via the steps listed above. This means that we have to manually fix the formatting (in Excel) for any datasets that contain any date/time/datetime fields. Any advice?

**Comment by flamber** [comment]
@nickhamlin It's a regression in 0.35.0 - #12964

**Comment by nickhamlin** [comment]
Much appreciated @flamber! I'll start tracking that issue instead, thanks!
