### ISSUE TITLE
Human-readable numbering doesn't work on Mobile version

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#10716]
**Desktop**
![desk](https://user-images.githubusercontent.com/15974735/63714448-aa075400-c7f6-11e9-869b-3c8c1dd1cc91.png)
**Mobile**
![mobile](https://user-images.githubusercontent.com/15974735/63714458-ad024480-c7f6-11e9-8f68-47cc223d9c09.png)

Metabase Version: 0.33
Browser: Checked with Firefox and Chrome

**Comment by paulrosenzweig** [comment]
Fixed in #10932

**Comment by vvaezian** [comment]
This is still not working in 0.33.5.1. (tested on Firefox Mobile and Chrome Mobile, latest versions).

Also in the desktop version if the screen width passes a threshold, the data is not shown in human-readable anymore (this is not specific to 0.33.5.1):

<img src="https://user-images.githubusercontent.com/15974735/69091836-fe8a2c00-09ff-11ea-81a4-add1748f2502.png" width=600>

It would be nice to have the option to enforce human-readability independent of the screen size.
