### ISSUE TITLE
Deleting a dashboard parameter's name causes the parameter to disappear but still be set via URL

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#10829]
If you edit a parameter and remove the name it will suddenly disappear from the UI. However, the parameter is still present and can be set via the URL.

I think there are two parts to fixing this:

1. Avoid letting you remove the name completely. We probably shouldn't update the name until you blur the text field, and if it's invalid (empty string or a duplicate) then revert to the previous name?
2. For fix existing dashboards where this has occurred, and as a defensive measure, we should probably ignore parameters that have an empty string as the name/slug.

**Comment by paulrosenzweig** [comment]
Fixed a while back in #10323

**Comment by nemanjaglumac** [comment]
@paulrosenzweig I noticed this just now. There is a repro test in `parameters.cy.spec.js` (issue labeled as `.Reproduced` on Oct, 12) which is still skipped. When I unskip it locally, it's still failing.

The issue doesn't seem to be fixed.

**Comment by nemanjaglumac** [comment]
Either this issue regressed or it was never fixed. Please, see https://github.com/metabase/metabase/pull/13971 for more details.

**Comment by nemanjaglumac** [comment]
After some clarification and useful feedback from Paul, test is now updated. It reflects this issue even though UI changed since it was originally opened.
Closing it again.
