### ISSUE TITLE
When report-timezone is set, Snowflake dates are returned from the day prior

### ISSUE THREAD

**Issue by yoccodog** [metabase/metabase#11036]
I know there is a lot of documentation around troubleshooting timezones and I've tried to go through that to make sure I wasn't unnecessarily posting here. I'm still running into problems, though. 

Metabase is connected to two databases, PostgreSQL and Snowflake. These databases have the same data in them. When I run a basic query with a date filter against Postgres, the output is as I would expect. This is not the case with Snowflake. With Snowflake, the data returned is from the day prior. 

For example, when I run the following query on Postgres (using native SQL to aid in debugging) with the date August 26, 2019 selected:
```
SELECT {{filter_date}}, timestamp
FROM table1
WHERE CAST(table1."timestamp" AS date) = CAST({{filter_date}} AS date)
LIMIT 1048576
```
I get:
```
2019-08-26 00:00:00-04  August 26, 2019, 12:50 PM
...
```

Running a similar query on Snowflake:
```
SELECT to_varchar({{filter_date}}), timestamp
FROM table1
WHERE date_trunc('day', CAST(table1."timestamp" AS timestamp)) = date_trunc('day', CAST({{filter_date}} AS timestamp))
LIMIT 1048576
```
 returns:
```
2019-08-25 20:00:00.000 -0400 August 25, 2019, 11:09 PM
...
```

What it looks like like is happening is that `filter_date` is somewhere converted to the day prior but only for Snowflake. 

I'm struggling to debug this further and would greatly appreciate any help. 

Browser timezone: EDT
Metabase reporting timezone: US/Eastern
Metabase timezone (via JAVA_TIMEZONE): US/Eastern
Postgres timezone: UTC
Snowflake timezone: UTC

Update:
I just realized that if I convert `filter_date` to UTC, I get the desired results:
```
SELECT to_varchar({{filter_date}}), timestamp
FROM table1
WHERE date_trunc('day', CAST(table1."timestamp" AS timestamp)) = date_trunc('day', CAST(CONVERT_TIMEZONE('UTC', {{filter_date}}) AS timestamp))
LIMIT 1048576
```
I would not expect to have to do this.

**Comment by flamber** [comment]
Hi @yoccodog 
Which version of Metabase?
It looks like there's an issue with Snowflake timezones - #8804 - does it match your problem?

**Comment by yoccodog** [comment]
Hi @flamber !

Metabase version 0.33.3. 

It almost looks like there is some kind of double-conversion going on so it might match. To be completely honest, I'm struggling to pin-point what's going on!

**Comment by salsakran** [comment]
P1 since this is a basic correctness issue and matches the other P1 timezone bugs we have. Suspect it might have a similar root cause.

@yoccodog which of the two (Postgres or Snowflake) is returning correct results?

**Comment by yoccodog** [comment]
Hi @salsakran . Postgres is returning the correct results.

**Comment by camsaul** [comment]
Note to self: code for debugging this

```clj
(defn- x []
  (driver/with-driver :postgres
    (qp.test/rows
      (qp/process-query
        (merge
         {:database   (data/id)
          :type       :native
          :native     {:query         "SELECT {{filter_date}}, last_login FROM users WHERE CAST(last_login AS date) = CAST({{filter_date}} AS date)"
                       :template-tags {:filter_date {:name         "filter_date"
                                                     :display_name "Just A Date"
                                                     :type         "date"}}}
          :parameters [{:type   "date/single"
                        :target ["variable" ["template-tag" "filter_date"]]
                        :value  "2014-08-02"}]})))))

(defn- x2 []
  (tu/with-temporary-setting-values [report-timezone "US/Pacific"]
    (x)))

(defn- y []
  (driver/with-driver :snowflake
    (qp.test/rows
      (qp/process-query
        (merge
         {:database   (data/id)
          :type       :native
          :native     {:query         (str "SELECT {{filter_date}}, \"last_login\" "
                                           "FROM \"test-data\".\"PUBLIC\".\"users\" "
                                           "WHERE date_trunc('day', CAST(\"last_login\" AS timestamp))"
                                           "    = date_trunc('day', CAST({{filter_date}} AS timestamp))")
                       :template-tags {:filter_date {:name         "filter_date"
                                                     :display_name "Just A Date"
                                                     :type         "date"}}}
          :parameters [{:type   "date/single"
                        :target ["variable" ["template-tag" "filter_date"]]
                        :value  "2014-08-02"}]})))))

(defn- y2 []
  (tu/with-temporary-setting-values [report-timezone "US/Pacific"]
    (y)))
```

**Comment by camsaul** [comment]
Fixed by #11718

**Comment by mnahta** [comment]
@camsaul i am using metabase on your cloud but this isn't fixed. It's always using week start = 7 (Sunday) instead of 1. Can you please look?
