### ISSUE TITLE
Field filters mismatch Datetimes and Timestamps

### ISSUE THREAD

**Issue by tomoschuk** [metabase/metabase#11578]
**Describe the bug**
Field filter no longer work for datetimes in natlve SQL queries in BigQuery

**Logs**
Not sure if related but:
`Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://metrics.cambly.com/app/dist/vendor.bundle.js?f4999ff7ddee79f5a90a:1:285932)
    at Object.e.exports [as findDOMNode] (https://metrics.cambly.com/app/dist/vendor.bundle.js?f4999ff7ddee79f5a90a:1:2248148)
    at d.value (https://metrics.cambly.com/app/dist/app-main.bundle.js?f4999ff7ddee79f5a90a:5:233247)
    at n._updateSize (https://metrics.cambly.com/app/dist/app-main.bundle.js?f4999ff7ddee79f5a90a:5:232674)`

**To Reproduce**
Use any field filter on datetime field in native SQL query
![Screen Shot 2019-12-20 at 10 27 34 AM](https://user-images.githubusercontent.com/27005443/71281723-786d4800-2313-11ea-81ab-eb6e3b699738.png)

**Information about your Metabase Installation:**

Chrome Version 79.0.3945.88
MacOS 10.15.1
BigQuery
Metabase 0.34, hosted on Heroku
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
Breaks nearly all natve SQL dashboards and tools

**Comment by flamber** [comment]
I don't think the javascript errors are related, I see them too. Adding error, images cannot be searched:
`No matching signature for operator BETWEEN for argument types: DATETIME, TIMESTAMP, TIMESTAMP. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [4:59]`

**Comment by kdhfred** [comment]
I got a same error log. This issue just happened after update 0.33.2 to 0.34
But when I run same query on 0.33.2, I got `No method in multimethod 'date' for dispatch value: [:bigquery :day]`
![image](https://user-images.githubusercontent.com/7248836/71562857-cdeee500-2ac9-11ea-9b16-f138490eccb4.png)

**Comment by masolin** [comment]
I got a similar error, too.

```
No matching signature for operator BETWEEN for argument types: DATE, TIMESTAMP, TIMESTAMP. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [4:68]
```

**Comment by flyingmachine** [comment]
I'm still looking this but found this [Stack Overflow helpful](https://stackoverflow.com/questions/51214576/bigquery-error-400-no-matching-signature-for-operator-between-for-argument-type).

I'm not familiar with the query editor but my guess at this point is that Big Query implementation is always producing `TIMESTAMP` values for the "begin" and "end" arguments to `BETWEEN` when filtering on the different varieties of date and times. Instead, the "begin" and "end" arguments should probably have the type that matches the field being filtered.

**Comment by camsaul** [comment]
@flyingmachine that's right, BigQuery is incredibly fussy about comparing various temporal types against one another. E.g. something like 

```sql
WHERE datetime '2020-01-06T13:14:00.000-08:00' > timestamp '2020-01-06T13:14:00.000-08:00'
```

is totally invalid in BigQuery land because a `datetime` is not comparable to a `timestamp`. We have had a few bugs related to this in the past, which in the past I fixed by wrapping everything in a `CAST(... AS timestamp)` call which wasn't the best solution, especially from a perf standpoint (indexes couldn't be used properly).

In 0.34.0 I switched to adding logic to reconcile the arg types of filter clauses – code is [here](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery/src/metabase/driver/bigquery/query_processor.clj#L432) – so the problem is the logic is not working correctly in this case, or not being applied, for one reason or another. It might be possible that the column metadata is incorrect, e.g. the synced column metadata says the column is a `TIMESTAMP` when it's actually a `DATE`.

**Comment by camsaul** [comment]
I think maybe the issue is the `reconcile-temporal-types` logic isn't being ran for the filter clauses created for parameters in SQL queries, since AFAIK it's working correctly for queries MBQL

**Comment by flyingmachine** [comment]
thanks @camsaul! this all makes sense. I think I'm close to being able to write the fix.

gonna mention #11222 for GH cross-linking

**Comment by flyingmachine** [comment]
@camsaul I think I've been able to confirm that the `reconcile-temporal-types` multimethod isn't being called for the test query that I'm using.

I can't tell when the [`sql.qp/->honeysql`](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery/src/metabase/driver/bigquery/query_processor.clj#L444) method is getting called, but it looks like for it to apply it would need to dispatch on `[:bigquery :between]`. However, I noticed that in [parameter substitution](https://github.com/metabase/metabase/blob/master/src/metabase/driver/sql/parameters/substitution.clj#L216) there aren't any data structures returned that include a `:between` keyword. The following query and params are returned for my test example:

```
"SELECT *\nFROM `debug_11578.table_with_datetimes`\nWHERE date_trunc(`debug_11578.table_with_datetimes`.`created_at`, day) BETWEEN ? AND ?"

((t/offset-date-time "2020-01-01T00:00Z") (t/offset-date-time "2020-01-31T00:00Z"))
```

At this point I'm not sure what to do, in part because I don't know where `sql.qp/->honeysql` is getting called.

**Comment by camsaul** [comment]
`sql.qp/->honeysql` is called when building an MBQL query, but not for parameter substitution, which is why thinks aren't working

**Comment by camsaul** [comment]
Fixed by #11678

**Comment by kdhfred** [comment]
@camsaul Thank you for your efforts!

**Comment by shafy** [comment]
@camsaul I've updated to 0.34.1 but unfortunatly the issue still persists. I have a simple BigQuery table and it still tries to add Months or Years or whatver with the `TIMESTAMP_ADD()` method.

Here's the query it generates:
```
SELECT `simplified_prod.rental_errors`.`created_at` AS `created_at`, `simplified_prod.rental_errors`.`error_code` AS `error_code`, `simplified_prod.rental_errors`.`error_message` AS `error_message`, `simplified_prod.rental_errors`.`error_type` AS `error_type`, `simplified_prod.rental_errors`.`external_identifier` AS `external_identifier`, `simplified_prod.rental_errors`.`pickup_location_id` AS `pickup_location_id`, `simplified_prod.rental_errors`.`pickup_location_name` AS `pickup_location_name`, `simplified_prod.rental_errors`.`pickup_location_pos_number` AS `pickup_location_pos_number`, `simplified_prod.rental_errors`.`user_email` AS `user_email`, `simplified_prod.rental_errors`.`user_id` AS `user_id`
FROM `simplified_prod.rental_errors`
WHERE datetime_trunc(`simplified_prod.rental_errors`.`created_at`, month) BETWEEN CAST(timestamp_trunc(timestamp_add(current_timestamp(), INTERVAL -30 month), month) AS datetime)
   AND CAST(timestamp_trunc(timestamp_add(current_timestamp(), INTERVAL -1 month), month) AS datetime)
LIMIT 1048576
```
