### ISSUE TITLE
Pulse charts don't honour custom column names

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#11655]
**Describe the bug**
For  table visualisation of questions with joined tables, I specify custom column names (instead of the autogenerated "Table -> Column" as column name). When creating a Pulse, I want the custom names to appear in the Pulse mail as specified. However, the Pulse mail still lists the autogenerated column names instead.

**To Reproduce**
1. Create a question from two joined tables.
2. Select table visualisation.
3. Give columns custom names.
4. Create a pulse from this question.
5. Observe the Pulse preview (and the received mail) list autogenerated column names instead of custom ones.

**Expected behavior**
I expect the Pulse to list custom column names as set by me.

**Screenshots**
Custom column names set in table visualisation (first column contains usernames and has been edited out):
![image](https://user-images.githubusercontent.com/30152071/72009256-d11a6b80-3255-11ea-959c-8f8b1bae01cb.png)

Actual Pulse mail (first column edited out):
![image](https://user-images.githubusercontent.com/30152071/72009208-bb0cab00-3255-11ea-89ab-d8b58da4f8fd.png)

**Information about your Metabase Installation:**
`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1; Windows for Workgroups 3.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.3+7",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.3",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.3+7",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-19",
      "tag": "v0.34.0",
      "branch": "release-0.34.x",
      "hash": "1335215"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}`

**Severity**
We are just rolling out the Pulses to our customers now, so have to give extra explanation about each chart -> not severe, but unpleasant.

**Comment by flyingmachine** [comment]
I was able to reproduce this locally

**Comment by camsaul** [comment]
Fixed by #11685

**Comment by andreychirikba** [comment]
In Excel attachments, custom column names are still not honoured. This is the Excel table header I get as a Pulse attachment:

`Name	Question 7 → count	Question 1 → sum	Question 8 → count	Question 10 → count	Question 11 → count	Question 12 → count	Question 13 → count	Question 14 → count`

while in the actual Pulse mail the column names are as set.

**Comment by flamber** [comment]
@andreychirikba 
Almost no formatting (including column titles) are applied to the exports/attachments.
There's an issue open about that: #10879 - upvote by clicking :+1: on the first post
