### ISSUE TITLE
DB explorer crash while viewing a single result

### ISSUE THREAD

**Issue by AlmogCohen** [metabase/metabase#11865]
**Describe the bug**
The metabase DB explorer crash when loading a single result from one of my DB tables. Due to the crash, most of the fields remain empty and the object relations are not loading. Non of the single-result info is shown for this table. All other pages in the app are working correctly. 

**Logs**
Console logs: [metabase-1581001608058.log](https://github.com/metabase/metabase/files/4165742/metabase-1581001608058.log)

All requests to the server including the XHR ones return 200 with no problem. I cannot provide a peek into the actual data as the data is confidential obviously...

**To Reproduce**
1. Click on any db under the 'OUR DATA'
2. Click one of the collections.
3. For any object that is loaded, click any of the "Ids" blue button to load the full row details
4. In my case, with my data for a specific table, the frontend crashes here...

**Expected behavior**
The page should finish loading the row information

**Screenshots**
<img width="1438" alt="Metabase error" src="https://user-images.githubusercontent.com/3888998/73950002-dd9ced00-4903-11ea-96f9-e951cc61b2c2.png">
<img width="649" alt="Console Error" src="https://user-images.githubusercontent.com/3888998/73950196-2d7bb400-4904-11ea-8858-ea4b2a53d679.png">

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
**How can provide these logs without providing confidential information? 
- Your browser and the version: Chrome 79
- Your operating system: OSX 10.15
- Your databases: Postgres
- Metabase version: v0.32.10
- Metabase hosting environment: AWS Elastic Beanstalk
- Metabase internal database: I'm not sure...postgres?

**Severity**
Blocking management work and analytics for internal users. The model that is crashing is one of the central pieces in our company and therefore it is crucial to have it visible for us.

**Additional context**
This model that is crashing, is very central in the company, and therefore has many relations to other objects that are all loaded by metabase when showing these rows

**Comment by flamber** [comment]
Hi @AlmogCohen 
There has been a lot of changes since 0.32.10. I cannot reproduce your issue on latest 0.34.2
But I have a feeling that it's probably related to #6830, which was fixed in 0.33.1
Is the `TypeError: Cannot read property 'length' of null` the only error in the console?

**Comment by AlmogCohen** [comment]
Awesome work, thanks for the quick response! I've just upgraded to metabase 0.34.2 to make the debug work easier. The issue still persists.

Now there are no console errors at all, but the same client crash is visible. For some of the table results, the API respond with the relevant data, but the client show nothing as you can see in the provided screenshot. I guess the crash has to do somehow with the specific information metabase is trying show in my installation and therefore you have issues reproducing it.

Broken: <img width="1440" alt="0 34 errors" src="https://user-images.githubusercontent.com/3888998/73956651-ebf00680-490d-11ea-99d0-f12bc100fc00.png">
And another row on the same table just works: 
<img width="1438" alt="0 34 no errors" src="https://user-images.githubusercontent.com/3888998/73956930-4e490700-490e-11ea-93a5-e7aef43330de.png">

Many rows are working well, many seems to be broken.

**Comment by flamber** [comment]
@AlmogCohen Nice with the extra info, but since you cannot provide any data, can you see any differences in between the working vs broken responses, which might be causing the javascript that visualizes the information to break? You might have to look at few working/broken responses.
Maybe easier to use something like https://jsonformatter.org/json-pretty-print to spot the differences.

**Comment by AlmogCohen** [comment]
I can try and provide **some** data (censored I guess) if somebody might have an idea why the client is breaking. It is the way with all bugs, but I'm surprised that the content of the data is breaking the view.

Any suggestions to what data should be interesting here? I cannot just put everything...are there any specific requests that might be of interest? is there any guidance available to what can actually break the views? I'm not a Metabase expert by any means...

Thanks!

**Comment by AlmogCohen** [comment]
Needless to say, it wasn't always like that, but I cannot recall on what Metabase version it worked perfectly...Our data did not change for this table for quite a few years...

**Comment by flamber** [comment]
@AlmogCohen 
It's the first time I've seen something like this, so I'm not sure what is breaking the view.
When there's no warnings/errors, then the only way to find it would be to reproduce with similar data.

Given that you had same behavior in 0.32.10, then I guess this issue has existed for a long time?

Can you show the field/column information from Browse Data > Learn about our data > (your db) > Worksheets table > Fields in this table? Like this:
![image](https://user-images.githubusercontent.com/1447303/74248377-c9803380-4ce7-11ea-88de-4a3899d432e6.png)

**Comment by AlmogCohen** [comment]
<img width="1096" alt="Screen Shot 2020-02-11 at 7 24 54 PM" src="https://user-images.githubusercontent.com/3888998/74261651-31447780-4d04-11ea-9d79-4209dd1ce8d6.png">

I'd be very happy to try and provide censored data the might help solving this issue. Metabase is generally pretty awesome so I'd be happy to help nail this bug down. 

(P.S. Not sure if this is related at all, but since upgrading to 0.34 the "is connected to" section stopped working altogether for all objects in all Metabase tables... https://share.getcloudapp.com/2NuBYjXe it is not the first time we upgrade the Metabase version on AWS...)

**Comment by AlmogCohen** [comment]
OK, we've got some progress. I've just suddenly realized that it might just be a CSS issue.

The `Widgets` field which contains a `json` (according to the image above) seems to contain extremely long lines in some of the cases. What happens is that the view somehow pushes all the data, of all fields reallyyyyyy far to the right part of the screen. wayyyy out of the screen frame :)

I think I would expect the scrolling to be within the json field, and not across the whole page.

See the video below: https://share.getcloudapp.com/6quBKPo9

**Comment by flamber** [comment]
Excellent! I can reproduce that. And yes, it seems like there's some scroll issues.
I'm going to create a new issue, so we don't have to read through all the troubleshooting :) #11887
