### ISSUE TITLE
Timestamp is always present in dates when exporting to CSV

### ISSUE THREAD

**Issue by bplmp** [metabase/metabase#12964]
**Describe the bug**
Dates are displayed without timestamp in visualization for native queries, but when exported they include timestamp.

**To Reproduce**
1. Create native query with a date
2. Set visualization to table
3. Go to settings and click "Off" in "Show the time"
4. (If you export the CSV before saving the question it works, strangely)
5. Save question
6. Export CSV
7. Open CSV and see that timestamp is still present

**Expected behavior**
I expect the CSV export to look just like what I am seeing in the table visualization, without the timestamp.

**Screenshots**
![image](https://user-images.githubusercontent.com/11858154/88083038-ef441b00-cb58-11ea-9067-2bbc5382ace1.png)

CSV:
```
date
2020-07-21T00:00:00Z
```

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.123-coreos",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "mysql",
      "redshift",
      "postgres",
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
We use CSV exports from Metabase to load into Google Sheets. This is breaking the formatting of some of the sheets and formulas.

**Additional context**
Note: this happened when updated Metabase from 0.34 to 0.35. The DB this is happening on is AWS Redshift.

**Comment by flamber** [comment]
Hi @bplmp 
Are you sure it only started after upgrading to 0.35? It has always (or for many versions) been like that. CSV does not apply formatting (#10879) and there's different behavior between saved and unsaved questions, when exporting https://github.com/metabase/metabase/issues/10803#issuecomment-638480542

**Comment by bplmp** [comment]
Hey @flamber, thanks for the reply. Yes, it is strange but it started right after we updated to 0.35... Many of our users started having this issue right after the update.

I guess this is duplicate of https://github.com/metabase/metabase/issues/10879 then. I just wasn't sure if formatting in CSV is something you plan to support in the future or not, or maybe the discussion is still ongoing...

**Comment by flamber** [comment]
@bplmp Hmmm, just tested, something happened between 0.34.3 and 0.35.0, where date columns got time and timezone added.
I'm sure this is adding to the confusion in #10803. But it's partially unrelated to #10879, since you were returning a date column.

**Comment by bplmp** [comment]
@flamber makes sense, will keep an eye on this issue then, thanks!

**Comment by amommendes** [comment]
@flamber just to point out we also tested this in 0.36 version and observed the same behavior

**Comment by amommendes** [comment]
@flamber, I inspected the code and the problem is related to the default value of `:format-rows` option.
In the `/:card-id/query/:export-format` [endpoint](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/api/card.clj#L642) (which is used to export when questios are saved) we dont pass `:format-rows? false` as we do in the `/api/dataset/:export-format` [endpoint](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/api/dataset.clj#L91)

**Comment by amommendes** [comment]
@flamber, I inspected the code and the problem is related to the default value of `:format-rows` option.
In the `/:card-id/query/:export-format` [endpoint](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/api/card.clj#L642) (which is used to export saved questios) we dont pass `:format-rows? false` as we do in the `/api/dataset/:export-format` [endpoint](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/api/dataset.clj#L91). Because we don't pass `false` to `:format-rows` in card export endpoint, it'll assume the default value in the `format_rows.clj`, which is defined as  `true` in the `format-rows` [method](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/query_processor/middleware/format_rows.clj#L77):
```clojure
(defn format-rows
  "Format individual query result values as needed.  Ex: format temporal values as ISO-8601 strings w/ timezone offset."
  [qp]
  (fn [{{:keys [format-rows?] :or {format-rows? true}} :middleware, :as query} rff context]
    (qp query
        (if format-rows?
          (fn [metadata]
            (format-rows-xform (rff metadata)))
          rff)
        context)))
```

However, [following the MBQL schema](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/backend/mbql/src/metabase/mbql/schema.clj#L955), the default value of this parameter should be `false`. WDYT?

I would suggest to change [this line](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/query_processor/middleware/format_rows.clj#L80) in the `format-rows` [method](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/query_processor/middleware/format_rows.clj#L77) as following:

```clojure
  (fn [{{:keys [format-rows?] :or {format-rows? false}} :middleware, :as query} rff context]
```
Testing locally it resulted in no formatting csv rows, as would be expected!

**Comment by flamber** [comment]
@amommendes I don't know the consequence of that, but if it does pass tests, then please submit a PR.

**Comment by amommendes** [comment]
@flamber thanks by the answer. We could change this in a more restrict way directly in the /:card-id/query/:export-format endpoint, adding the `:format-rows? false` in the [middleware options](https://github.com/metabase/metabase/blob/b6ad9f508971017f92f552d90ca9e7787272acc9/src/metabase/api/card.clj#L642) as following:

```clojure
(api/defendpoint ^:streaming POST "/:card-id/query/:export-format"
  "Run the query associated with a Card, and return its results as a file in the specified format. Note that this
  expects the parameters as serialized JSON in the 'parameters' parameter"
  [card-id export-format :as {{:keys [parameters]} :params}]
  {parameters    (s/maybe su/JSONString)
   export-format dataset-api/ExportFormat}
  (binding [cache/*ignore-cached-results* true]
    (run-query-for-card-async
     card-id export-format
     :parameters  (json/parse-string parameters keyword)
     :constraints nil
     :context     (dataset-api/export-format->context export-format)
     :middleware  {:skip-results-metadata? true :format-rows? false})))
``` 
WDYT?

**Comment by flamber** [comment]
Fixed by #13447

**Comment by nickhamlin** [comment]
@flamber I just tested this in both 0.36.8 and 0.37.0 and I'm still not able to get metabase to omit the timestamps in a CSV export. I'm following the exact steps described in https://github.com/metabase/metabase/issues/10689 if it's helpful in reproducing, and the details of our stack are below. Any ideas or suggestions you have are very much appreciated, since getting this fixed would remove a major blocker for our team. Thanks again!

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.19.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-23",
      "tag": "v0.36.8.1",
      "branch": "release-0.36.x",
      "hash": "bcc9401"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
@nickhamlin Visual formatting is not applied to exports - #10879 - you can group by Day, which is then respected.

**Comment by mazameli** [comment]
@flamber I think it's sounding though like this [wasn't happening to folks until 0.35](https://github.com/metabase/metabase/issues/12964#issuecomment-662056143), so if @nickhamlin etc. are still experiencing it, doesn't that mean the regression hasn't been fixed?
