### ISSUE TITLE
shutdowns sometimes leave liquibase locks

### ISSUE THREAD

**Issue by snarfed** [metabase/metabase#1354]
we're running the bare jar. sometimes when we kill and restart metabase (ie the JVM process), it hangs after _Verify Database Connection ... CHECK_ and then dies after ~5m with the exception below.

we fix this by clearing the stale lock: we run `org.h2.tools.Server`, connect to `jdbc:h2:~/metabase.db;IFEXISTS=TRUE`, and run `DELETE FROM databasechangeloglock;`. it'd be nice if we didn't have to though. :P

(congrats again on the launch, btw! looks like reception has been great so far!)

```
liquibase.exception.DatabaseException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by ... (...) since 10/23/15 9:08 PM
	at com.metabase.corvus.migrations.LiquibaseMigrations.setupDatabase(LiquibaseMigrations.java:25)
	at metabase.db$migrate.invoke(db.clj:62)
	at metabase.db$setup_db.doInvoke(db.clj:108)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init.invoke(core.clj:99)
	at metabase.core$_main.doInvoke(core.clj:176)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by ... (...) since 10/23/15 9:08 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:175)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:184)
	at liquibase.Liquibase.update(Liquibase.java:177)
	at com.metabase.corvus.migrations.LiquibaseMigrations.setupDatabase(LiquibaseMigrations.java:23)
	... 9 more
```

**Comment by snarfed** [comment]
actually, it looks like this is probably fixed by #1082. we saw this today when upgrading from 0.11.2 to 0.12.1, and 0.11.2 didn't have that fix, so that makes sense.

tentatively closing. feel free to reopen if i misdiagnosed.

**Comment by vkovalskiy** [comment]
@snarfed this problem still active and we have to `DELETE FROM databasechangeloglock` every time we update to the new version and have to restart metabase 😢

**Comment by salsakran** [comment]
@vkovalskiy what are you running MB on? Is there anything weird happening in the logs towards the end of shutdown?

**Comment by damm** [comment]
I just moved our metabase container from one server to another and I had to truncate the table in order for it to startup correctly.

Rather confusing

**Comment by camsaul** [comment]
This is fixed by #3295 so starting with Metabase 0.20 this should no longer be an issue.
