### ISSUE TITLE
Wrong day names are displayed when using not-Sunday as start of the week and grouping by "Day of week"

### ISSUE THREAD

**Issue by nbriche** [metabase/metabase#13604]
When grouping by day of the week, the DATA use the correct date but the AXIS LABELS still start with Sunday.

**To Reproduce**
- Start of the week: Monday
- Sample dataset: table Orders
- Filter: "Created at" between 2020-03-02 and 2020-03-03 (monday and tuesday)
- Summarize: by Count and group by Created At (by day of the week)
- Visualization: Bar, X-axis: Ordinal

**Expected behavior**
- Two bars, one for Monday 2020-03-02 labelled "Monday", one for Tuesday 2020-03-03 labelled "Tuesday"

**Actual behavior**
- Two bars, one for Monday 2020-03-02 labelled "Sunday", one for Tuesday 2020-03-03 labelled "Monday"

![Capture d’écran de 2020-10-27 14-27-02](https://user-images.githubusercontent.com/424286/97307990-a7701680-1860-11eb-9651-b453d29dd0f8.png)

**Information about your Metabase Installation:**
- Metabase version: 0.37.0.2
- Metabase hosting environment: Jar-file on Ubuntu 16.04
- Metabase internal database: H2

**Severity**
Rather annoying. We do a lot of week-over-week stats (data from our helpdesk). Until now we had to make do with graphs starting with Sunday, which look lopsided (not a lot of issues opened on a Sunday, so the graphs look like calm Mondays and busy Tuesdays). This bug makes the graphs look correct (busy on week start, calm on weekends) but can't be used with wrong labels.

**Comment by nemanjaglumac** [comment]
It seems this is working in the latest `master`. I am preparing a Cypress repro test to make sure. Will push by the end of the day.

**Comment by camsaul** [comment]
Fixed by #13740

**Comment by ellie-metabase** [comment]
It looks like this is still broken for postgres + redshift.  More details to follow - reopening bug

**Comment by camsaul** [comment]
Fixed by #15040
