### ISSUE TITLE
Linked filters breaking SQL questions on v0.37.2

### ISSUE THREAD

**Issue by phsantiago** [metabase/metabase#13868]
**Describe the bug**
When embedding a report with chained filters, questions written in SQL break.  
Removing the link between filters make them work again.  

Happens when embedding the dashboard only, doesn't happen when embedding the **question** or on the dashboard view.

**Logs**
 - Metabase server logs
```clj
[29e3343c-5749-4dc7-a1a1-ebdf3102a026] 2020-11-22T20:25:24-03:00 ERROR metabase.query-processor.middleware.catch-exceptions Erro ao processar a query: null
{:database_id 1,
 :started_at #t "2020-11-22T23:25:23.981289Z[Etc/UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Erro ao construir o mapa de paramêtros da busca",
   :stacktrace
   ["--> driver.common.parameters.values$fn__76296$query__GT_params_map__76301$fn__76305.invoke(values.clj:338)"
    "driver.common.parameters.values$fn__76296$query__GT_params_map__76301.invoke(values.clj:320)"
    "driver.sql$fn__78104.invokeStatic(sql.clj:46)"
    "driver.sql$fn__78104.invoke(sql.clj:42)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:53)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:44)"
    "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
    "mbql.util.match$replace_in_collection$iter__26258__26262$fn__26263.invoke(match.clj:132)"
    "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
    "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
    "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:62)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:80)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:76)"
    "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101$fn__48102.invoke(parameters.clj:85)"
    "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101.invoke(parameters.clj:82)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48122.invoke(parameters.clj:114)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46508.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47127.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__41200.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49058.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348$fn__48352.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47345.invoke(fetch_source_query.clj:267)"
    "query_processor.middleware.store$initialize_store$fn__49067$fn__49068.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__49067.invoke(store.clj:10)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__46385.invoke(cache.clj:214)"
    "query_processor.middleware.validate$validate_query$fn__49076.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47470.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41038.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49043.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46748.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48211.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46691.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___39827$thunk__39828.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___39827$fn__39830.invoke(reducible.clj:108)"],
   :error_type :invalid-query,
   :ex-data
   {:type :schema.core/error,
    :tags
    {"created" {:id "94f5ac13-34a8-942a-0f07-673ac2e1b9c1", :name "created", :display-name "Created", :type :dimension, :dimension [:field-id 12], :widget-type :date/month-year, :default nil},
     "person_name" {:id "1c534752-7bfc-346b-91b1-6337534fe381", :name "person_name", :display-name "Person name", :type :dimension, :dimension [:field-id 22], :widget-type :category, :default nil}},
    :params
    [{:type :category, :target [:dimension [:template-tag "person_name"]], :slug "categoria", :value "Carolina Crona", :name "Categoria", :id "4cd0131b", :filteringParameters ["222b245f"]}]}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true},
  :native
  {:query
   "select\n    *\nfrom\n    ORDERS\n        inner join PEOPLE on PEOPLE.ID = ORDERS.USER_ID\n        inner join PRODUCTS on PRODUCTS.ID = ORDERS.PRODUCT_ID\nWHERE 1 = 1\n    [[AND {{created}}]]\n    [[AND {{person_name}}]]",
   :template-tags
   {"created" {:id "94f5ac13-34a8-942a-0f07-673ac2e1b9c1", :name "created", :display-name "Created", :type :dimension, :dimension [:field-id 12], :widget-type :date/month-year, :default nil},
    "person_name" {:id "1c534752-7bfc-346b-91b1-6337534fe381", :name "person_name", :display-name "Person name", :type :dimension, :dimension [:field-id 22], :widget-type :category, :default nil}}},
  :database 1,
  :parameters
  ({:type "category", :target [:dimension [:template-tag "person_name"]], :slug "categoria", :value "Carolina Crona", :name "Categoria", :id "4cd0131b", :filteringParameters ["222b245f"]}),
  :async? true,
  :cache-ttl nil},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.common.parameters.values$fn__76272$value_for_tag__76277.invoke(values.clj:308)"
  "driver.common.parameters.values$fn__76296$query__GT_params_map__76301$fn__76305$iter__76307__76311$fn__76312.invoke(values.clj:330)"
  "driver.common.parameters.values$fn__76296$query__GT_params_map__76301$fn__76305.invoke(values.clj:329)"
  "driver.common.parameters.values$fn__76296$query__GT_params_map__76301.invoke(values.clj:320)"
  "driver.sql$fn__78104.invokeStatic(sql.clj:46)"
  "driver.sql$fn__78104.invoke(sql.clj:42)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:44)"
  "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
  "mbql.util.match$replace_in_collection$iter__26258__26262$fn__26263.invoke(match.clj:132)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
  "query_processor.middleware.parameters$expand_all$replace_48080__48081.invoke(parameters.clj:62)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:62)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:80)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:76)"
  "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101$fn__48102.invoke(parameters.clj:85)"
  "query_processor.middleware.parameters$fn__48096$substitute_parameters_STAR___48101.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48122.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46508.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47127.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__41200.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49058.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348$fn__48352.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48348.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47345.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__49067$fn__49068.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__49067.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46385.invoke(cache.clj:214)"
  "query_processor.middleware.validate$validate_query$fn__49076.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47470.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__41038.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49043.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46748.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48211.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46691.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___39827$thunk__39828.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___39827$fn__39830.invoke(reducible.clj:108)"],
 :context :embedded-dashboard,
 :error "Input to value-for-tag does not match schema: \n\n\t   [nil (named [{:filteringParameters disallowed-key}] params)]  \n\n",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:type :schema.core/error,
  :value
  [{:id "94f5ac13-34a8-942a-0f07-673ac2e1b9c1", :name "created", :display-name "Created", :type :dimension, :dimension [:field-id 12], :widget-type :date/month-year, :default nil}
   [{:type :category, :target [:dimension [:template-tag "person_name"]], :slug "categoria", :value "Carolina Crona", :name "Categoria", :id "4cd0131b", :filteringParameters ["222b245f"]}]],
  :error [nil (named [{:filteringParameters disallowed-key}] params)]},
 :data {:rows [], :cols []}}

```
(IDK why but metabase keep translating log errors like in this line "Erro ao construir o mapa de paramêtros da busca" I think it is:) https://github.com/metabase/metabase/blob/f02c07ce4c658b944491fd010f04bb663a0daa49/src/metabase/driver/common/parameters/values.clj#L338

**Can it be reproduced on the sample dataset?**
Yes, following **To Reproduce** instructions below.

**Your Metabase version**
v1.37.2

**Where Metabase is running (Docker image, AWS Elastic Beanstalk, Heroku, Linux/Ubuntu, etc)**
GCP, Compute Engine

**Which database is used**
MySQL 5.7

**To Reproduce**

1. Create a custom sql question with the following SQL:
```sql
select
    *
from
    ORDERS
        inner join PEOPLE on PEOPLE.ID = ORDERS.USER_ID
        inner join PRODUCTS on PRODUCTS.ID = ORDERS.PRODUCT_ID
WHERE 1 = 1
    [[AND {{created}}]]
    [[AND {{person_name}}]]
```

2. Custom fields:
>created field configs:
Variable Type: Field filter
Map to: Orders.Created_at
Type: Month and year
Not required

>person_name field configs:
Variable Type: Field filter
Map to: People.name
Type: Category
Not required

3. Create a dashboard with the custom question created above.  
4. Edit the dashboard:
4.1: Add a `time` filter and link it to `created` field
4.2: Add a `category` filter and link it to `Person name` field. Link it to the `time` filter on chained filters.
5. Save the dashboard
6. See that both the chaining and filtering works within metabase
7. Click on `Sharing and Embeding` and `Embed this dashboard in an application`
8. Make the `category` filter `editable`
9. Filter for `Lina Labadie`
10. See that the card displays the error message

**Expected behavior**
Being able to provide editable linked fields in embed dashboards.

**Screenshots**
|when linked|when unlinked|
|-|-|
|![image](https://user-images.githubusercontent.com/10498833/99920571-3870cb00-2d03-11eb-803d-9ece37a77111.png)|![image](https://user-images.githubusercontent.com/10498833/99920624-7ff75700-2d03-11eb-97b3-4f6f8fe2bde0.png)|

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9+11",
    "os.name": "Linux",
    "os.version": "4.19.0-12-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-11-16",
      "tag": "v0.37.2",
      "branch": "release-x.37.x",
      "hash": "25e5f70"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Blocking some users, about 8 customers depending upon that.

**Additional context**
Related issue: #13639

**Comment by mazameli** [comment]
@flamber I'm wondering if this is related to or the same as https://github.com/metabase/metabase/issues/13639, which has close to 20 upvotes.

**Comment by camsaul** [comment]
Fixed by #13877

**Comment by remis87** [comment]
@phsantiago did this fix it for you? Istill have the exact same problem on
` "version": {
      "date": "2020-12-03",
      "tag": "v1.37.3",
      "branch": "release-x.37.x",
      "hash": "2f1e783"
    }`

**Comment by dacort** [comment]
@remis87 I have a reproduction for this that is still failing. Going to reopen this issue once I create a Cypress reproduction test case.

**Comment by remis87** [comment]
Can we get at least any indicator for progress or an acknowledgement here? It becomes increasingly frustrating that this feature takes forever to be usable (speaking as an enterprise customer here)

**Comment by rlotun** [comment]
We are looking into this now and will have an an ETA on the fix as soon as possible. Apologies for the confusion here!

**Comment by camsaul** [comment]
Fixed by #14248
