### ISSUE TITLE
Regression : custom column with the same name as a table column

### ISSUE THREAD

**Issue by maximepvrt** [metabase/metabase#14255]
Worked perfectly on V0.36.8.2 but regression after migration to V0.37.4

If I select the custom column now, I see the table column

![Capture d’écran 2021-01-05 à 11 34 56](https://user-images.githubusercontent.com/1840026/103636469-4f354f00-4f4a-11eb-8742-a4df64c8a163.png)
![Capture d’écran 2021-01-05 à 11 34 49](https://user-images.githubusercontent.com/1840026/103636464-4e042200-4f4a-11eb-8895-a79b0bd5525d.png)

My source labels are the source column table values and not the custom column values
![Capture d’écran 2021-01-05 à 11 35 55](https://user-images.githubusercontent.com/1840026/103636468-4f354f00-4f4a-11eb-97b4-81d494b1c5ca.png)

**Comment by flamber** [comment]
Hi @maximepvrt 
I cannot reproduce. Please provide "Diagnostic Info" from Admin > Troubleshooting, and which database you are querying.
And the query generated - either from "View the SQL" or the response of the request.

**Comment by maximepvrt** [comment]
``` {
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Linux",
    "os.version": "5.10.1+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

My database is postgres

```SELECT CAST("source"."created_at" AS date) AS "created_at", "source"."source" AS "source", count(*) AS "count"
FROM (SELECT "public"."conversation"."created_at" AS "created_at", "platform__via__platform_id"."name" AS "name", "public"."conversation"."source" AS "source", "public"."conversation"."platform_id" AS "platform_id", "platform__via__platform_id"."id" AS "id", concat("platform__via__platform_id"."name", '-', "public"."conversation"."source") AS "source_2" FROM "public"."conversation"
LEFT JOIN "public"."platform" "platform__via__platform_id" ON "public"."conversation"."platform_id" = "platform__via__platform_id"."id") "source"
GROUP BY CAST("source"."created_at" AS date), "source"."source"
ORDER BY CAST("source"."created_at" AS date) ASC, "source"."source" ASC
```

**Comment by flamber** [comment]
Regression since 0.37.1 - likely caused by #13648

Workaround: is to have unique names for Custom Columns that doesn't overlap existing table column names.

Reproduce:
1. Custom question > Sample Dataset > Products - Custom Column `concat([Category], "2")` as `CATEGORY` (uppercase name is important on H2, other databases handle casing differently) - summarize Count by CATEGORY (the CC)
![image](https://user-images.githubusercontent.com/1447303/103672658-dd2a2d80-4f7c-11eb-8a72-863adcc554f7.png)
2. Returns the Custom Column name as the header, but the values comes from the table column:
![image](https://user-images.githubusercontent.com/1447303/103673614-16af6880-4f7e-11eb-80a0-71ffaddec0ee.png)

The generated query looks like this, which seems incorrect, since the table column Category shouldn't be in select-clause:
```
SELECT "source"."CATEGORY" AS "CATEGORY", count(*) AS "count"
FROM (SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", concat("PUBLIC"."PRODUCTS"."CATEGORY", '2') AS "CATEGORY_2" FROM "PUBLIC"."PRODUCTS") "source"
GROUP BY "source"."CATEGORY"
ORDER BY "source"."CATEGORY" ASC
```
Whereas previous versions would do this:
```
SELECT "source"."CATEGORY" AS "CATEGORY", count(*) AS "count"
FROM (SELECT concat("PUBLIC"."PRODUCTS"."CATEGORY", '2') AS "CATEGORY", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY_2" FROM "PUBLIC"."PRODUCTS") "source"
GROUP BY "source"."CATEGORY"
ORDER BY "source"."CATEGORY" ASC
```

**Comment by camsaul** [comment]
@flamber / @nemanjaglumac , is this fixed in 0.38.0? This seems like the sort of thing I may have inadvertently fixed with the other nested query fixes

**Comment by flamber** [comment]
@camsaul Tested 0.38.0, but it still includes the db column in the sub-select, and gives the Custom Column a suffix `_2`:
`SELECT "source"."CATEGORY" AS "CATEGORY", count(*) AS "count"
FROM (SELECT "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", concat("PUBLIC"."PRODUCTS"."CATEGORY", '2') AS "CATEGORY_2" FROM "PUBLIC"."PRODUCTS") "source"
GROUP BY "source"."CATEGORY"
ORDER BY "source"."CATEGORY" ASC`

**Comment by nemanjaglumac** [comment]
Cypress test is still failing locally. It sees custom column name, but fields are not concatenated (as custom expression suggested):
![image](https://user-images.githubusercontent.com/31325167/108376791-a2661700-7203-11eb-8548-a5026345678c.png)
