### ISSUE TITLE
Moved collections not being correctly included in `api/collection/tree` API response

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#14280]
**Describe the bug**
While trying to do some organization on our stats instance I was moving around a bunch of collections that had "Test" data we've made into a new parent "Test" folder to clean up our sidebar a bit.  After moving a few, I noticed collections I'd moved weren't reflecting in the new sidebar (they do reflect properly in the move modal). Strangely this is only happening with a few. Another couple I'd moved are showing up exactly as expected.

**Logs**
JS console
```Uncaught TypeError: can't access property "length", n.name is undefined```

That error makes more sense after inspecting the API response. Somehow there's a child node with no info wrapping one of the moved collections. I'm not entirely sure what could cause the API to generate a response like this. I also moved 3 collections, so I'm not sure why the other ones aren't showing up.

```
  {
    "description": "If you're testing things out, try and put things here.",
    "archived": false,
    "children": [
      {
        "children": [
          {
            "description": "Automatically generated cards.",
            "archived": false,
            "slug": "questions_for__a_look_at_your_people_table_",
            "color": "#509EE3",
            "name": "Questions for \"A look at your People table\"",
            "personal_owner_id": null,
            "id": 115,
            "location": "/179/18/",
            "namespace": null
          }
        ]
      }
    ],
    "slug": "testing",
    "color": "#509EE3",
    "name": "Testing",
    "personal_owner_id": null,
    "id": 179,
    "location": "/",
    "namespace": null
  },
```

**To Reproduce**
I haven't found a consistent reproduction yet, but this is what initially happened.

1. Create a new collection
2. Navigate to an existing collection.
2. Use the "Edit collection" action to open up the collection details modal and select a new parent collection from the dropdown.
3. Move the existing collection to the new collection.
4. Navigate to the new "parent" collection and no content is visible.

**Expected behavior**
The moved collection is visible under its new parent immediately.

**Information about your Metabase Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: Windows
- Metabase version: 0.38-rc1
- Metabase hosting environment:
- Metabase internal database: Postgres

**Severity**
Severe, can result in items becoming inaccessible.

**Comment by camsaul** [comment]
Is this on `latest` master? I fixed a similar bug with the (mostly) empty API response in #14251

**Comment by kdoh** [comment]
I encountered it on stats, but haven't been able to trigger it locally so it's possible. I'll investigate.

**Comment by kdoh** [comment]
@camsaul Looks like yes. I'm not sure what the deployed instance's hash was when I was moving things this morning, but at the very least it's still an issue as of right now (still not able to see the right items) with the current build.

![image](https://user-images.githubusercontent.com/5248953/103786069-f9c07700-5009-11eb-9962-7131ea5bb1e0.png)

**Comment by camsaul** [comment]
I will take a look

**Comment by nemanjaglumac** [comment]
I managed to reproduce it on `metabase-head` Docker image. Will try to make a Cypress repro ASAP.
