### ISSUE TITLE
Viewing two columns with same name across tables fails

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#1447]
Looks like there's no namespacing in effect when I do a join in the visual query builder to "view by data_table.col_name and connected_table.col_name" where the two tables are distinct but the column I'm asking for has the same field name for both.

Screenshot:

<img width="850" alt="screen shot 2015-11-04 at 5 34 49 pm" src="https://cloud.githubusercontent.com/assets/193187/10954355/e6a44f32-831a-11e5-83d3-b64910c6c85c.png">

Returns only 1 column in the results table instead of 2 columns, conceivably because the field names ("name" in this case) conflict?

I'm guessing the fix for this would be to "namespace" the fields by their parent table.

**Comment by camsaul** [comment]
It turns out this was already fixed in PR #1467. I've added a unit test for this issue specifically to verify that it is fixed #1781

**Comment by agilliland** [comment]
This isn't fully fixed from what I'm seeing, there are a couple things still wanting here ...

1. The QP is simply renaming the occurrences of the field name beyond the first one (e.g. CREATED_AT_2) and returning it to the UI in that form, which is not accurate.
2. The metadata being formed for the column with the `_2` appended to it is wrong and indicates that we didn't properly match up the real fields metadata with what was returned.

I'm reopening this so that we can address these things.

**Comment by camsaul** [comment]
@agilliland this is fixed. The problem was only one column was being returned by the query processor. Now, both are being returned.

We're not doing any special renaming. Suffixing a name like `_2` is done by the database. That's normal DB behavior. If we want to dynamically calculate better names for these fields that's a separate and larger issue.
