### ISSUE TITLE
Scrolling in Firefox is difficult using the scrollbar

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#14607]
**Describe the bug**
Scrolling in Firefox is difficult using the scrollbar

**To Reproduce**
Specially in Pivot Table:
![screencast-2021-02-01_15 25 38](https://user-images.githubusercontent.com/1447303/106479778-fbffdf00-64aa-11eb-95ad-5e19d3fbe4fe.gif)

**Expected behavior**
Same behavior as Chrome

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

**Additional context**
Likely very related to #13773. And to #10339

**Comment by ariya** [comment]
Could this be specific to macOS? I'm trying it on Firefox 85 on Windows and Linux, and neither demonstrates the same level of laggy scrolling behavior.

@flamber if there's a particular stress-test query which I shall try, let me know.

**Comment by flamber** [comment]
@ariya I'm using Linux, but on an older computer. It's not that it's laggy, it's that the scrollbar "clickability" is off. There has been several fixes the past couple of days, so perhaps it has been fixed - haven't tested yet.

**Comment by ariya** [comment]
> @ariya I'm using Linux, but on an older computer. It's not that it's laggy, it's that the scrollbar "clickability" is off.

Thanks for the clarification @flamber!

I ran my investigations on a VM with (intentionally) capped CPU usage so hopefully that can highlight any potential performance problem.

Subjectively, I couldn't reproduce the clickability issue. However, looking at the profiler in Firefox Dev Tools revealed a few instances where the scroll event is taking too long (certainly longer than when I tried to profile the same way in Chrome/Chromium), e.g. one of them is 123 ms which definitely won't lend itself to a smooth scrolling behavior (again, potentially related to #10339):

![image](https://user-images.githubusercontent.com/7288/106786022-ee5d6d00-6602-11eb-9cfa-ca1f8f5eee2b.png)

**Comment by uladzimirdev** [comment]
The linked fix doesn't actually solve the problem as I couldn't reproduce it on any version I tested started from 0.39.5, but improves rendering performance overall
