### ISSUE TITLE
Error showing number of lines and sometimes black page on source on version 0.39.4

### ISSUE THREAD

**Issue by raphamotta** [metabase/metabase#16681]
**Describe the bug**
After update from 0.39.2 to 0.39.4 it starts to show {0} as number os lines, version and sometimes black pages. See this image:

![image](https://user-images.githubusercontent.com/39523113/122611706-26b49380-d058-11eb-8e13-918af363cc52.png)
![image](https://user-images.githubusercontent.com/39523113/122611802-5368ab00-d058-11eb-88b2-7cf250c2c25b.png)
![image](https://user-images.githubusercontent.com/39523113/122611811-582d5f00-d058-11eb-86c6-6da1c194813e.png)

**Logs**
do not apply

**To Reproduce**
1. update on AWS Elastic Beanstalk from 0.39.2 to 0.39.4
2. Enjoy

**Expected behavior**
Show numbers, not {0}

**Screenshots**
Above

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.198-152.320.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-15",
      "tag": "v0.39.4",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by flamber** [comment]
Hi @raphamotta 
I cannot reproduce with the Docker version, nor JAR.
Please make sure to refresh your cache if you are using a reverse-proxy. And also your browser cache, and refresh the browser.
The problem was fixed in 0.39.3 - #15694

**Comment by raphamotta** [comment]
@flamber  You are right, just tested the jar version and the bug does not existis. However, the bug still exists on AWS Elastic Beanstalk, I tested in several browsers and computers. Not using reverse proxy and cache is clean.

**Comment by raphamotta** [comment]
I did some tests and the problem is on the language.  If in the user account setting I put "Use site default", it switch to Brazilian Portuguese and the bug happens. If I choose "Portuguese(Brazil)", there's no bug. The bug happens only when I choose "Use site default".

The bug happens only on AWS Elastic Beanstalk version, did not happens on jar version.

**Comment by flamber** [comment]
@raphamotta But the EB version is just a Docker image. Well, something must be wrong with the build of 0.39.4

**Comment by flamber** [comment]
@raphamotta Please provide screenshots of your settings. I don't understand what you have set in User Account and what is set in Admin > Settings > Localization.

**Comment by flamber** [comment]
@raphamotta I have found the problem. Go to Admin > Settings > Localization > and set the language to "Portuguese (Brazil)" again. That will fix the problem. Creating a new issue with the core problem.

**Comment by raphamotta** [comment]
@flamber thank you, I saw the rewrite issue, much better explained. Sorry if I was not clear trying to explain the issue.
