### ISSUE TITLE
"Edited by" help text not fully translated

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16962]
**Describe the bug**
We introduced "Edited by..." help text for dashboards and questions in v0.40. It doesn't seem to be fully translated.

**Logs**

**To Reproduce**
1. Change language to something other than English
2. Go to any existing dashboard
3. Notice untranslated string

French
![image](https://user-images.githubusercontent.com/31325167/125128186-fbc0db00-e0fd-11eb-9878-ed83a7052659.png)

Czech
![image](https://user-images.githubusercontent.com/31325167/125128366-3fb3e000-e0fe-11eb-8af1-12d8d6c02b83.png)

**Expected behavior**
All parts of string should be properly translated.

**Information about your Metabase Installation:**
you can check this on master, 3555b7b

**Severity**
?

**Comment by daltojohnso** [comment]
This will get fixed by https://github.com/metabase/metabase/pull/16803/files#diff-c11a84e3eab3cba172d5262e315abcc0ccaa235a432de8fa5f6b2df23c373012R45

**Comment by daltojohnso** [comment]
This will get fixed by https://github.com/metabase/metabase/pull/16803/files#diff-c11a84e3eab3cba172d5262e315abcc0ccaa235a432de8fa5f6b2df23c373012R45 which is in a PR that should merge this week to `master`.

**Comment by nemanjaglumac** [comment]
@daltojohnso I still see this issue on the latest `master`.

**Comment by flamber** [comment]
@nemanjaglumac I don't think there are any updated translations for this yet, so that's likely why you're still seeing the English.

**Comment by nemanjaglumac** [comment]
Revisited this and all strings seem to be fixed now.
