### ISSUE TITLE
"Show error details" in Query Builder should be disabled after clicking

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19900]
Steps to repro:

1. Run any query that fails.
2. See the `There was a problem with your question` error
3. Click `Show error details`
4. Error details are shown, but the `Show error details` link remains available active (i.e., it's still blue and hovering over it still adds the underline) and you can still click it.

I would expect that to get grayed out or give **some** sort of indication it has already been clicked after clicking it. It would be nice if it changed to a `Hide error details` button so you could hide them again, but I'm not super concerned about that.

I sat around for a minute or two trying to figure out why it wouldn't show me error details and kept clicking that button (thinking it was broken) before I realized that it was showing the error details (they were just not what I was expecting)

**Comment by WiNloSt** [comment]
I'm not sure if this is something already fixed in 0.42 as it was released on Feb 8 which is after this issue was created. @flamber is this something we still have to fix?

#### Testing steps
1. Click `+ New` button
2. Select `SQL query`
3. Run `select * from INVALID;`

And I couldn't find `There was a problem with your question` or `Show error details`

#### Screenshot
![Screen Shot 2022-03-03 at 7 10 14 PM](https://user-images.githubusercontent.com/1937582/156562201-3666852a-9d1c-4118-9599-390ae33735c9.png)

**Comment by flamber** [comment]
@WiNloSt It's not fixed. You'll have to do it with GUI questions:
1. Native > `select 1` - save as Q1
2. Click "Explore results" to use it as a Saved Question
3. Save the GUI question as Q2
4. Go back to Q1 and generate something invalid like `select;` and save
5. Then go back to Q2, which will error
![image](https://user-images.githubusercontent.com/1447303/156564062-2e86a9bd-269e-4336-a185-77e5428cf062.png)

**Comment by WiNloSt** [comment]
@flamber I can reproduce the bug now thanks!
