### ISSUE TITLE
Slack Pulses don't handle unicode correctly

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#2027]
###### This is what you see on the front-end

![screen shot 2016-02-25 at 1 18 52 pm](https://cloud.githubusercontent.com/assets/1455846/13334738/659bbbfe-dbc2-11e5-95df-633ae4b155db.png)

###### This is what you see in slack

![screen shot 2016-02-25 at 1 19 14 pm](https://cloud.githubusercontent.com/assets/1455846/13334755/74d33ebc-dbc2-11e5-9988-29cb9e7db30a.png)

###### Please fill in the blanks, if relevant: 

*  I am using the Chrome browser.
*  My computer's OS is Mac [Dre].
*  My database is connected. (Sample dataset - H2).
*  My Metabase version is `release-0.15.0`

**Comment by camsaul** [comment]
Fixed in time for `0.15` .

**Comment by agilliland** [comment]
:+1:

**Comment by on99** [comment]
![image](https://user-images.githubusercontent.com/13196393/31581198-ae525eaa-b197-11e7-982d-69c99b1111c9.png)

Seems like it's not resolved yet, I am using the latest metabase (v0.26.1). The *box* should be some Chinese characters.

**Comment by Kcin1993** [comment]
![截圖 2021-06-25 下午3 39 37](https://user-images.githubusercontent.com/8435927/123388699-aa77fe00-d5cb-11eb-8836-cf9dfd95ac9c.png)

The missing words are Chinese characters. My Metabase version is v0.39.4, released on 2021-06-15. 
This happened in localhost, hosting on my computer. I'm not sure if it is the reason.

**Comment by flamber** [comment]
@Kcin1993 There's an issue open for that #2342 - upvote by clicking :+1: on the first post
