### ISSUE TITLE
Filter dropdown not showing remapped values on the dashboard for FKs

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#21528]
**Describe the bug**
Filter dropdowns of remapped FK does not show the remapped name on the dashboard - only on the question.

**Workaround**: Instead of using remapping, select the Field Filter of the column target column (in the example below, Product.Title instead of Orders.Product_ID), but make sure the table in part of the join:
https://www.metabase.com/learn/sql-questions/field-filters#creating-a-filter-widget-with-a-dropdown-menu

**To Reproduce**
1. Admin > Data Model > Sample > Orders > Product ID :gear: > Display values: `Use foreign key` => `Title`, Filtering on this field: `Plain input box` => `A list of all values`
(Re-scan the field, and do a browser refresh to avoid 15542/16322)
![image](https://user-images.githubusercontent.com/1447303/161065156-e42f8c81-031a-496f-95fa-642439344b99.png)
2. Native > Sample > `select count(*) from products where {{f}}` - set as Field Filter of Orders.Product_ID
![image](https://user-images.githubusercontent.com/1447303/161065248-5a0ae3e7-31e6-440e-a3c1-5095755e2caf.png)
3. Open the filter widget - it will show remapped names and IDs
![image](https://user-images.githubusercontent.com/1447303/161065497-48f7b5cd-25a6-4701-b800-ea715b57d4ba.png)
4. Add the question to a dashboard and add an ID filter and connect to the card.
Click filter widget - it will only show IDs
![image](https://user-images.githubusercontent.com/1447303/162273634-3c59e457-87f8-4982-804f-40a58414cd3d.png)

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.4 - regression since 0.42.0

**Additional context**
Related to #21382

**Comment by losrebellos** [comment]
When querying the API to retrieve the values for a specific param ([here](http://localhost:3000/api/dashboard/4/params/f825a080/values) in the screenshots), the provided values are in an Array of ids/numbers while it seems to be an Array of values (as string) when used in a simpler question.

__Simple question API call__

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/348552/163581559-f9e1cbd4-f8e6-4ed3-8d08-3b1b9a660b42.png">

__API call for remapped values__

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/348552/163580795-85e04347-9753-4b49-8cb6-4dd76eb58b41.png">

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/348552/163580841-f6c11c96-da87-47de-9802-d7fc720f7040.png">

**Comment by willbryant** [comment]
I think this just got worse in the last release? Now seeing the ID values instead of the remapped values in the new filter modal too.

**Comment by flamber** [comment]
@willbryant Sounds like you're seeing #24626

**Comment by willbryant** [comment]
@flamber Very similar, but unfortunately this one hasn't been fixed by https://github.com/metabase/metabase/pull/24685

I suspect it's a slightly different bit of code as that ticket/PR was for custom mappings, and this one is for foreign key mappings?

**Comment by flamber** [comment]
@willbryant This issue is a backend problem, and has a workaround. #24626 was a frontend specific problem.

**Comment by willbryant** [comment]
@flamber OK, I agree. So I think my original comment stands, this problem is now worse, because it now affects the new Filter modal, whereas the previous Filter sidebar was immune.

**Comment by flamber** [comment]
@willbryant This issue has nothing to do with #24626. #24626 has been fixed and will be part of 0.44.1 as noted in the sidebar of the issue (Milestone).

**Comment by willbryant** [comment]
I fully agree @flamber. It was your suggestion that I was seeing #24626, not mine?

It is not relevant, as you say, and I confirmed this by pulling in the fix and finding that this problem still occurs.

I am seeing this issue, and this issue now affects the Filter modal too.

**Comment by flamber** [comment]
@willbryant Please open a new issue if you are seeing a different problem.

**Comment by willbryant** [comment]
Cool, will do. But, the description of this ticket is no longer correct, as it does now affect filtering, not just the dashboard.

**Comment by WiNloSt** [comment]
The reason why the dashboard field isn't populating field values is that when we view the parameter in the native query editor, the field that's passed to the parameter widget is the FK. Given Field Filter of *Orders.Product_ID*, *Orders.Product_ID* is passed to the parameter. But when we map an ID parameter on a dashboard to this question, we would get *Products.ID* passed to the parameter instead.

This is one part of the code that determines whether or not the `ParameterFieldWidget` will show a list of values when clicking on the parameter, and it's the determining factor in this case.
https://github.com/metabase/metabase/blob/1d2e85ddee5c9e32f430f5bbacaf319b6f00cbc2/frontend/src/metabase-lib/parameters/utils/parameter-source.ts#L88

The parameter values will be shown correctly when we click the parameter on the native editor if we set *Orders.Product_ID*'s `has_field_values` to `list`, but it won't work on the dashboard because we get a different field (*Products.ID*) and its `has_field_values` is `none` by default.

**Comment by WiNloSt** [comment]
I found a possible cause introduced by this PR https://github.com/metabase/metabase/pull/18223/files#diff-82a7f4faef021837026f98a1fb4ca767a167bc0a756e50eebc0a046e463567edR384

https://github.com/metabase/metabase/blob/7c4b372e9709a08de5146f65bbafa0ca38c4729a/frontend/src/metabase/meta/Dashboard.js#L384

I'm not sure what that line is supposed to do, but removing that line doesn't fail the test from that PR. As I've checked out [6600f4c](https://github.com/metabase/metabase/commit/6600f4c596e207978c6f53ad62fd14575eb8c395) and played around with the code from that snapshot.

If we can remove that line, it would also fix the FE bug here.

The problem exists even in 46, unlike what I've mentioned in the previous comment.

#### on `master` @ 1d2e85ddee5c9e32f430f5bbacaf319b6f00cbc2
1. If you follow the repro, you won't get the field values on step 4)

#### on 46.7
1. If you follow the repro, you will get the field values, if not try refreshing the dashboard.
2. This seems fine unless you go to Admin > Data Model and then back to the same dashboard, now the values won't be shown on the same parameter anymore.

This is because an API we call on Data Model page (now Table Metadata) return fields with hydrated `target`, unlike `api/field/:field-id` which we call on the dashboard page, which will return the field without `target` property.

And the code that I mentioned above makes it so that we resolve fields that have `target` resulting in us passing the resolved field, the *Products.ID* in this case rather than *Orders.Product_ID* to the parameter.

I believe the solution is to remove that code that resolves the field `target` as I've said at least it didn't break the tests introduced in [that PR](https://github.com/metabase/metabase/pull/18223) that induced that line of code.

**Comment by WiNloSt** [comment]
The above assumption (removing `.map(field => field.target ?? field)`) breaks the test `should work for the foreign key` in `e2e/test/scenarios/dashboard-filters/dashboard-filters-id.cy.spec.js`

**Comment by qnkhuat** [comment]
fixed by https://github.com/metabase/metabase/pull/33632

**Comment by paoliniluis** [comment]
Reopening as it won't work if you use a GUI questionn

**Comment by qnkhuat** [comment]
This seems like a FE issue to me, when I click on the parameter widget, there are no FE calls to get field values.

I did some debugging, and I think the problem is that the field of the parameter is not "ORDERS.PRODUCT_ID," but it's followed by "PRODUCTS.ID," it's handled [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/utils/dashboards.ts#L196-L198C5. I)

I think it's a subtle feature on its own, but maybe we need to add a special case to: not follow FK if the field has a remapped value.

**Comment by ranquild** [comment]
@qnkhuat is right that we deliberately follow FKs when remapping field values. We can't remove it simply because the feature works only when all parameter targets map to a single DB field. If that's not the case, e.g. when there is a PK field and a FK field targeting the PK field and we don't follow FKs, then no remapping would be shown at all.
