### ISSUE TITLE
CumulativeSum in custom expression fails with integer argument

### ISSUE THREAD

**Issue by danaivehr** [metabase/metabase#27807]
**Describe the bug**
When I use CumulativeSum in a custom expression, passing a number as an argument, I get an error.

For example:
![image](https://user-images.githubusercontent.com/1226019/213800005-a9360d2f-a886-44c5-97d3-1283d9d67345.png)

`Failed to fetch Field 1: Field does not exist, or belongs to a different Database.`

Metabase interprets it as a column name, not a number.

**To Reproduce**
1. Create any question to any tabel or model
2. Add aggregation custom expression field = CumulativeSum(1) with grouping by any column
3. Run the question

**Expected behavior**
In example above it should just see cumulative count by grouped column

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Chrome 109.0.5414.74)
- Your operating system: (Windows 10)
- Your databases: (Postgres)
- Metabase version: (0.45.2)
- Metabase hosting environment: (Docker on Ubuntu)
- Metabase internal database: (Postgres)

**Severity**
Happens every time.
I tried to make a cumulative count of some other conditional expression, but came to the result that even 1 as an argument produces the same error.

**Comment by ranquild** [comment]
Turned out to be an MBQL lib bug with `expressionClauseForLegacyExpression`. For some reason the function translates `["avg", 2]` into `["avg", ["field", 2, null]]`. 
<img width="1466" alt="Screenshot 2024-06-25 at 12 34 03" src="https://github.com/metabase/metabase/assets/8542534/471fb394-c3aa-4190-96f0-92480d0f68ca">

**Comment by mngr** [comment]
It might be already fixed in 0.50, needs to be checked

**Comment by appleby** [comment]
Still present in master, though the error message has changed slightly

> Cannot determine the source table or query for Field clause [:field 1 nil]

**Comment by ranquild** [comment]
We don't use the legacy MBQL here anymore; perhaps this is fixed now

**Comment by appleby** [comment]
Still present in master at 7d306e5884d. The onBlur bug reported above is now gone and you can create the custom expression, but you still get an error when you run the query, presumably because we still roundtrip through legacy and `canonicalize-implicit-field-id` is still turning the literal value into a `[:field 1 nil]` clause.

**Comment by appleby** [comment]
stats repro: [https://stats.metabase.com/question/26714-repro-for-27807](https://stats.metabase.com/question/26714-repro-for-27807)

**Comment by ranquild** [comment]
Still not fixed. Repro - `CumulativeSum(1)`.

**Comment by ranquild** [comment]
`Lib.expressionClause` does not need to normalize legacy MBQL. It's up-to-date, always.
