### ISSUE TITLE
Fix e2e-tests-dashboard-ee

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#28491]
Reference: [Slack convo (internal)](https://metaboat.slack.com/archives/C5XHN8GLW/p1676997906308539)

This issue is specifically for fixing `frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js`

If you pause Cypress before it clicks the info button, just before this line:
https://github.com/metabase/metabase/blob/c82ccb1d47c74fd036e6871bbfbe87349ce7efdc/frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js#L72

you'll see that there's still 2 more API endpoints being responded

<img src='https://user-images.githubusercontent.com/1937582/220412747-0db2841a-0033-446a-ac82-8046b336aa33.png' width='500' />

This means it could be a race condition (I didn't take much time into troubleshooting this yet, but this is all based on my observation):
1. Cypress click the info button revealing the right sidebar
2. API responses received, updating the UI prompting React to rerender the UI, and now the right side bar is close.
3. Cypress don't see the right sidebar so the test failed.

**Comment by WiNloSt** [comment]
Fixed by https://github.com/metabase/metabase/pull/28505

**Comment by tsmacdonald** [comment]
@WiNloSt I'm seeing `actions-on-dashboards.cy.spec.js ` still fail, [example](https://github.com/metabase/metabase/actions/runs/4283343087/jobs/7459152748)

```
Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM.

`<button class="Button e2qhocv2 Button--primary Button--fullWidth css-meu1a emiw9oj2">...</button>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.findByRole()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element
```

**Comment by tsmacdonald** [comment]
here's the link: https://www.deploysentinel.com/ci/runs/63fcc23dc977b83868358b27

**Comment by WiNloSt** [comment]
@tsmacdonald Thank you for keeping a lookout. I updated the description to reflect the issue intent that this is about `frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js`, which seems to have been solved.

I think I've seen people [talking about flaking actions tests](https://metaboat.slack.com/archives/C5XHN8GLW/p1677242944041229). That might relate. Do you think it's better to keep this close and open another issue to tackle `actions-on-dashboards.cy.spec.js` instead? I'm worried this issue will turn into an epic issue where everyone talks about any failure in `e2e-tests-dashboard-ee` instead.

**Comment by tsmacdonald** [comment]
> Do you think it's better to keep this close and open another issue to tackle actions-on-dashboards.cy.spec.js instead? I'm worried this issue will turn into an epic issue where everyone talks about any failure in e2e-tests-dashboard-ee instead.

Yeah, that makes total sense to me
