### ISSUE TITLE
JS Error adding a time filter

### ISSUE THREAD

**Issue by urjitbhatia** [metabase/metabase#2980]
*  I am using the Chrome browser.
*  My computer's OS is OSX 10.11.5.
*  I'm running Metabase on AWS EBS
*  My database is Redshift.
*  My Metabase version is v0.17.1.

I am trying to create a new question and add a filter with a "time" type field. I selected "Today" and then add resulting on the filter not being added and this error showing up in the console:

```
Uncaught TypeError: Cannot read property 'toLowerCase' of null
capitalize	@	inflection.js:846
l	@	query_time.js:88
s	@	query_time.js:118
(anonymous function)	@	query_time.js:70
u	@	query_time.js:70
value	@	FilterWidget.jsx:63
value	@	FilterWidget.jsx:141
```

**Comment by tlrobinson** [comment]
Duplicate of #2617

**Comment by camsaul** [comment]
@urjitbhatia this has been fixed in Metabase 0.18; [upgrade to a newer version of Metabase](http://www.metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase) and you won't see this bug anymore 👍

**Comment by urjitbhatia** [comment]
@tlrobinson cool, thanks! I tried to upgrade but I realized that the ELB .zip package for 0.18 is still not out yet? Can you please link to that?

**Comment by tlrobinson** [comment]
@urjitbhatia Where are you seeing the zip missing from? It's here http://downloads.metabase.com/v0.18.1/metabase-aws-eb.zip (or downloads.metabase.com/v0.18.0/metabase-aws-eb.zip for v0.18.0)

**Comment by urjitbhatia** [comment]
@tlrobinson http://www.metabase.com/docs/v0.18.1/operations-guide/running-metabase-on-elastic-beanstalk.html still points to the old version

```
Application Version
The application version describes the exact binary you wish to deploy to your Elastic Beanstalk application. Metabase provides a pre-built AWS Elastic Beanstalk application version which can be linked to directly. Simply enter the following url in the S3 URL textbox:

http://downloads.metabase.com/v0.17.1/metabase-aws-eb.zip
```

**Comment by mazameli** [comment]
Thanks, Urjit — we'll fix that link. Sorry for the confusion!
