### ISSUE TITLE
Creating/editing database connection with SSH tunnel fails silently, when SSH port is not filled out

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32234]
### Describe the bug

Checking https://github.com/metabase/metabase/issues/20756 I saw that the connection will fail when the SSH port is not filled out

### To Reproduce

Spin up a stack with a bastion and an RDS server:
https://github.com/paoliniluis/bastion-rds

Connect to the DB and just create a table and some rows

Connect Metabase to it without filling the SSH port

### Expected behavior

If port is not filled, it should use port 22 as default

### Logs

java.lang.NullPointerException
	at clojure.lang.RT.intCast(RT.java:1221)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:53)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:53)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:94)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:88)
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:134)
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:130)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:293)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:289)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:318)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:314)
	at metabase.driver.sql_jdbc$fn__121460.invokeStatic(sql_jdbc.clj:52)
	at metabase.driver.sql_jdbc$fn__121460.invoke(sql_jdbc.clj:50)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__48184.invoke(util.clj:144)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Information about your Metabase installation

```JSON
v47-RC2
```

### Severity

P3

**Comment by asennoussi** [comment]
I'm happy I found this issue. I fixed my issue

**Comment by zbodi74** [comment]
This error is still present as of v1.47.7 . Can we please make sure the fix makes it into the next release?

**Comment by darksciencebase** [comment]
@zbodi74 you mean you'd like it to be backported to 47?

**Comment by zbodi74** [comment]
Yes please, if we are going to have another minor 47 release before 48.

**Comment by lbrdnk** [comment]
Backport PR #36200 that fixes the issue was tested and merged into 47 branch.
