### ISSUE TITLE
"Before" filter implies the selected date is inclusive, but it's exclusive

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#33494]
There's an inconsistency between the date picker UI and the query behaviour in "Before" date range filters. We should consider changing the date picker UI to show that the date range doesn't include the selected date. Note this doesn't apply to datetime ranges with a time component.

For example: A “Before 08/10/2023” filter has 08/10/2023 highlighted in dark blue, as if it were included in the range. But it’s not. It’s excluded. Here's how it looks in the UI:

![image](https://github.com/metabase/metabase/assets/39073188/5f0e404a-028c-4ffb-b93f-ffe58eb8f58e)

But for a SQL DB this would be compiled to something like:

`cast(<column> as date) < date '2023-08-10'`

which doesn't include the selected date.

[Slack context behind decision](https://metaboat.slack.com/archives/C01LQQ2UW03/p1692964455742739?thread_ts=1692607179.959739&cid=C01LQQ2UW03)

**Comment by romeovs** [comment]
I think this has been fixed.

The current `Before` no longer looks ambiguous as of 0483818e6a5d9ff0c37a637661f90901980d9a5d:

<img width="356" alt="Screenshot 2024-03-06 at 13 25 11" src="https://github.com/metabase/metabase/assets/1250185/b859e26d-b33b-4d70-997a-30aac957308a">


and the resulting SQL correctly selects: ` col < '2024-03-06 00:00:00.000+01:00'` correctly.

**Comment by kamilmielnik** [comment]
I can still reproduce it in `master` at 638d79c457 ([screenshot](https://github.com/metabase/metabase/assets/6830683/a7c4ca70-e881-43f1-8628-c4ee075e8b65))

**Comment by ranquild** [comment]
This was fixed when we migrated all data pickers to the one from the QB
