### ISSUE TITLE
Incorrect legends for graphs

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#3642]
This is on our stats instance, and I'm not seeing an JS errors.

This graph is an aggregation grouped by month, with a `this year` relative filter on it. It's incorrectly labeling the October numbers as September, and it's showing December of 2015 even though it shouldn't because of the filter:
![screen_shot_2016-10-21_at_9_33_16_am](https://cloud.githubusercontent.com/assets/2223916/19606124/09b32a24-9775-11e6-90fe-fc340262be8f.png)

The tooltip shows the correct month:
![screen_shot_2016-10-21_at_10_00_46_am](https://cloud.githubusercontent.com/assets/2223916/19606154/4c89a6e8-9775-11e6-8ef9-7562ce580c02.png)

Removing the relative filter seems to fix the problem for the legend, though notice that it's still showing an empty trailing month and an empty leading month:
![screen_shot_2016-10-21_at_10_01_40_am](https://cloud.githubusercontent.com/assets/2223916/19606176/7139e3a4-9775-11e6-815b-7611b9c34673.png)

This seems to be happening for other granularities as well, such as `This Month` grouped by day:
![screen_shot_2016-10-21_at_10_04_19_am](https://cloud.githubusercontent.com/assets/2223916/19606243/e4564aa8-9775-11e6-93b4-6ebc2a0d98c2.png)

The common denominator for the _incorrect_ legends appears to be the use of a relative filter, but the extra preceding and succeeding "buckets" seem to always be appearing. The visualization type doesn't seem to matter, provided the x-axis is time (bar, line, area).

**Comment by tlrobinson** [comment]
Looks like it's happening on dates during daylights savings. Also it's not limited to relative date filters, but a specific number of data points (happens with 12 bars but not 13, in the case of month)

**Comment by tlrobinson** [comment]
Ok, this is a weird one.

Backend returns the following:

```
["2016-01-01T00:00:00.000-08:00", 1],
["2016-02-01T00:00:00.000-08:00", 1],
["2016-03-01T00:00:00.000-08:00", 1],
["2016-04-01T00:00:00.000-07:00", 1],
["2016-05-01T00:00:00.000-07:00", 1],
["2016-06-01T00:00:00.000-07:00", 1],
["2016-07-01T00:00:00.000-07:00", 1],
["2016-08-01T00:00:00.000-07:00", 1],
["2016-09-01T00:00:00.000-07:00", 1],
["2016-10-01T00:00:00.000-07:00", 1],
["2016-11-01T00:00:00.000-07:00", 1],
["2016-12-01T00:00:00.000-08:00", 1]
```

As you can see it's returning the start of the month at 00:00 in the UTC offset at that moment in time, which changes depending on the whether it's daylights savings or not. I guess this is the correct behavior?

When dc.js formats axis ticks it uses the browser's timezone, but we want to match the timezone of the data, so we have a little hack that takes the UTC offset of the first data point and sets the moment.js `utcOffset` to that. Unfortunately it wasn't a safe assumption that the offset of the first point should be the same for all of them.

```
function applyChartTimeseriesXAxis(chart, settings, series, xValues, xDomain, xInterval) {
    // get the data's timezone offset from the first row
    let dataOffset = parseTimestamp(series[0].data.rows[0][0]).utcOffset() / 60;

    // ...
        chart.xAxis().tickFormat(timestamp => {
            // timestamp is a plain Date object which discards the timezone,
            // so add it back in so it's formatted correctly
            const timestampFixed = moment(timestamp).utcOffset(dataOffset).format();
            return formatValue(timestampFixed, { column: dimensionColumn })
        });
```

So, this bug happens when the *first* data point is *not* during daylights savings. Dates during daylights savings lose an hour, which shifts them to the previous month/week/day. (if the first data point is during daylights savings, then dates not in daylights savings get shifted, but in the other direction, so they're formatted correctly).

I hate time.

**Comment by tlrobinson** [comment]
Tests for this:

```
    it("should display months correctly with queries that start during daylights savings", function() {
        renderTimeseriesLine({
            rows: [
                ["2015-10-01T00:00:00.000-07:00", 1],
                ["2015-11-01T00:00:00.000-07:00", 1],
                ["2015-12-01T00:00:00.000-08:00", 1],
                ["2016-01-01T00:00:00.000-08:00", 1],
            ],
            unit: "month",
        });
        expect(qsa("svg .axis.x .tick text").map(e => e.textContent)).toEqual([
            "September 2015", // FIXME: 1 month padding
            "October 2015",
            "November 2015",
            "December 2015",
            "January 2016",
            "February 2016", // FIXME: 1 month padding
        ]);
    });

    it("should display months correctly with queries that start not during daylights savings", function() {
        renderTimeseriesLine({
            rows: [
                ["2016-02-01T00:00:00.000-08:00", 1],
                ["2016-03-01T00:00:00.000-08:00", 1],
                ["2016-04-01T00:00:00.000-07:00", 1],
                ["2016-05-01T00:00:00.000-07:00", 1],
            ],
            unit: "month"
        });
        expect(qsa("svg .axis.x .tick text").map(e => e.textContent)).toEqual([
            "January 2016", // FIXME: 1 month padding
            "February 2016",
            "March 2016",
            "April 2016",
            "May 2016",
            "June 2016", // FIXME: 1 month padding
        ]);
    });
```

**Comment by mazameli** [comment]
This bug still seems to be present on our stats instance, at least for 2016. One thing I didn't notice before, but is present in the original screenshot I posted, is that the x-axis labels are showing March twice. Is this because last year was a leap year?

<img width="1138" alt="screen shot 2017-02-07 at 11 29 09 am" src="https://cloud.githubusercontent.com/assets/2223916/22707842/f8a20a3e-ed28-11e6-8984-782e8f07ed94.png">

**Comment by huksley** [comment]
I am experiencing same issue but with dates. I have bars for every day but bar is displayed with incorrect label (but with correct tooltip)

![image](https://cloud.githubusercontent.com/assets/1594349/23338550/28788ae4-fc1f-11e6-8888-b6e29665920a.png)

**Comment by darylteo** [comment]
Hi guys just wanted to try and help out as I'm also experiencing issue and I don't want to add more noise.

---

This is not data related. Doesn't make sense why it would work for tooltip and not for labels. 

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L134

> timestamp is a plain Date object which discards the 
> so add it back in so it's formatted correctly

The issue is most likely with how the Date objects are contructed, as they are being constructed in browser timezones, even when the original dates themselves are UTC. I cannot find the code that does this at this time, but can easily reproduce problem now with simple system level adjustments.

As an example, setting my computer timezone to UTC with Chrome console:

```js
> new Date('2017-04-01 00:00:00')
> Sat Apr 01 2017 00:00:00 GMT+0000 (UTC)
````

However, if your browser is in a non UTC timezone, 

```js
> new Date('2017-04-01 00:00:00')
> Sat Apr 01 2017 00:00:00 GMT+1100 (AEDT)
````
Attached reproduction of issue.

<img width="1156" alt="non-utc" src="https://cloud.githubusercontent.com/assets/1226920/25657075/5cd974fc-303f-11e7-863c-02d812dca62b.png">
<img width="1120" alt="utc" src="https://cloud.githubusercontent.com/assets/1226920/25657074/5cd8b5b2-303f-11e7-99a3-0bcbe47606a5.png">

**Comment by mazameli** [comment]
Some additional context:

If my filter is `previous sixth months` (i.e., not including the current month), the axis and tooltip look like this, and the **axis is correct** but the **tooltip is wrong:**

![screen shot 2017-05-25 at 11 09 10 am](https://cloud.githubusercontent.com/assets/2223916/26464150/96a4a834-413b-11e7-890e-b71881f15d99.png)

If I do `previous 180 days`, my graph looks like this, and again the _axis_ is correct, and the tooltip is wrong. This is the opposite of what I originally reported.

![screen shot 2017-05-25 at 11 12 39 am](https://cloud.githubusercontent.com/assets/2223916/26464188/c50bc82e-413b-11e7-9f6e-efcb485c2ab3.png)

**Comment by ebalgava** [comment]
Any progress? Same issue here: 
![itms_zop_po_mesiacoch_z_posledneho_datumu_v_aktualnom_stave](https://user-images.githubusercontent.com/29505976/28461928-2c064892-6e19-11e7-965d-91819fa7a873.png)

**Comment by salsakran** [comment]
this should be fixed in 0.26, which was just released. Can you check to see if upgrading fixes this issue @ebalgava @huksley @darylteo ?

**Comment by ebalgava** [comment]
My issue still persists within v0.26.1: 
https://bi.ekosystem.slovensko.digital/public/dashboard/86ce303c-05bf-4947-bb39-d2a958208492

**Comment by adrienguyon** [comment]
Hi all, I am not sure this issue was fixed as I am experimenting the same problem (I am on version v0.28.1).
@salsakran was it solved for you? 
Thanks.
![image](https://user-images.githubusercontent.com/36507501/36260215-f86fbc4c-1260-11e8-9504-de84dd6e7923.png)

**Comment by delx** [comment]
I also experience this problem on v0.28.1.

**Comment by Poggen** [comment]
We're still experiencing this issue on 29.3. Are you still experiencing the issue, @adrienguyon & @delx?
![image](https://user-images.githubusercontent.com/5216834/41598768-80e4104c-73d1-11e8-9927-b8e754c47a4e.png)

**Comment by adrienguyon** [comment]
Yes unfortunately @Poggen

**Comment by SetSails** [comment]
same here. upgraded to 0.29.3 and still the same problem we've been facing for over a year.

**Comment by ebalgava** [comment]
I saw last progress within this issue here: https://github.com/metabase/metabase/issues/5246#issuecomment-379423115

There are also mentioned some workarounds and link to timezone troubleshooting.
