### ISSUE TITLE
Sign "personal-collection does not match schema" when it's user deactivating.

### ISSUE THREAD

**Issue by Rschewsky** [metabase/metabase#36731]
**Describe the bug**
Sign "Output of user->personal-collection does not match schema: [0;33m (not ("instance of a Collection" nil)) [0m" shows by deactivating user's account

**Logs**
api.js:218 
        
        
       GET https://metabase.tetrika-school.ru/api/user?include_deactivated=true 500 (Internal Server Error)
(anonymous) @ api.js:218
value @ api.js:176
value @ api.js:171
(anonymous) @ api.js:143
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
p @ analytics.js:150
a @ analytics.js:150
(anonymous) @ analytics.js:150
(anonymous) @ analytics.js:150
(anonymous) @ api.js:32
(anonymous) @ api.js:119
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
p @ analytics.js:150
a @ analytics.js:150
(anonymous) @ analytics.js:150
(anonymous) @ analytics.js:150
(anonymous) @ api.js:60
(anonymous) @ entities.js:315
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
j @ engine.js:115
a @ engine.js:115
(anonymous) @ engine.js:115
(anonymous) @ engine.js:115
(anonymous) @ entities.js:314
(anonymous) @ utils.js:233
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
m @ promise.ts:61
a @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ utils.js:225
(anonymous) @ utils.js:310
(anonymous) @ utils.js:198
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
m @ promise.ts:61
a @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ utils.js:196
(anonymous) @ index.js:16
(anonymous) @ redux.js:578
(anonymous) @ EntityListLoader.jsx:111
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
C @ PaginationState.jsx:8
a @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:106
value @ EntityListLoader.jsx:130
hs @ react-dom.production.min.js:212
kc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:248
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
Show 33 more frames
Show less
utils.js:242 Request entities,users_list,{"include_deactivated":true},fetch failed: {status: 500, data: {…}, isCancelled: false}
(anonymous) @ utils.js:242
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
m @ promise.ts:61
l @ promise.ts:61
Promise.then (async)
m @ promise.ts:61
a @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ utils.js:225
(anonymous) @ utils.js:310
(anonymous) @ utils.js:198
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
m @ promise.ts:61
a @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ promise.ts:61
(anonymous) @ utils.js:196
(anonymous) @ index.js:16
(anonymous) @ redux.js:578
(anonymous) @ EntityListLoader.jsx:111
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
C @ PaginationState.jsx:8
a @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:106
value @ EntityListLoader.jsx:130
hs @ react-dom.production.min.js:212
kc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:248
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
Show 24 more frames
Show less
PaginationState.jsx:8 Uncaught (in promise) {status: 500, data: {…}, isCancelled: false}data: cause: "Output of user->personal-collection does not match schema: \n\n\t \u001b[0;33m  (not (\"instance of a Collection\" nil)) \u001b[0m \n\n"data: {type: 'schema.core/error', schema: {…}, value: null, error: 'schema.utils.ValidationError@108af596', toucan2/context-trace: Array(2)}error: "schema.utils.ValidationError@108af596"message: "Output of user->personal-collection does not match schema: \n\n\t \u001b[0;33m  (not (\"instance of a Collection\" nil)) \u001b[0m \n\n"trace: (305) [Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), Array(4), …]value: nullvia: [{…}][[Prototype]]: ObjectisCancelled: falsestatus: 500[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
C @ PaginationState.jsx:8
l @ EntityListLoader.jsx:107
Promise.then (async)
C @ PaginationState.jsx:8
a @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:107
(anonymous) @ EntityListLoader.jsx:106
value @ EntityListLoader.jsx:130
hs @ react-dom.production.min.js:212
kc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:248
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
Show 13 more frames
Show less

**To Reproduce**
1. Go to page https://metabase.tetrika-school.ru/admin/people
2. Find user "s r"
3. Try to deactivate user

**Expected behavior**
User must be deactivated correctly

**Screenshots**
![image](https://github.com/metabase/metabase/assets/44786854/4dc1fa2d-cb6a-44e0-84d1-485639fbbd72)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.0-58-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.16 (Debian 12.16-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v0.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by paoliniluis** [comment]
Please upgrade to the latest version. I think we fixed this already in v48

**Comment by Rschewsky** [comment]
We have upgraded our Metabase to the last possible version (v0.47.10) but the bug is still remaining.

**Comment by paoliniluis** [comment]
Please upgrade to v48

**Comment by Rschewsky** [comment]
Unfortunately, it's impossible. 0.47.10 is the latest version.
![image](https://github.com/metabase/metabase/assets/44786854/6683df6e-ea7f-4b5d-bfa0-7e4782002ea0)

**Comment by darksciencebase** [comment]
Yes, this is what currently is displayed in the application. But 48 is already available at https://github.com/metabase/metabase/releases

**Comment by ksj20** [comment]
I faced this issue when inviting a new user with `Default` credentials. I got the same log showing
`Output of user->personal-collection does not match schema: �[0;33m (not ("instance of a Collection" nil))`

Anyone facing the same issue and cannot afford to upgrade to version 48 
a workaround would be to add/edit appropriate row in the `collection` table with the the following columns filled: `name`, `description`, `archived`, `location`, `slug`, and very importantly `personal_owner_id`!!  - you can find the `personal_owner_id` from the `core_user`'s `id` column.

btw, from what I have tested the `entity_id` column was not necessary, I kept it as null when inserting the new row(s)
