### ISSUE TITLE
Clicking on entity qualified id on the content model takes nowhere and spins forever

### ISSUE THREAD

**Issue by dragonsahead** [metabase/metabase#38747]
### Describe the bug

1) go to the content model of the metabase analytics section
2) click on any entity qualified id
3) see the modal spinning forever
![image](https://github.com/metabase/metabase/assets/1711649/c2fcf745-6362-426c-abea-dccdd51849ae)

### To Reproduce

above

### Expected behavior

It should load the entity

### Logs

NA

### Information about your Metabase installation

```JSON
v47.x+ for sure
```

### Severity

P2

**Comment by luizarakaki** [comment]
Fixed in the audit dev instance. The issue was that entity_qualified_id was marked as entity key.
Although this looks a models bug, it shouldn't crash like that

**Comment by kamilmielnik** [comment]
`Lib.availableDrillThrus` incorrectly returns `zoom` drill (with incorrect `many-pks?: false`) when there are mutliple PKs and one of them is a string. [It should return drill-thru.pk instead](https://github.com/metabase/metabase/blob/a6039a0fcbb515f417bd6f9053e5af3708a856b2/src/metabase/lib/drill_thru/zoom.cljc#L61).

Relabeling to QP.

Ways to reproduce:
- Click any value in 2nd column in https://stats.metabase.com/model/14230
- New Model > Products > Edit Metadata > Change semantic type of Vendor to "Entity Key" > Save. Click any value in Vendor column.
- New SQL Question > `select 'a' as "a", 'b' as "b";` > Save. Create a model based on this question > Metadata > Set semantic type of both columns as "Entity Key" > Save. Click any value in table.

**Comment by ranquild** [comment]
This is fixed now. We can use the `Content` model for repro. E.g. a composite PK.

**Comment by romeovs** [comment]
@ranquild I can still reproduce the bug on `master` at `2ae676e86dc74954310b6a383f757ab7bd1150b0` following these steps:

- New Model > Products 
- Edit Metadata
- Change semantic type of Vendor to "Entity Key" 
- Save 
- Visualize
- Click any value in Vendor column

<img width="1474" height="906" alt="Image" src="https://github.com/user-attachments/assets/d7b48f27-53e7-4aa3-88b8-e4556ebe7bca" />

A refresh of the pages seems to resolve the issue however.

The PR that was supposed to fix this was closed, not merged: https://github.com/metabase/metabase/pull/57136

**Comment by ranquild** [comment]
Cannot be reproduced in v57/master

**Comment by ranquild** [comment]
Changed to .Frontend just to add a E2E repro for what @romeo reproduced before
