### ISSUE TITLE
The app keeps going back to the home page whenever I try to load the dashboard

### ISSUE THREAD

**Issue by bourgois** [metabase/metabase#3950]
------
Cf:
http://discourse.metabase.com/t/the-app-keeps-going-back-to-the-home-page-whenever-i-try-to-load-the-dashboard/875
-----

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following:

- Your browser and the version: Chrome  54.0.2840.98, Firefox 49.0.2, Safari 10.0.1
- Your operating system: OS X 10.12.1
- Your databases: MySQL on aws
- Metabase version: 0.21.0
- Metabase hosting environment: Mac app
- Metabase internal database: MySQL

- I click on my dashboard from Activity or "Recently viewed" or via the dashboard menu
- The dashboard start loading and I see spinner for a short time, then I get a full white page with the Metabase logo as a spinner.
- After a while, I get back to the homepage
- If I click on the back arrow on the top left, I can usually get back to the dashboard. Sometime I need to do this more than once. Sometime some charts have 'there was a prbl displaying that chart' or icons of a exclamation mark. I can restart the whole process until things are good.

**Comment by camsaul** [comment]
@bourgois are any of the queries on this dashboard particularly slow?

**Comment by bourgois** [comment]
I don't think so. It takes a couple of seconds to update the full dashboard.

**Comment by tlrobinson** [comment]
@bourgois Could you try opening the app, copying the URL (in the Edit menu, I think?) and opening it in Safari? See if it loads correctly, and if there are any errors in the Javscript console. Thanks.

**Comment by bourgois** [comment]
Thanks for the tip: no issue in Safari, it stays on the page.
I will use Safari instead of the app for now :)

**Comment by doodlebro** [comment]
This solution works for me as well (using chrome instead of safari though). Thanks for the tip @tlrobinson.

**Comment by bourgois** [comment]
@doodlebro so you have the same issue in the app?
Using Chrome, Safari or Firefox, it works as long as I am using the browser and not the app...

**Comment by camsaul** [comment]
I might be able to fix this by making the timeout a little less agro or moving some of the rendering to a background thread

I will look into this 😎

**Comment by doodlebro** [comment]
@bourgois: Yep, same issue in app, even on the current version (0.23.1.0)

Browser is a fine solution; my colleagues will be accessing through a browser anyways.

**Comment by camsaul** [comment]
@doodlebro are you running the Mac App and having other people access through a browser? You should really set up a dedicated instance if multiple people are using it

**Comment by doodlebro** [comment]
No, I'm just testing for now :)

**Comment by camsaul** [comment]
@bourgois this should be fixed by #4750, which we're shipping as part of our next release in a few weeks or so. If you continue to see this issue after upgrading to the new release please feel free to reöpen this issue or open a new one.

**Comment by bourgois** [comment]
Hi @camsaul 
I didn't realize it was closed. But I still have the issue... I am now on 0.25.2.0 on my Mac and continue to use Chrome rather than the app because of this...
