### ISSUE TITLE
Multiple aggregations of the same type are missing correct `cols` metadata

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4003]
Similar to #4002, but when two aggregations of the same type are specified, only the first has the correct `cols` metadata, in particular `base_type`, `special_type`, and `source` are incorrect.

Example query:

```json
{
  "source_table": 1,
  "aggregation": [["count"], ["count"]],
  "breakout": [["datetime_field", ["field-id", 1], "as", "day"]]
}
```

Expected `data.cols[1]` and `data.cols[2]`:

```json
{
  "description":null,
  "table_id":null,
  "special_type":"type/Number",
  "name":"count",
  "source":"aggregation",
  "extra_info":{},
  "id":null,
  "target":null,
  "display_name":"count",
  "base_type":"type/Integer"
},
{
  "description":null,
  "table_id":null,
  "special_type":"type/Number",
  "name":"count_2",
  "source":"aggregation",
  "extra_info":{},
  "id":null,
  "target":null,
  "display_name":"count_2",
  "base_type":"type/Integer"
}
```

Actual `data.cols[1]` and `data.cols[2]`:

```json
{
  "description":null,
  "table_id":null,
  "special_type":"type/Number",
  "name":"count",
  "source":"aggregation",
  "extra_info":{},
  "id":null,
  "target":null,
  "display_name":"count",
  "base_type":"type/Integer"
},
{
  "description":null,
  "table_id":null,
  special_type:null,
  "name":"count_2",
  "extra_info":{},
  "id":null,
  "target":null,
  "preview_display":true,
  "display_name":"count_2",
  base_type:"type/*"
  source: 
}
```

**Comment by VikramTiwari** [comment]
![screen shot 2016-12-27 at 09 56 01](https://cloud.githubusercontent.com/assets/1330677/21505292/bbc268d6-cc1a-11e6-8bcc-a72a6ba68113.png)

@tlrobinson Is this being caused by the same reason?
To reproduce:
- Create a question with custom expressions
- Give a name to your expression
- Run the query (gives first two sets of errors)
- Try saving the question (gives the last error)
I am on the latest master branch.

**Comment by camsaul** [comment]
So this is actually the same issue as #1786, which has been open for almost a year. Are we sure this is a Priority/P1 issue?

**Comment by camsaul** [comment]
I don't think this will be super simple to fix, otherwise I would have done it already. I think it would require reworking a lot of pieces in the query processor to get it working right so not sure if it makes sense to try to tackle this now since it's not a regression.

**Comment by camsaul** [comment]
I think could potentially do a hacky fix for this actually

**Comment by salsakran** [comment]
For context, this makes multiple aggregations pretty hokey, so it's P1. When we didn't have multiple aggregations it wasn't that big a deal.

**Comment by camsaul** [comment]
Fixed by #4070

**Comment by VikramTiwari** [comment]
This is still not fixed for BigQuery based databases. I understand that `expression-aggregations` part is still commented in the driver file, just wanna gauge when do you guys plan on supporting it for BigQuery driver as well?

**Comment by camsaul** [comment]
Hi @VikramTiwari, we have an open issue for supporting `expression-aggregations` for BigQuery, #3997 (opened by you!). Keep an eye on that issue, we should be adding support at some point in the near future.
