### ISSUE TITLE
Permissions tests intermittently failing

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#4054]
Looks like certain db calls return data in a different order e.x. https://circleci.com/gh/metabase/metabase/9493

```
failure in (permissions_test.clj:706) : metabase.permissions-test
(expect ["DB 1 Expensive Venues" "DB 2 Expensive Venues" "DB 2 Today's Users"] (metabase.permissions-test/with-test-data (GET-segment :crowberto)))
           
expected:
 ["DB 1 Expensive Venues" "DB 2 Expensive Venues" "DB 2 Today's Users"]
was:
 ["DB 2 Today's Users" "DB 1 Expensive Venues" "DB 2 Expensive Venues"]

in expected, not actual:
["DB 1 Expensive Venues" "DB 2 Expensive Venues" "DB 2 Today's Users"]
in actual, not expected:
["DB 2 Today's Users" "DB 1 Expensive Venues" "DB 2 Expensive Venues"]
```

and some others: https://circleci.com/gh/metabase/metabase/9501

```
failure in (permissions_collection_test.clj:32) : metabase.permissions-collection-test
(expect false (metabase.permissions-test/with-test-data (can-run-query? :rasta)))

           expected: false 
                was: true

failure in (permissions_collection_test.clj:37) : metabase.permissions-collection-test
(expect false (metabase.permissions-test/with-test-data (tu/with-temp Collection [collection] (set-card-collection! collection) (can-run-query? :rasta))))

           expected: false 
                was: true
```

**Comment by camsaul** [comment]
The first failure was fixed by #4073 but not sure how the second one happened

**Comment by tlrobinson** [comment]
Also happening for metrics_test (https://circleci.com/gh/metabase/metabase/9587)

```
failure in (metric_test.clj:48) : metabase.models.metric-test
(expect
 [true false]
 (tu/with-temp*
  [Database [{database-id :id}] Table [{table-id :id} {:db_id database-id}] Metric [{metric-id :id} {:table_id table-id, :definition {:database 45, :query {:filter ["yay"]}}}]]
  [(metric/exists? metric-id) (metric/exists? 34)]))

           
expected:
 [true false]
 
was:
 [true true]
```

**Comment by camsaul** [comment]
@tlrobinson I already fixed that it's merged into `release-0.22.0` already

**Comment by tlrobinson** [comment]
This is still happening fairly often https://circleci.com/gh/metabase/metabase/9725?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by tlrobinson** [comment]
FWIW I've only seen this happen on CI nodes 0 and 3, which both use H2 as the application database, while 1 and 2 use Postgres and MySQL.

**Comment by tlrobinson** [comment]
This is still happening pretty regularly (~50% of the time) and it's a bit of a drag :-/

**Comment by camsaul** [comment]
These have all been fixed, so going to go ahead and close this out. If we see more perms random test failures we can open a new issue
