### ISSUE TITLE
Primary Key missing filter options

### ISSUE THREAD

**Issue by abhishek-superk** [metabase/metabase#40665]
### Describe the bug

Primary keys can only be filtered for `Is` and `Is Not`.

Most importantly - joining with a different table and trying to filter rows that gave or didn't give a match, this can be done only via `Is Empty` or `Is not Empty` filter options. 
<img width="1282" alt="image" src="https://github.com/metabase/metabase/assets/73629665/607a92a0-af4f-4c0b-b6be-0266a9486608">

### To Reproduce

1. Go to any table with primary key defined
2. Click on the column name to filter.

### Expected behavior

All text/numeric filter options as usual should be available for the primary keys as well. 
In many cases, primary key contains partial information about the that can be used to filter the data, hence `Contains` and `Does Not Contain` are also useful. 

This used to work as expected in earlier versions, but is missing in version `0.49`

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7-post-Ubuntu-0ubuntu220.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7-post-Ubuntu-0ubuntu220.04.1",
    "os.name": "Linux",
    "os.version": "5.15.0-1052-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.3.39-MariaDB-0ubuntu0.20.04.2"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

P1, breaking joins and adding complications in using tables

**Comment by bshepherdson** [comment]
No repro.

Here's what it looks like on master and 49.1, clicking on a numeric FK:
![2024-03-27-101741_616x975_scrot](https://github.com/metabase/metabase/assets/157812/bf803fdf-fbf5-4409-b203-eb46cbaa11cb)

Where is that **Alias** field coming from? Perhaps from a model which does not define its type in the metadata, or from a SQL question? The column appears to be all blank, ie. `NULL` - if there's no values returned for a SQL column we don't know what type it is.

I don't think this is a UI regression, but rather a metadata issue.

**Comment by abhishek-superk** [comment]
That's weird, all our primary keys are giving only two options. 
<img width="492" alt="image" src="https://github.com/metabase/metabase/assets/73629665/256e5b47-def2-4bc1-b4d2-1d601510f514">
<img width="520" alt="image" src="https://github.com/metabase/metabase/assets/73629665/b2736ba8-9a82-4304-84a2-ae8b474ed8a5">
<img width="520" alt="image" src="https://github.com/metabase/metabase/assets/73629665/a72b550b-59ec-4dd8-9888-34a0b86e8745">

The table metadata doesn't seem to have any issue either, at least we didn't change anything after the update. 
<img width="888" alt="image" src="https://github.com/metabase/metabase/assets/73629665/80f4f140-940f-4e27-af1a-81f892d48598">

Is there anything else we should check?

**Comment by bshepherdson** [comment]
There's been some other oddities around filters, so there may be some more subtle bug here. (For example, it might be a BigQuery-specific issue.)

I'll investigate further and see if I can reproduce this.

**Comment by abhishek-superk** [comment]
@bshepherdson Thank you, much appreciated! 🙏 

One other thing that changed in filters: 
If you want to select 4 of the search results - previously you could just type once and select all 4, but now you gotta type again every time. Don't know where else to post this, couldn't think of what to write in a new issue.

**Comment by bshepherdson** [comment]
I'm back to looking at this issue after dealing with some other escalations.

I still can't reproduce this, even on BigQuery. @abhishek-superk can you still see this issue (on the latest 49.3 or 49.4 if it's practical to update)?

If you can, can you open the devtools Network tab, find the latest `/api/dataset` request (or `/api/card/$ID/query` for a saved question), and paste the `data.cols[0]` value showing one of these problem PKs? It should look something like this:
```json
{
  "description": null,
  "semantic_type": "type/PK",
  "table_id": 653,
  "coercion_strategy": null,
  "name": "id",
  "settings": null,
  "source": "fields",
  "fk_target_field_id": null,
  "field_ref": ["field", 1514, null],
  "effective_type": "type/Integer",
  "nfc_path": null,
  "parent_id": null,
  "id": 1514,
  "position": 0,
  "visibility_type": "normal",
  "display_name": "ID",
  "fingerprint": null,
  "base_type": "type/Integer"
}
```

**Comment by perivamsi** [comment]
@bshepherdson let's add the milestone after the fix is merged into master and is backported to 49. Otherwise we will keep pushing the milestones out.

**Comment by abhishek-superk** [comment]
Thanks @bshepherdson! Updated to 0.49.5 as it's the latest available now. Still getting only 2 options - `Is` and `Is Not` for PKs or FKs columns.

Here's the `data.cols[0]` values for a table:

```
{
                "description": null,
                "semantic_type": "type/PK",
                "table_id": 2297,
                "coercion_strategy": null,
                "name": "alias",
                "settings": null,
                "source": "fields",
                "fk_target_field_id": null,
                "field_ref": [
                    "field",
                    49329,
                    null
                ],
                "effective_type": "type/Text",
                "nfc_path": null,
                "parent_id": null,
                "id": 49329,
                "position": 0,
                "visibility_type": "normal",
                "display_name": "Alias",
                "fingerprint": {
                    "global": {
                        "distinct-count": 9653,
                        "nil%": 0.0
                    },
                    "type": {
                        "type/Text": {
                            "percent-json": 0.0,
                            "percent-url": 0.0,
                            "percent-email": 0.0,
                            "percent-state": 0.0,
                            "average-length": 14.251527389458424
                        }
                    }
                },
                "base_type": "type/Text"
            },


```


The index of PK in the saved report was 1, so sharing that instead of 0:
```
{
                "description": "SPA Product ID",
                "semantic_type": "type/FK",
                "table_id": 2253,
                "coercion_strategy": null,
                "name": "productId",
                "settings": null,
                "source": "fields",
                "fk_target_field_id": 91100,
                "field_ref": [
                    "field",
                    119963,
                    null
                ],
                "effective_type": "type/Text",
                "nfc_path": null,
                "parent_id": null,
                "id": 119963,
                "position": 2,
                "visibility_type": "normal",
                "display_name": "ProductId",
                "fingerprint": {
                    "global": {
                        "distinct-count": 5569,
                        "nil%": 0.0
                    },
                    "type": {
                        "type/Text": {
                            "percent-json": 0.0,
                            "percent-url": 0.0,
                            "percent-email": 0.0,
                            "percent-state": 0.0,
                            "average-length": 35.9948
                        }
                    }
                },
                "base_type": "type/Text"
            },
```

Also, here's the same info for FK in this report:
```
{
                "description": "Replenishment Alias",
                "semantic_type": "type/FK",
                "table_id": 2253,
                "coercion_strategy": null,
                "name": "alias",
                "settings": null,
                "source": "fields",
                "fk_target_field_id": 49329,
                "field_ref": [
                    "field",
                    48348,
                    null
                ],
                "effective_type": "type/Text",
                "nfc_path": null,
                "parent_id": null,
                "id": 48348,
                "position": 4,
                "visibility_type": "normal",
                "display_name": "Alias",
                "fingerprint": {
                    "global": {
                        "distinct-count": 8009,
                        "nil%": 0.0
                    },
                    "type": {
                        "type/Text": {
                            "percent-json": 0.0,
                            "percent-url": 0.0,
                            "percent-email": 0.0,
                            "percent-state": 0.0,
                            "average-length": 14.1712
                        }
                    }
                },
                "base_type": "type/Text"
            },
```


The PK of the table shared is being referred as a FK in the report shared next, in case it helps.

**Comment by bshepherdson** [comment]
Okay, string keys are the issue here. I can reproduce this with a test table using string keys.
![2024-04-15-162840_629x490_scrot](https://github.com/metabase/metabase/assets/157812/137df03f-9acd-41fa-b3a5-adba82d0c11f)

I'll work on a fix, should be straightforward.
