### ISSUE TITLE
After upgrading to 0.50, all non-admin users are facing error message : ERROR: syntax error at or near ")" 

### ISSUE THREAD

**Issue by tcourtainsellsy** [metabase/metabase#44043]
**Describe the bug**
After upgrading to v0.50, all non-admin users encounter an error when trying to access any question or dashboard.

**Logs**
[7a5de2fb-b7cb-451d-98e2-7f13c79679e6] 2024-06-12T09:21:35+02:00 ERROR metabase.server.middleware.log GET /api/dashboard/32/query_metadata 500 7,4 s (183 appels de DB) {:metabase-user-id 73} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "ERROR: syntax error at or near \")\"\n  Position: 50",
   :data
   {:toucan2/context-trace
    [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection"
      {:toucan2.jdbc.query/sql-args ["SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"]}]
     ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}]
     ["resolve connection" {:toucan2.connection/connectable :default}]
     ["resolve connection" {:toucan2.connection/connectable nil}]
     {:toucan2.pipeline/rf
      #object[clojure.core$map$fn__5931$fn__5932 0x3451c8a0 "clojure.core$map$fn__5931$fn__5932@3451c8a0"]}
     ["with compiled query"
      {:toucan2.pipeline/compiled-query ["SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"]}]
     ["with built query"
      {:toucan2.pipeline/built-query {:select [:*], :from [[:metabase_database]], :where [:in :id #{}]}}]
     ["with resolved query" {:toucan2.pipeline/resolved-query {}}]
     ["with parsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/select.instances,
       :toucan2.pipeline/parsed-args {:kv-args {:id [:in #{}]}, :queryable {}}}]
     ["with model" {:toucan2.pipeline/model :model/Database}]
     ["with unparsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/select.instances,
       :toucan2.pipeline/unparsed-args (:model/Database :id [:in #{}])}]]},
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]}
  {:type org.postgresql.util.PSQLException,
   :message "ERROR: syntax error at or near \")\"\n  Position: 50",
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]}],
 :trace
 [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2725]
  [org.postgresql.core.v3.QueryExecutorImpl processResults "QueryExecutorImpl.java" 2412]
  [org.postgresql.core.v3.QueryExecutorImpl execute "QueryExecutorImpl.java" 371]
  [org.postgresql.jdbc.PgStatement executeInternal "PgStatement.java" 502]
  [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 419]
  [org.postgresql.jdbc.PgPreparedStatement executeWithFlags "PgPreparedStatement.java" 194]
  [org.postgresql.jdbc.PgPreparedStatement execute "PgPreparedStatement.java" 180]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement execute "NewProxyPreparedStatement.java" 67]
  [toucan2.jdbc.query$reduce_jdbc_query invokeStatic "query.clj" 40]
  [toucan2.jdbc.query$reduce_jdbc_query invoke "query.clj" 22]
  [toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default
   invokeStatic
   "pipeline.clj"
   19]
  [toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default
   invoke
   "pipeline.clj"
   9]
  [clojure.lang.AFn applyToHelper "AFn.java" 178]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [methodical.impl.combo.threaded$fn__18070$fn__18071$fn__18078 invoke "threaded.clj" 79]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040$fn__18044 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 doInvoke "core.clj" 2589]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18050 doInvoke "threaded.clj" 46]
  [clojure.lang.RestFn applyTo "RestFn.java" 151]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 65]
  [methodical.impl.standard$invoke_multifn doInvoke "standard.clj" 47]
  [clojure.lang.RestFn invoke "RestFn.java" 594]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 199]
  [toucan2.pipeline$transduce_execute$with_connection_STAR___21303 invoke "pipeline.clj" 78]
  [toucan2.connection$bind_current_connectable_fn$fn__20980 invoke "connection.clj" 104]
  [toucan2.connection$bind_current_connectable_fn$fn__20980 invoke "connection.clj" 104]
  [toucan2.connection$bind_current_connectable_fn$fn__20980 invoke "connection.clj" 104]
  [toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource invokeStatic "connection.clj" 18]
  [toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource invoke "connection.clj" 15]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18070$fn__18071$fn__18072 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040$fn__18044 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18050 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [metabase.db.connection$do_with_connection_primary_method_default invokeStatic "connection.clj" 132]
  [metabase.db.connection$do_with_connection_primary_method_default invoke "connection.clj" 130]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18070$fn__18071$fn__18072 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040$fn__18044 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18050 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [toucan2.connection$do_with_connection_primary_method_ invokeStatic "connection.clj" 204]
  [toucan2.connection$do_with_connection_primary_method_ invoke "connection.clj" 194]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18070$fn__18071$fn__18072 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040$fn__18044 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18050 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [toucan2.pipeline$transduce_execute invokeStatic "pipeline.clj" 77]
  [toucan2.pipeline$transduce_execute invoke "pipeline.clj" 64]
  [clojure.lang.Var invoke "Var.java" 399]
  [toucan2.pipeline$transduce_compiled_query invokeStatic "pipeline.clj" 244]
  [toucan2.pipeline$transduce_compiled_query invoke "pipeline.clj" 240]
  [toucan2.pipeline$transduce_built_query invokeStatic "pipeline.clj" 252]
  [toucan2.pipeline$transduce_built_query invoke "pipeline.clj" 246]
  [toucan2.pipeline$transduce_query_primary_method_default invokeStatic "pipeline.clj" 272]
  [toucan2.pipeline$transduce_query_primary_method_default invoke "pipeline.clj" 269]
  [clojure.lang.AFn applyToHelper "AFn.java" 178]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [methodical.impl.combo.threaded$fn__18070$fn__18071$fn__18078 invoke "threaded.clj" 79]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040$fn__18044 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18040 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 doInvoke "core.clj" 2589]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18050 doInvoke "threaded.clj" 46]
  [clojure.lang.RestFn applyTo "RestFn.java" 151]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 65]
  [methodical.impl.standard$invoke_multifn doInvoke "standard.clj" 47]
  [clojure.lang.RestFn invoke "RestFn.java" 594]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 199]
  [toucan2.pipeline$transduce_query_STAR_ invokeStatic "pipeline.clj" 278]
  [toucan2.pipeline$transduce_query_STAR_ invoke "pipeline.clj" 274]
  [toucan2.pipeline$transduce_with_model invokeStatic "pipeline.clj" 293]
  [toucan2.pipeline$transduce_with_model invoke "pipeline.clj" 280]
  [toucan2.pipeline$transduce_parsed invokeStatic "pipeline.clj" 309]
  [toucan2.pipeline$transduce_parsed invoke "pipeline.clj" 295]
  [toucan2.pipeline$transduce_unparsed invokeStatic "pipeline.clj" 317]
  [toucan2.pipeline$transduce_unparsed invoke "pipeline.clj" 311]
  [toucan2.select$select_fn__GT_fn invokeStatic "select.clj" 195]
  [toucan2.select$select_fn__GT_fn doInvoke "select.clj" 181]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 673]
  [clojure.core$apply invoke "core.clj" 662]
  [toucan2.select$select_pk__GT_fn invokeStatic "select.clj" 221]
  [toucan2.select$select_pk__GT_fn doInvoke "select.clj" 210]
  [clojure.lang.RestFn invoke "RestFn.java" 464]
  [metabase.api.table$batch_fetch_query_metadatas_STAR_ invokeStatic "table.clj" 359]
  [metabase.api.table$batch_fetch_query_metadatas_STAR_ invoke "table.clj" 348]
  [metabase.api.table$fn__93453$batch_fetch_table_query_metadatas__93454 invoke "table.clj" 379]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.public_settings.premium_features$dynamic_ee_oss_fn$fn__55937 doInvoke "premium_features.clj" 557]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [metabase.api.query_metadata$metadata_for_table_dependents invokeStatic "query_metadata.clj" 34]
  [metabase.api.query_metadata$metadata_for_table_dependents invoke "query_metadata.clj" 30]
  [metabase.api.query_metadata$metadata_for_dependents invokeStatic "query_metadata.clj" 50]
  [metabase.api.query_metadata$metadata_for_dependents invoke "query_metadata.clj" 49]
  [metabase.api.query_metadata$dashboard_metadata invokeStatic "query_metadata.clj" 152]
  [metabase.api.query_metadata$dashboard_metadata invoke "query_metadata.clj" 118]
  [metabase.api.dashboard$fn__97835 invokeStatic "dashboard.clj" 843]
  [metabase.api.dashboard$fn__97835 invoke "dashboard.clj" 838]
  [compojure.core$wrap_response$fn__52844 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__52828 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__52833 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 151]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__97094 invoke "auth.clj" 18]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52884 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 300]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [metabase.api.routes$fn__103529$fn__103532 invoke "routes.clj" 73]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__103809$fn__103810 doInvoke "routes.clj" 73]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52884 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52888 invoke "core.clj" 300]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 153]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52837 invoke "core.clj" 152]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856$f__52857$respond_SINGLEQUOTE___52858 invoke "core.clj" 197]
  [metabase.server.routes$fn__103792$fn__103794 invoke "routes.clj" 47]
  [compojure.core$routes$fn__52856$f__52857 invoke "core.clj" 198]
  [compojure.core$routes$fn__52856 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__99959 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__99956 invoke "exceptions.clj" 96]
  [metabase.server.middleware.log$log_api_call$fn__104089$fn__104090$fn__104091 invoke "log.clj" 236]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__104089$fn__104090 invoke "log.clj" 227]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__104089 invoke "log.clj" 226]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__107377 invoke "browser_cookie.clj" 40]
  [metabase.server.middleware.security$add_security_headers$fn__99915 invoke "security.clj" 238]
  [ring.middleware.json$wrap_json_body$fn__107636 invoke "json.clj" 64]
  [metabase.server.middleware.offset_paging$handle_paging$fn__86415 invoke "offset_paging.clj" 43]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__54299 invoke "json.clj" 83]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__107725 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__107744 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__69704 invoke "misc.clj" 60]
  [metabase.server.middleware.session$reset_session_timeout$fn__76848 invoke "session.clj" 552]
  [metabase.server.middleware.session$bind_current_user$fn__76814$fn__76815 invoke "session.clj" 446]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 425]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 408]
  [metabase.server.middleware.session$bind_current_user$fn__76814 invoke "session.clj" 445]
  [metabase.server.middleware.session$wrap_current_user_info$fn__76795 invoke "session.clj" 383]
  [metabase.server.middleware.session$wrap_session_id$fn__76767 invoke "session.clj" 259]
  [metabase.server.middleware.auth$wrap_static_api_key$fn__97102 invoke "auth.clj" 32]
  [ring.middleware.cookies$wrap_cookies$fn__107564 invoke "cookies.clj" 200]
  [metabase.server.middleware.misc$add_content_type$fn__69686 invoke "misc.clj" 28]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__69712 invoke "misc.clj" 77]
  [ring.middleware.gzip$wrap_gzip$fn__107606 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__69715 invoke "misc.clj" 94]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__107393 invoke "ssl.clj" 41]
  [metabase.server$async_proxy_handler$fn__70050 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 421]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 390]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 277]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy run "AdaptiveExecutionStrategy.java" 199]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
  [java.lang.Thread run nil -1]],
 :cause "ERROR: syntax error at or near \")\"\n  Position: 50",
 :message "ERROR: syntax error at or near \")\"\n  Position: 50"}

**To Reproduce**
1.	Log in as a non-admin user.
2.	Open a question or dashboard accessible to “All users”.
3.	An error message appears: ERROR: syntax error at or near “)” Position: 50.

**Expected behavior**
The "All users" objects shoud be visible to anoyne.

**Screenshots**

**Severity**
This is blocking our usage of Metabase entirely. Nothing is accessible except for admins.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.8.6-clevercloud-vm-dirty",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "postgres",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-10",
      "tag": "v0.50.0",
      "hash": "4fe42d3"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by ruber0id** [comment]
Same issue, but with MySQL Prod DB (ver. 8.0.36)

**Comment by MathiasGr** [comment]
Same here

**Comment by alyakh-gegi-llc** [comment]
Same [Error showing questions for users without "Create queries" permission after upgrade to v0.50.0](https://github.com/metabase/metabase/issues/44035)

**Comment by darksciencebase** [comment]
possibly introduced by https://github.com/metabase/metabase/pull/43625

**Comment by perivamsi** [comment]
Please upgrade to 50.1, this issue is fixed there.

**Comment by tcourtainsellsy** [comment]
I confirm this is fixed now, thanks a lot.

**Comment by akundevigooodsru** [comment]
We still have this issue on 0.50.1 and 0.50.13 when empty filters from the request are converted to the `where param_name IN ()` in the query. 
Rolled back to 0.49.15 and errors gone.

**Comment by adam-james-v** [comment]
@akundevigooodsru, I suspect that you're encountering a different issue, though you're right that it seems similar. Do you mind opening an issue? If you get a chance to do that, could you also provide a little more detail/context regarding the error you've seen. For example, could you provide information in the issue about which request this happens with? A regular dashboard? An embedded dashboard? That sort of thing.
