### ISSUE TITLE
Users with No Access to the Collection Our Analytics are not able to use the Query Editor for Saved Questions/Models

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#44071]
### Describe the bug

Users with No Access to the Collection Our Analytics are not able to use the Query Editor for Saved Questions/Models

### To Reproduce

1) Go to People -> Groups -> New Group -> Name it Test and Save
2) Go to People -> People -> Invite Someone -> Add it to Group Test
3) Go to Permissions -> Collections -> Give No Access to Test and All Users to Our Analytics 

<img width="1510" alt="image" src="https://github.com/metabase/metabase/assets/110378427/82308b74-22a1-4445-8781-01df98b7fbaf">

4) Go to Permissions -> Data -> Give View and query builder only

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/2fa284db-0200-4df0-9d8f-2c953c3293d3">

5) Then login as that user and try to use a saved question or Model

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/f4d98265-888f-4052-8223-1b02dadc9746">

### Expected behavior

 I expect the user to have access to his personal collection and other collections ... since even giving him access to a new collection doesn't work

### Logs

GET /api/collection/root 403 71.3 ms (2 DB calls) {:metabase-user-id 2} 
"You don't have permissions to do that."

### Information about your Metabase installation

```JSON
50.0
```

### Severity

blocker

### Additional context

Seems to be related to https://github.com/metabase/metabase/issues/30355 and other issues with removing access to the Root collection (Our Analytics)

Also seems that the issue from https://github.com/metabase/metabase/issues/38856 moved to somewhere else

**Comment by bshepherdson** [comment]
https://github.com/metabase/metabase/issues/44043 we fail to fetch metadata for users without permissions to see tables.

I'm not entirely sure why that's surfaced as a permissions error here. But we use missing metadata as a signal for "no permissions" sometimes.

I won't close this in case there's some extra problem here. Try it on master after the fix? #44052.

**Comment by sloansparger** [comment]
I was not able to reproduce the issue on the 50.1 JAR following the steps above. The issue should be fixed.

**Comment by Tony-metabase** [comment]
@sloansparger still an issue and i am on version 50.1

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4bc09631-dc4b-4ec5-89f7-0c2115ee9421">


<img width="1508" alt="image" src="https://github.com/metabase/metabase/assets/110378427/76c3d4bb-b818-4e18-83c3-f6c67e4edd93">
