### ISSUE TITLE
Fix CSS wonkiness in Pulses section

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#4527]
Some missing padding in the heading for the empty state modal:

![screen shot 2017-03-14 at 11 13 03 am](https://cloud.githubusercontent.com/assets/2223916/23964438/c06a116a-0971-11e7-8e5b-b6a9b4303b2e.png)

Some weirdness in displaying this warning message (and maybe other warning messages?):

<img width="435" alt="screen shot 2017-03-14 at 11 54 05 am" src="https://cloud.githubusercontent.com/assets/2223916/23964458/d6f2cb20-0971-11e7-8e6f-a357630e969b.png">

**Comment by kdoh** [comment]
The first issue was fixed by #4422. @mazameli mind giving me a bit more info about which browser and if there were any special circumstances for the second screenshot?

**Comment by mazameli** [comment]
Yeah, this was on Chrome (56.0.2924.87) on our stats instance (which I thought was on `master` but might not be?). The saved question was a funnel, which gets converted to a table when included in a pulse.

**Comment by mazameli** [comment]
I am definitely still seeing the second issue on `release-0.23.0` btw Kyle.

**Comment by mazameli** [comment]
Fixed by #4422 and #4561
