### ISSUE TITLE
Invalid XRay Generated if Join Column in Underlying Models is not also Selected

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#46337]
### Describe the bug

If you created a model that joins two tables on an ID column, but do not also include the column in the "select" - invalid x-rays are generated downstream.

### To Reproduce

1. Spin up Metabase (this was reproduce on 49 and 50)
2. Create a Question with the Sample DB:

* Join orders.user_id to + to [people.id](<http://people.id>)
* Deselect user_id from the column picker for the orders table

3. Promote the Question to a Model
4. X-ray the model
5. Note that invalid SQL is generated for cards on the x-ray dashboard (Column "source.USER_ID" not found;)

Loom recording of a similar flow:<br>[https://www.loom.com/share/40f7587c08254fc9b72b05231842750d?sid=9187d5de-1af7-4b30-b01c-b660e1482a25](<https://www.loom.com/share/40f7587c08254fc9b72b05231842750d?sid=9187d5de-1af7-4b30-b01c-b660e1482a25>)

### Expected behavior

The xray should work

### Logs

*No response*

### Information about your Metabase installation

```JSON
v50.13
```

### Severity

annoying

### Additional context

You can work around this by converting the model back to a question, adding the ID columns back to the question and promoting it back to a model.

**Comment by ranquild** [comment]
Can be reproduced on 0.53.1. Fixed in master `0c7400c81eb29c27ad21d55d6c9486b4d0668206`, pre-v56. Repro steps:
- Models -> New -> Notebook -> Orders -> Join People. Remove `User ID` from `Orders` columns. Save.
- Go to the collection -> X-ray this.
- Check that queries can be executed.

Before:

<img width="1201" height="716" alt="Image" src="https://github.com/user-attachments/assets/16196b3e-1ffa-41bf-8eb7-6004773ca851" />

Now:

<img width="1162" height="785" alt="Image" src="https://github.com/user-attachments/assets/46a5ec1a-d95f-48c5-a2ba-bd12a8f54dd5" />

**Comment by romeovs** [comment]
I can still reproduce this on `master` (`a4fe6afc7fe8f7c71ec530a7baf8f697660f520e`).

See repro in https://github.com/metabase/metabase/pull/60845

**Comment by ranquild** [comment]
Can be still reproduced on v57
