### ISSUE TITLE
Pivot Table Column reordering from Visualization UI doesn't reflect in downloaded files

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#48442]
### Describe the bug

If you order the columns for a Pivot Table via the UI, they will show up in the Visual but will not reflected in downloaded files:

 ![Image](https://github.com/user-attachments/assets/1443be13-c299-473f-b07b-11b8757c6201)

It only works if you order them form the editor section:

![Image](https://github.com/user-attachments/assets/257480e3-a538-4eba-bc06-a8b01f3e3520)

### To Reproduce

1. Go toNew ->  Question -> Products -> Count and Sum of Rating -> Grouped by Created At -> Turn into a Pivot

![Image](https://github.com/user-attachments/assets/5a06bb54-8f58-49d0-bd91-b80bc9df7591)

2.Re-order the columns from the UI

![Image](https://github.com/user-attachments/assets/b2be9387-29eb-4184-a1f2-397370162fdb)

3. Download the Pivot and notice that the order didn't match the Pivot

![Image](https://github.com/user-attachments/assets/4de2c41b-2177-47f3-aaa8-39ff265a683a)

You can test this on stats https://stats.metabase.com/question/20058-test

### Expected behavior

The download should be an exact copy of what you get presented in the UI

### Logs

None that are relevant

### Information about your Metabase installation

Tested on 50.28 and master

### Severity

It's very annoying if you don't know about this bug. 

### Additional context

There is a workaround in which you need to go and order the columns from the editor

**Comment by kamilmielnik** [comment]
Also dates are formatted differently in the "Created At" column

**Comment by Tony-metabase** [comment]
I am escalating this cause it causes more weird stuff happening when you add the question to a dashboard, for reference:

https://stats.metabase.com/dashboard/2650-test

I added a new column to the question

![Image](https://github.com/user-attachments/assets/b2b6a0c9-a42c-4e43-b4dd-4a364841efaf)

And added the question to the dashboard but the order is still broken:

![Image](https://github.com/user-attachments/assets/35660a2c-81ad-4e4a-bf3d-9f5939519c42)

This makes pivot with many columns very very hard to work with

**Comment by adam-james-v** [comment]
This bug is solved by https://github.com/metabase/metabase/pull/46995

Since the fix for v50 is a bit of a hacky fix, I am closing this issue and encourage transitioning to v51 when feasible, as the pivot exports are much improved.

In the meantime, as a workaround, it should be possible to switch to Table viz, arrange columns as you want them to be there, save the question, and switch back to a pivot viz. This may not be perfect, but can be a stopgap until v51 can be used.

**Comment by Tony-metabase** [comment]
Reopening this since the download as pivot still doesn't respect reordering, both if you thick the Keep data pivoted option

![Image](https://github.com/user-attachments/assets/775a096d-3103-4ce3-aaf1-3918a5be252e)

Also for the Keep data pivoted enabled the column names this time are also being ignored

![Image](https://github.com/user-attachments/assets/11a7c178-1692-4a72-ba9c-de2f98cf228c)
