### ISSUE TITLE
Enable caching for static files to improve embedded dashboard performance

### ISSUE THREAD

**Issue by rodrigoGA** [metabase/metabase#50373]
The file app-embed.ab96202c244c98ca.js takes over 5 seconds to load, significantly slowing down the loading of embedded dashboards. This file does not include caching headers (Cache-Control and Expires), forcing browsers to re-download it on every visit.

![Image](https://github.com/user-attachments/assets/19d2a810-68e2-4b9f-a108-2864abfd8d8c)

Impact:

Prolonged loading times: Negatively affects the user experience for embedded dashboards.
Increased bandwidth usage: Causes unnecessary requests to the server.
Request:

Mark the file as cacheable by adding headers such as:

```
Cache-Control: public, max-age=31536000
Expires: [future date]
```
This will allow browsers to store the file locally and improve performance.

**Comment by paoliniluis** [comment]
@rodrigoGA version of Metabase? how are you deploying Metabase and where?

**Comment by rodrigoGA** [comment]
I am deploying it using the jar.

Metabase info:
```
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-19",
      "tag": "v0.51.4",
      "hash": "47f05f3"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.114.2.el7.x86_64",
    "user.language": "es",
    "user.timezone": "Europe/Madrid"
  }
}
```

**Comment by paoliniluis** [comment]
@rodrigoGA send please the size of the asset as I can’t see it on the screenshot, also send us where you’re physically located and the configuration of the reverse proxy/load balancer

**Comment by rodrigoGA** [comment]
@paoliniluis the size of the asset is 1 MB. It's currently installed in Europe on Metabase. I’m accessing it from America, and there is an Apache server acting as the reverse proxy in front. Please note that gzip compression is not yet configured on the reverse proxy.

For context, I have other deployments on similar infrastructure that don’t experience the same level of slowness when loading.

**Comment by roycai1234** [comment]
Yes I got the same problem. I deployed on docker, v0.51.4. It took me quite a long time to load the first page every time I refreshed the page. I checked the network traffic and found the some static files were reloaded every time,and no cache. 
I tried to downgrade to v0.50.31 （It also took me  a long time to download from 0.51 to 0.50 on docker）, then it's OK.

**Comment by rodrigoGA** [comment]
Yes, I also notice the slow load of the application overall, but where it
impacts the most is in the embeddings as well.

**Comment by rodrigoGA** [comment]
@paoliniluis @heypoom  According to the changelog, they fixed this in v0.52.1, but after updating to that version, none of the static files are returning the cache header.
This bug is still active.
![Image](https://github.com/user-attachments/assets/40d9f169-299e-4abc-93d7-93c9239b3d64)

**Comment by paoliniluis** [comment]
@rodrigoGA, can you check if this is still valid in 53? we haven't got any reports of this other than your comment
