### ISSUE TITLE
Metabase Initialization Failure due to com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'core_organization' already exists

### ISSUE THREAD

**Issue by ktkization** [metabase/metabase#5094]
Browser: Chrome.
OS: Ubuntu 14.04.3 LTS
Database is MYSQL
Previous Metabase version: 0.20.0
Metabase version trying to upgrade to: 0.24.0

I'm getting this error when trying to upgrade from version 0.20.0 to 0.24.0
```
Metabase is not initialized yet!
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'core_organization' already exists
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
```
After doing some research I came across a similar past issue https://github.com/metabase/metabase/issues/2672 but the fix suggested `java -jar metabase.jar migrate force` doesn't fix the migration issue I'm experiencing 

Any pointers to what might be going wrong with my upgrade ?

**Comment by VikramTiwari** [comment]
I am trying to do this from 0.23.1 to 0.24.0 and still the same issue. This is not great considering folks might be doing this directly on their production.

@camsaul @salsakran Urgent issue

**Comment by bernardosrulzon** [comment]
+1!

**Comment by thearthur** [comment]
This issue is fixed in #5073 and there is a sql command there that you can use to get the upgrade to run.

**Comment by salsakran** [comment]
hey @ktkization @VikramTiwari @bernardosrulzon this has been fixed in #5079 and in 0.24.1 which we just pushed out right now.

Please try upgrading with that and letting us know if it works. 

Sorry for the hassle! =(

**Comment by bernardosrulzon** [comment]
Fixed for me @salsakran! Thanks!

**Comment by VikramTiwari** [comment]
This is fixed now. Thanks! 👍

**Comment by SubigyaPanta** [comment]
I'm having similar issue.
I'm running the metabase using docker and docker-compose. Here is my compose file:
```
version: '3'
services:
  metabase:
    image: metabase/metabase:v0.39.1
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=3306
      - MB_DB_USER=secretuser
      - MB_DB_PASS=secretword
      - MB_DB_HOST=secrethost
    ports:
      - 3000:3000
```

After Compose up, I get this error:

```
metabase_1  | 2021-05-17 08:27:59,084 ERROR metabase.core :: Metabase Initialization FAILED
metabase_1  | liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
metabase_1  |      Reason: liquibase.exception.DatabaseException: (conn=32027) Table 'core_organization' already exists [Failed SQL: CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`)) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci]
metabase_1  |   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
..
.. <lot of lines here>
..
metabase_1  | Caused by: java.sql.SQLException: Table 'core_organization' already exists
metabase_1  |   at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
metabase_1  |   at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
metabase_1  |   at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
metabase_1  |   at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
metabase_1  |   ... 57 more
metabase_1  | 2021-05-17 08:27:59,109 INFO metabase.core :: Metabase Shutting Down ...
```

I think the issue still exists in version v0.39.1. I also tried with v0.38.5 and still got the same problem.

**Comment by flamber** [comment]
@SubigyaPanta Make sure you have an empty database. And otherwise follow the requirements from the notes:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html#notes

**Comment by SubigyaPanta** [comment]
@flamber Yes, I tried it with empty schema. when I got the above error.

More info on database:
MySQL version 8.0.21
Default collation: utf8mb4_general_ci
Default characterset: utf8mb4
MySQL instance is from AWS RDS. I don't know if it is because of AWS.

**Comment by flamber** [comment]
@SubigyaPanta I don't know what's wrong if you have deleted the database and created an empty database again. I guess it's a compatibility problem with AWS RDS not actually running MySQL, but some custom build. It's working fine locally on 8.0.21

Check which charset/collation the database was created with - should be `utf8mb4` and `utf8mb4_unicode_ci`:
`SELECT * FROM information_schema.schemata WHERE schema_name = 'metabase'`

You can start the setting the environment variable [MB_DB_AUTOMIGRATE=false](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_automigrate), which should show all queries in the console, which you can then run directly on your database, and then you should be able to start Metabase.

**Comment by SubigyaPanta** [comment]
@flamber Like you said, when I ran it on local it worked. Turns out I didn't had ALTER and REFERENCE permissions in the database in AWS. It's fixed now. Thank you for your support.
