### ISSUE TITLE
Dashboard card title links can't be opened in new tab/window on Windows or Linux

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5168]
Command/ctrl+clicking or right-clicking on question titles for cards on dashboards no longer allows you to open that question in a new window or tab. I tested this on Chrome on master, but [another user reported it on Windows](http://discourse.metabase.com/t/can-i-know-why-its-not-posible-to-open-the-questions-on-a-new-tab-like-it-was-before/1538) (unsure which browser).

**No `new tab` or `new window` options in the context menu:**

![screen shot 2017-05-22 at 2 21 37 pm](https://cloud.githubusercontent.com/assets/2223916/26329043/3dc829c2-3efa-11e7-831d-78395982ca6c.png)

**But those options are present on question links in the rest of the app, like the Questions list:**

![screen shot 2017-05-22 at 2 21 51 pm](https://cloud.githubusercontent.com/assets/2223916/26329096/6c747258-3efa-11e7-8ffc-9e85fe19f318.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by kdoh** [comment]
This is happening because we're not actually using links for titles on dash card visualizations. Instead, clicking on the title element calls `onChangeCardAndRun(card)` I'm not entirely sure why we're doing that instead of just linking to the query builder with the card ID. @attekei or @tlrobinson have any light to shed on this?

**Comment by attekei** [comment]
I will take a look at this now as I'm trying to solve other `onChangeCardAndRun`-related challenges (more specifically https://github.com/metabase/metabase/issues/5028 + a dashcard title lineage bug)

**Comment by tlrobinson** [comment]
It's not as simple as linking to `/question/{card.id}` any more. `onChangeCardAndRun` merges the currently applied dashboard parameters into the card definition and url params before redirecting.

It's nice having a single function for both drill through and card titles etc, but we could have another function that formats the URL with those same modifications.

Or perhaps we could simulate the command click behavior so that it also works on drill through?

**Comment by attekei** [comment]
> Or perhaps we could simulate the command click behavior so that it also works on drill through?
Intuitively this option would make most sense

**Comment by kdoh** [comment]
Would it be possible to dynamically update the link with the relevant information so we could still use a native link tag instead of doing a push under the hood when you click?

**Comment by tlrobinson** [comment]
That's what my suggestion in the 2nd paragraph meant.

**Comment by kdoh** [comment]
It'd be super cool if I learned to read one of these days. That seems like my preference.

**Comment by cyberhorse** [comment]
Also, to the best of my knowledge, this is a regression issue. It used to work fine before (maybe 0.22 and before)

**Comment by attekei** [comment]
This and #2647 are interrelated as both use React's `onClick` handler for triggering a Redux action that navigates to other part of the app. I did earlier a quick experiment in #5207 where there is related discussion. Currently I agree with @kdoh that in many cases it would be ideal to replace `onClick` handlers with generated urls.

**Comment by amywtlin** [comment]
+1. We just upgraded and me and my colleague are pretty used to opening queries in a new tab, and I'm pretty bummed we can't do it anymore

**Comment by mazameli** [comment]
I'd love to see us fix this in 0.27. The current situation makes it pretty rough going back and forth from a slow-loading dashboard to one of its card's detail views.

**Comment by camsaul** [comment]
@mazameli is this a duplicate of #2647 ?

**Comment by paulrosenzweig** [comment]
Resolved by #8860

**Comment by flamber** [comment]
@paulrosenzweig May I disagree and say that this is not fixed? You cannot use `ctrl` or `shift` or right-click, which is what Maz is referring to.
You can since 0.31.2 use `Metakey`, which is probably great if you're using Mac, since it's `cmd` (I think), but for everyone else, that's not how link controls work.

**Comment by paulrosenzweig** [comment]
@flamber ah thanks! I had only tested on a Mac 🤦‍♂

**Comment by shenoyroopesh** [comment]
For me it doesn't seem to work on mac either. What do you do to have a new window open on mac?

**Comment by shenoyroopesh** [comment]
Just realized, using Firefox.

**Comment by patvong** [comment]
This is not fixed neither on Firefox and Chrome on Mac. Would really like this to be fixed.

**Comment by flamber** [comment]
@patvong 
Which version of Metabase? And you're pressing `Command`, which is the `MetaKey` on Mac, whereas it's `Windows` on Windows.

**Comment by patvong** [comment]
@flamber Ah, was it fixed on a newer version?
Our company is running an old one:
```
You're on version v0.31.1
Built on 2018-11-21
```

**Comment by flamber** [comment]
@patvong As I wrote on a previous https://github.com/metabase/metabase/issues/5168#issuecomment-515496809, it's fixed on 0.31.2, but only on Mac. For everyone else, using `MetaKey` is not practically, since it's `Windows` instead of `Ctrl`. And it doesn't play nice on Linux.

**Comment by danbroun** [comment]
> @patvong As I wrote on a previous [#5168 (comment)](https://github.com/metabase/metabase/issues/5168#issuecomment-515496809), it's fixed on 0.31.2, but only on Mac. For everyone else, using `MetaKey` is not practically, since it's `Windows` instead of `Ctrl`. And it doesn't play nice on Linux.

Yeah at least Windows key is working. That already helps a lot even though it is not really intuitive.

**Comment by vvaezian** [comment]
Currently the `Windows` key opens in new tab in Chrome but not in Firefox.

Firefox 83.0 (64-bit) [latest version]
Metabase v0.37.2

**Comment by Sire** [comment]
How can this horrible usability bug still be here over three years later? Web users expect to be able to open reports in new tabs. Especially if you need to reload a slow dashboard for every new report you want to look at.

Can't you modify the windows+click trigger to also monitor ctrl+click on Windows?

**Comment by maximepvrt** [comment]
issue is no longer scheduled ?

**Comment by Koojav** [comment]
Any news on fixing this issue?

**Comment by brendanheywood** [comment]
Correct me if I'm wrong, but it looks like the problem here was these were fake links in js instead of plain html links, and the solution was to add even more js to add more workarounds. From what I can tell this still won't fix the problem and a right click to explicitly open the OS context menu and choose whether its a new tab or a new window, (or even just copy the link) will still not work, nor will other ways like a middle button click on most 3 button mice. And I doubt this has great accessibility (#1462).

Surely it's way less code and complexity to just remove all the js and render a plain link?

**Comment by maximepvrt** [comment]
@ranquild, have you seen @brendanheywood message ?

**Comment by zqiang-bolt** [comment]
looks like having this issue again in version v0.44.2

**Comment by brendanheywood** [comment]
From my point of view this issue was never fixed in the first place, the solution was just plain wrong
