### ISSUE TITLE
Table metadata not getting updated for removed fields

### ISSUE THREAD

**Issue by ujjwal-gupta** [metabase/metabase#5292]
On removing a Mongo collection (table) and then adding it back after adding new and removing some old fields, and triggering a manual sync from the admin panel, I observed that the new fields came up but the old ones that had been removed stayed. In metabase's db I observed that the table was never really deleted, just marked as inactive and I'm guessing the app just adds any new fields it observes on a sync.

As a workaround, I was using a different collection name to store my data for a while hoping the metadata of the old data would eventually clear out but it still hasn't. Now it seems like that table name has become a reserved word and I can't use it for any of my tables because I'll continue to see fields that aren't even there in it.

MongoDB
Metabase version: 0.24.2
Hosted on Elastic Beanstalk t2.large
Metabase internal database: MySQL

**Comment by Varunram** [comment]
@ujjwal-gupta Well, that's weird. I did something similar on a `postgres` table and it seems to work perfectly fine. Will wait for someone on a mongo database and report.

**Comment by ujjwal-gupta** [comment]
If I had to guess I would say it's because in Mongo it's not necessary for all documents to have every field so Metabase fields are a superset. Whenever they see a document with a new field, they add it to the data model but they don't check all document to see if a field has been removed from all of them once it's been added.

**Comment by camsaul** [comment]
This was fixed by #5510

**Comment by brijendra98** [comment]
I am still facing this issue and it doesn't seem to be fixed.

**Comment by camsaul** [comment]
@brijendra98 we haven't shipped the fix yet

**Comment by mazameli** [comment]
Hey everyone. Just a heads up that [we've shipped version 0.26](http://www.metabase.com/blog/Metabase-0.26) with a fix for this issue.
