### ISSUE TITLE
Time-series grouped by week off by 1?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#5324]
Something funny going on with by-week time series charts. This one is filtered to only show June 2017, but the first data point is showing the last week of May. There also is no data point for the current, incomplete week; the last week plotted on the chart ends on June 10, though the x-axis does display a tick for June 11. If I change the filter to `This Year`, the chart still ends before the current incomplete week (i.e. the week starting on Sunday, June 11, 2017). The table data appears to match the chart.

<img width="1056" alt="week-chart" src="https://user-images.githubusercontent.com/2223916/27098108-40db6f2e-502b-11e7-9d06-5db50cdb58bf.png">

**Comment by Varunram** [comment]
@mazameli Weird. If I may know, what type is Column Month? I have a column with type timestamp and I seem to get stuff right when I filter them.

**Comment by tlrobinson** [comment]
Actually, I think this is a duplicate of #2517, but we changed the formatting so it seems different.

**Comment by Varunram** [comment]
Another related issue for you guys: #4180

**Comment by gilhs** [comment]
Possible related to #5246 as well?

**Comment by Varunram** [comment]
Yeah, there seems to be a chain of these date time issues. Weird.

**Comment by salsakran** [comment]
repro-d. Think it has something to do with the server timezone. When using the same DB maz is using, I get correct axis ticks.

**Comment by salsakran** [comment]
This is a dupe of #3642, #3744, #4180, #4245, #2517
I believe the root cause is #2035

We're working on this now, and planning on kicking it out in the next release, whether 0.25.2 if there is one, or 0.26

**Comment by joevandyk** [comment]
@salsakran thanks! it would be awesome to have a 0.25.2 rolled out with this fix (it's been confusing users to have to add one to the month in charts/tables).

**Comment by camsaul** [comment]
@joevandyk 0.25.2 is already out

**Comment by joevandyk** [comment]
ah ok. thanks for the update!

**Comment by VikramTiwari** [comment]
Based on my debugging:
If a question is created using "today" or any date based filter where today's date is being used, the result ends up being wrong because the server timezone is being used for generating queries. So after 5 pm on PDT, all those queries break.

**Comment by senior** [comment]
The fix for this was just merged (https://github.com/metabase/metabase/pull/5729) and will be included in the next 0.26 RC release

**Comment by joevandyk** [comment]
@senior awesome! is there an easy way to pull down a docker image of something that includes this fix?

**Comment by senior** [comment]
We don't create docker images for RC releases unfortunately, so you'll have to use the JAR directly.

**Comment by joevandyk** [comment]
if you did create docker images for rc releases, I'd be able to test it and give feedback. :)

I suppose I could look into building my own docker images.. is that build process complicated?

**Comment by senior** [comment]
I'm not sure, I think @salsakran usually creates the docker images. Running the JAR is pretty easy, just `java -jar metabase.jar`. The RC JAR can be found on the [release page](https://github.com/metabase/metabase/releases/tag/v0.26.0.RC1)

**Comment by salsakran** [comment]
@VikramTiwari @joevandyk This should be fixed in 0.26, which went out today. Can you verify?

**Comment by VikramTiwari** [comment]
Just checked. Doesn't seem so. An easy way to check is to query for last 2 weeks of data and you should see the issue still present.

**Comment by joevandyk** [comment]
It seems fixed for me.

**Comment by ebalgava** [comment]
Doesn't seem so also for my related issue 
https://github.com/metabase/metabase/issues/3642#issuecomment-332653232
https://bi.ekosystem.slovensko.digital/public/dashboard/86ce303c-05bf-4947-bb39-d2a958208492
