### ISSUE TITLE
JS error when editing filtered field in dashboards

### ISSUE THREAD

**Issue by Sytten** [metabase/metabase#5365]
Hi,

I encountered this bug when I try to edit the filter fields of questions in a dashboard. When I click on a card, it sticks to my cursor no matter what I do (I have to refresh the page). I can barely change the field if I place my cursor at the right place before. In the console this is the error:
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at s (app-main.bundle.js:145)
    at Object.m [as getParameterMappingOptions] (app-main.bundle.js:145)
    at app-main.bundle.js:145
    at app-main.bundle.js:75
    at app-main.bundle.js:75
    at app-main.bundle.js:75
    at app-main.bundle.js:75
    at Function.t [as mapToProps] (app-main.bundle.js:145)
    at r (app-main.bundle.js:30)
    at Function.r.mapToProps (app-main.bundle.js:30)
```
- Your browser and the version: Chrome 58
- Your operating system: OS X Sierra
- Your databases: Postgres
- Metabase version: 0.24.2

![screen shot 2017-06-20 at 2 58 20 pm](https://user-images.githubusercontent.com/2366731/27334280-144405f4-55c9-11e7-9956-887ce59b7adf.png)

**Comment by mazameli** [comment]
Should have been fixed by https://github.com/metabase/metabase/pull/10206

**Comment by kleban31** [comment]
This is still happening to me. Like right now. Version 0.34.1

**Comment by flamber** [comment]
@kleban31 You're most likely seeing a different issue. Please update to latest 0.35.2. Remember to backup first.
And you can use the forum for questions and troubleshooting: https://discourse.metabase.com/
