### ISSUE TITLE
Type errors on Nextjs (and possibly others) "'MetabaseProvider' cannot be used as a JSX component."

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#53767]
Thread with the customer: https://metaboat.slack.com/archives/C07166YL2UU/p1737479261789419

Thread 1 of investigation: https://metaboat.slack.com/archives/C063Q3F1HPF/p1737479654203179
Thread 2 of investigation: https://metaboat.slack.com/archives/C063Q3F1HPF/p1739530363089089

It seems like `@types/react` is installed multiple times, specifically, there's a copy inside `node_modules/@metabase/emebedding-sdk-react/...` which shouldn't be there.

**Comment by npretto** [comment]
Customer confirmed it was fixed

**Comment by PavankalyanVana** [comment]
```typescript
<MetabaseProvider authConfig={authConfig}>
	<InteractiveDashboard
		dashboardId={dashboardId}
		initialParameters={data?.initialParameters}
		hiddenParameters={data?.hiddenParameters}
		withTitle={false}
		withDownloads={false}
		onLoad={() => {
			setIsLoading?.(false);
		}}
	/>
</MetabaseProvider>
``` 
i am still getting this error 

Type error: 'MetabaseProvider' cannot be used as a JSX component.
  Its type 'NamedExoticComponent<MetabaseProviderProps>' is not a valid JSX element type.
