### ISSUE TITLE
ERROR: operator does not exist: integer = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. 

### ISSUE THREAD

**Issue by sashaaro** [metabase/metabase#5632]
Google Chrome 59.0.3071.115
Ubuntu 17.04
PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
- Metabase version: 0.25.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

`SELECT COUNT("order".order_id) AS sclr_0, TO_CHAR("order".created_at, 'YYYY-MM-DD') AS
sclr_1 FROM "order" where {{created_at}} AND {{restaurant}}
GROUP BY sclr_1;`

restaurant variable ->  Widget: id

ERROR: operator does not exist: integer = character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 331

Logs

Jul 28 16:27:32 WARN metabase.query-processor :: {:status :failed,
:class java.lang.Exception,
:error "ERROR: operator does not exist: integer = character varying\n Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n Position: 275",
:stacktrace
["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:349)"
"driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:345)"
"driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:396)"
"driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:392)"
"driver$fn__22473$G__22466__22480.invoke(driver.clj:45)"
"query_processor$execute_query.invokeStatic(query_processor.clj:49)"
"query_processor$execute_query.invoke(query_processor.clj:43)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__26496.invoke(mbql_to_native.clj:30)"
"query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__25019.invoke(annotate_and_sort.clj:41)"
"query_processor.middleware.limit$limit$fn__26451.invoke(limit.clj:14)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26299.invoke(cumulative_aggregations.clj:46)"
"query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__26299.invoke(cumulative_aggregations.clj:46)"
"query_processor.middleware.format_rows$format_rows$fn__26442.invoke(format_rows.clj:21)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__27720.invoke(results_metadata.clj:88)"
"query_processor.middleware.resolve$resolve_middleware$fn__24627.invoke(resolve.clj:329)"
"query_processor.middleware.expand$expand_middleware$fn__26193.invoke(expand.clj:536)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__24711.invoke(add_row_count_and_status.clj:14)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__26319.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__27730.invoke(resolve_driver.clj:14)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__25099.invoke(cache.clj:146)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__26241.invoke(catch_exceptions.clj:58)"
"query_processor$process_query.invokeStatic(query_processor.clj:124)"
"query_processor$process_query.invoke(query_processor.clj:120)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:232)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:227)"
"query_processor$fn__27764$process_query_and_save_execution_BANG___27769$fn__27770.invoke(query_processor.clj:270)"
"query_processor$fn__27764$process_query_and_save_execution_BANG___27769.invoke(query_processor.clj:256)"
"api.card$run_query_for_card.invokeStatic(card.clj:491)"
"api.card$run_query_for_card.doInvoke(card.clj:477)"
"api.card$fn__29925$fn__29928$fn__29929.invoke(card.clj:498)"
"api.card$fn__29925$fn__29928.invoke(card.clj:497)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:227)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:222)"
"api.card$fn__29925.invokeStatic(card.clj:493)"
"api.card$fn__29925.invoke(card.clj:493)"
"middleware$enforce_authentication$fn__28955.invoke(middleware.clj:122)"
"api.routes$fn__40133.invokeStatic(routes.clj:56)"
"api.routes$fn__40133.invoke(routes.clj:56)"
"routes$fn__40784$fn__40785.doInvoke(routes.clj:75)"
"routes$fn__40784.invokeStatic(routes.clj:71)"
"routes$fn__40784.invoke(routes.clj:71)"
"middleware$log_api_call$fn__29054$fn__29056.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__29054.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__29004.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__28959.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__29008.invoke(middleware.clj:268)"],
:query
{:type "native",
:native
{:query "SELECT COUNT(\"order\".order_id) AS sclr_0, TO_CHAR(\"order\".created_at, 'YYYY-MM-DD') AS\nsclr_1 FROM \"order\" where {{created_at}} [[AND {{restaurant}}]]\nGROUP BY sclr_1;",
:template_tags
{:created_at
{:id "431f6a38-455e-db5e-d862-59d6903b3242", :name "created_at", :display_name "Created at", :type "dimension", :required true, :dimension ["field-id" 166], :widget_type "date/range"},
:restaurant {:id "66ad5e09-0957-d8e2-d85f-30cab586024a", :name "restaurant", :display_name "Restaurant", :type "dimension", :dimension ["field-id" 181], :widget_type "id"}}},
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:parameters [{:type "id", :target ["dimension" ["template-tag" "restaurant"]], :value "6"}],
:cache_ttl nil,
:info
{:executed-by 1,
:context :question,
:card-id 3,
:dashboard-id nil,
:query-hash [-49, -69, -67, 38, 55, -79, -44, 54, 54, -72, -75, -20, 71, -14, 52, -66, -89, -106, -38, 7, 42, 16, 27, 25, 122, 123, 24, -84, 42, 71, -116, -126],
:query-type "native"}},
:expanded-query nil}

Jul 28 16:27:32 WARN metabase.query-processor :: Query failure: ERROR: operator does not exist: integer = character varying
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Position: 275
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:201)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:194)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:233)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:227)"
"query_processor$fn__27764$process_query_and_save_execution_BANG___27769$fn__27770.invoke(query_processor.clj:270)"
"query_processor$fn__27764$process_query_and_save_execution_BANG___27769.invoke(query_processor.clj:256)"
"api.card$run_query_for_card.invokeStatic(card.clj:491)"
"api.card$run_query_for_card.doInvoke(card.clj:477)"
"api.card$fn__29925$fn__29928$fn__29929.invoke(card.clj:498)"
"api.card$fn__29925$fn__29928.invoke(card.clj:497)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:227)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:222)"
"api.card$fn__29925.invokeStatic(card.clj:493)"
"api.card$fn__29925.invoke(card.clj:493)"
"middleware$enforce_authentication$fn__28955.invoke(middleware.clj:122)"
"api.routes$fn__40133.invokeStatic(routes.clj:56)"
"api.routes$fn__40133.invoke(routes.clj:56)"
"routes$fn__40784$fn__40785.doInvoke(routes.clj:75)"
"routes$fn__40784.invokeStatic(routes.clj:71)"
"routes$fn__40784.invoke(routes.clj:71)"
"middleware$log_api_call$fn__29054$fn__29056.invoke(middleware.clj:331)"
"middleware$log_api_call$fn__29054.invoke(middleware.clj:330)"
"middleware$add_security_headers$fn__29004.invoke(middleware.clj:245)"
"middleware$bind_current_user$fn__28959.invoke(middleware.clj:142)"
"middleware$maybe_set_site_url$fn__29008.invoke(middleware.clj:268)"]

**Comment by camsaul** [comment]
@sashaaro as that error suggests you're trying to compare an integer with text, which isn't allowed in Postgres. Double-check that you picked the right type for your parameters

**Comment by jpulec** [comment]
I've encountered this issue as well, and it seems that adding a field filter to SQL query that points to a foreign key will not work, and fails with this error.

**Comment by salsakran** [comment]
Re-pro'd.

Using a parameter filter with H2 works just fine, but trying to do this on PostgreSQL blows up with the above error
![screen shot 2017-07-31 at 6 03 14 pm](https://user-images.githubusercontent.com/107439/28804840-9cdbfcb6-761a-11e7-825e-ef5b016d40df.png)

**Comment by camsaul** [comment]
@salsakran did you set the "User" param as a number?

**Comment by salsakran** [comment]
I set it as a field filter, and used the “ID” widget

**Comment by rossbeale** [comment]
seeing this too - pretty confident this worked pre 0.25

**Comment by camsaul** [comment]
I think this has been fixed at some point as I am not able to repro on 0.28.3.

@salsakran (or anyone else) can you please try to repro this bug and confirm that it is indeed fixed?

**Comment by salsakran** [comment]
confirmed that it's been fixed sometime between when I repro'd it and the current version of master.

**Comment by pelletencate** [comment]
I would like this issue to be reopened: it still happens when you're directly navigating to a URL that has the value in the query string.

 0.32.5

1. Create a question with a field filter on a foreign key.
2. Make the field filter required, leave the default value empty
3. Save the question
4. Open a new browser tab and head directly to /question/xyz?filter_name=123
**Exp:** Resultset with the filter applied
**Act:** `org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying`
5. Clear the filter box on the top toolbar, and manually fill in the `123` that was first put in the query string, and click "Get Results"
6. Query works fine

**Comment by flamber** [comment]
Hi @pelletencate 
You should probably create a new issue, since this issue has been closed for a long time.
But I cannot reproduce your issue on 0.32.5 with PG 11.2 by using sample data with the query:
```
SELECT COUNT(*) FROM "SampleData"."orders"
WHERE quantity={{qty}}
```
![image](https://user-images.githubusercontent.com/1447303/57153506-bb35dc00-6d93-11e9-9ffe-3ed18344793d.png)

**Comment by camsaul** [comment]
The errors you're seeing here should be fixed by #10103

**Comment by wihodges** [comment]
I just updated to 0.33 and getting this error when trying to filter count to equal than '1':

![Screenshot 2019-09-05 11 58 51](https://user-images.githubusercontent.com/286956/64362740-ab920280-cfd4-11e9-89de-4d3e846ac684.png)

So this should be a pretty simple filter that excludes any rows with count of 1. I'm pretty sure I was able to do this in the previous version of sql editor...?

**Comment by wihodges** [comment]
Oh I guess on second glance my error message is slightly different: 
ERROR: operator does not exist: bigint >= character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 747

**Comment by paulrosenzweig** [comment]
@wihodges that's a new bug in 33.1 which was released yesterday. The fix has been merged #10809 and we'll hopefully get 33.2 out soon.

**Comment by citizen-seven** [comment]
I've encountered this issue on Metabase 34.3

`ERROR: operator does not exist: integer = character varying`

When I enter the filter first time it goes ok, but page refresh leads to this error.

Filter type: ID.

**Comment by flamber** [comment]
@citizen-seven While it was fixed for most cases in 0.34.3, #11883, there were cases that only got fixed in 0.35.0, #11911
But it's definitely not this issue anymore. Otherwise start a new issue, when you have tested with 0.35.4
