### ISSUE TITLE
Deleted columns still being shown in MongoDB metadata.

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#5814]
Reported at http://discourse.metabase.com/t/cleaning-up-old-columns/1845

@camsaul might be useful to check if this behaviour still exists with the rewrite.

**Comment by camsaul** [comment]
Yeah that was because the old sync code had that separate "dynamic" sync stuff for mongo which never deleted old columns. Anyways it doesn't work that way anymore since we're back to one copy of the sync code

**Comment by chris062689** [comment]
Thank you very much for a response.

Is there an upgrade path or information on this rewrite?

Is there a way to resolve our issue in the current version?

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/5510?

**Comment by chris062689** [comment]
Will retest today and let you know.

**Comment by chris062689** [comment]
Attempted to test with new columns and it still does not appear to be synchronizing the new columns / removing old ones. 

The only unique configuration my environment has, is connecting to the Mongodb instance through a SSH tunnel (that's not managed by metabase)

**Comment by camsaul** [comment]
Fixed by #5814
