### ISSUE TITLE
Timeseries spanning dozens of years or more show too many ticks

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#590]

**Comment by tlrobinson** [comment]
This should be fixed, @agilliland can you confirm it is?

**Comment by agilliland** [comment]
Yeah, this is still happening for me.  It's a tough one because it's not a highly likely scenario, but if we are plotting a lot of points in a chart ideally the axis labels will keep scaling appropriately to not become garbled.

<img width="1395" alt="screen shot 2015-10-29 at 6 14 05 pm" src="https://cloud.githubusercontent.com/assets/1987787/10836331/6dfe6668-7e69-11e5-8b4b-f975d3c530de.png">

**Comment by camsaul** [comment]
@agilliland is this still an issue?

**Comment by agilliland** [comment]
yes

**Comment by agilliland** [comment]
To reproduce (using Crunchbase data):
* start a new question
* pick `Investments` table
* pick `count of rows` aggregation
* add breakout by `Funded At`
* run the query
* select bar/line/area chart
