### ISSUE TITLE
Public links are broken in master

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6352]
I get the following error 

![screen shot 2017-11-08 at 11 05 25 am](https://user-images.githubusercontent.com/107439/32569005-bf869f20-c474-11e7-8168-06eed57993a2.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
^ @kdoh is this fixed by #6373?

**Comment by kdoh** [comment]
Yup!

**Comment by bpinaya** [comment]
Hi there, I'm seeing that problem still with the iframe resizer missing when having:
![image](https://user-images.githubusercontent.com/2473733/35678924-985e0bdc-072b-11e8-8a00-aef60166fda2.png)
When using an iframe size of:
<iframe width="80%" height="99%" border=0 src="">. </iframe>
I saw that the fix is implemented in the version of metabase I am using but still have that problem. Any tips?
