### ISSUE TITLE
Filter shows wrong display values when table has multiple FK columns pointing to the same column

### ISSUE THREAD

**Issue by willmarks** [metabase/metabase#65838]
### Describe the bug

Hello and thanks for taking a look at this!

We are seeing an issue where dashboard filters are showing the incorrect display value mappings when a table has multiple FK columns pointing to the same target column. The FKs are configured to use the same display values field.

Here is a simplified version of our data schema to illustrate what is happening:

Table 1: `teams`
Contains all teams
| columns |
| ------ |
| uid |
| name |

Table 2: `item_ownership`
A hierarchical ownership table with team columns that are FKs pointing to the `team.uid` with display field `team.name`.
| columns |
| ---------- |
| item |
| parent_team - FK => `team.uid` (display field `team.name`) | 
| child_team - FK => `team.uid` (display field `team.name`)

Lets say these tables have the following rows:

`teams`:
| uid | name |
| ------ | ----- |
| crm | CRM |
| sales | Sales |
| root | Root |

`item_ownership`:
| item | parent_team | child_team |
| ------ | ----- | ----- |
| 1 | crm | sales |
| 1 | root | crm |

The issue arrises when you try to filter a question built using the `item_ownership` table. 

Using the `child_team` as the filter column works fine and the filter shows correctly mapped display values:

<img width="342" height="253" alt="Image" src="https://github.com/user-attachments/assets/40571683-5b76-47f2-a391-2cfad1bf8fa4" />

But when using `parent_team` as the filter column the **display value is not mapped correctly**. I would expect it to still be "CRM - crm":

<img width="327" height="245" alt="Image" src="https://github.com/user-attachments/assets/03accd54-2062-43fa-ba94-0fb0d98c200d" />

And looking at the responses coming from `/dashboard/:dashId/params/:paramId/values` I can see the mismatch there as well:
```json
{
    "values": [
        [
            "crm",
            "Sales"
        ]
    ]
}
```

### To Reproduce

1. Create and populate tables as illustrated above
4. Create a question using the table that is not the FK target
5. Add a filter to the dashboard and attempt to filter the question using the first of the two FK columns.
6. If the mapping looked correct, attempt to filter the question using the second of the two FK columns.
7. One of the columns should have resulted in the incorrect mapping.
### Expected behavior

The FK display field value should be correctly mapped for all FK columns even when they are pointed to the same target column.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "duckdb"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-11-12",
      "tag": "v56",
      "hash": "ebc3907"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-LTS",
    "os.name": "Linux",
    "os.version": "6.1.155",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```

### Severity

blocking an upgrade

**Comment by lbrdnk** [comment]
Potentially fixed by [https://github.com/metabase/metabase/pull/65841](https://github.com/metabase/metabase/pull/65841)

**Comment by eliotmetabase** [comment]
@lbrdnk could you try to repro this now that your fix is merged?

**Comment by deniskaber** [comment]
I reproduced the issue. It still exists in the latest master.
