### ISSUE TITLE
webpack build error 

### ISSUE THREAD

**Issue by Kuchitama** [metabase/metabase#6677]
### Bugs
I got errors when I run `yarn run build` or any other commands.
The error is last part of this description.

- Your browser and the version: ---
- Your operating system: OS X 10
- Your databases: ---
- Metabase version: v0.28.0-snapshot(582d42d83d67e2a6699eb14b5366144cbcd86724)
- Metabase hosting environment: ---
- Metabase internal database: ---

- *Repeatable steps to reproduce the issue*

1. checkout `582d42d83d67e2a6699eb14b5366144cbcd86724` (current master)
2. build front end `yarn run buid`
3. failed the command with below error

#### error message

```
ERROR in ./admin/settings/components/SettingsSingleSignOnForm.jsx

/Users/k2/ProgramProjects/clojure/metabase/frontend/src/metabase/admin/settings/components/SettingsS
ingleSignOnForm.jsx
  3:19  warning  '/Users/k2/ProgramProjects/clojure/metabase/node_modules/c-3po/dist/index.js' impor
ted multiple times  import/no-duplicates
  6:10  error    't' is already defined
                    no-redeclare
  6:23  warning  '/Users/k2/ProgramProjects/clojure/metabase/node_modules/c-3po/dist/index.js' impor
ted multiple times  import/no-duplicates

✖ 3 problems (1 error, 2 warnings)

 @ ./admin/settings/containers/SettingsEditorApp.jsx 69:32-85
 @ ./routes.jsx
 @ ./app-main.js

...
```

**Comment by Kuchitama** [comment]
This problem is fixed in https://github.com/metabase/metabase/pull/6675

**Comment by bpinaya** [comment]
Just cloned the repo to get latest results, I am still having the same problem, this is the error log:

```
WARNING in ./frontend/src/metabase/admin/people/containers/PeopleListingApp.jsx             
                                                                                            
/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/people/containers/PeopleListingApp.jsx                                                                                
  4:10  warning  'Link' is defined but never used  no-unused-vars                           
                                                                                            
✖ 1 problem (0 errors, 1 warning)                                                           
                                                                                            
 @ ./frontend/src/metabase/routes.jsx 301:24-88                                             
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx

/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx
  3:19  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates
  6:10  error    't' is already defined                                                                             no-redeclare
  6:23  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates

✖ 3 problems (1 error, 2 warnings)

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 89:32-85
 @ ./frontend/src/metabase/routes.jsx
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx

/home/bpinaya/Documents/metabase/frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
   3:19  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates
  14:10  error    't' is already defined                                                                             no-redeclare
  14:23  warning  '/home/bpinaya/Documents/metabase/node_modules/c-3po/dist/index.js' imported multiple times  import/no-duplicates

✖ 3 problems (1 error, 2 warnings)

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 111:17-40                                                                                                     
 @ ./frontend/src/metabase/routes.jsx                                                                                                                                                    
 @ ./frontend/src/metabase/app-main.js                                                                                                                                                   
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js                                                                                          
                                                                                                                                                                                         
ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx                                                                                                         
Module build failed: Duplicate declaration "t"                                                                                                                                           
                                                                                                                                                                                         
  12 | import cx from "classnames";                                                                                                                                                      
  13 | import _ from "underscore";                                                                                                                                                       
> 14 | import { t, jt } from "c-3po";                                                                                                                                                    
     |          ^                                                                                                                                                                        
  15 |                                                                                                                                                                                   
  16 | export default class SettingsSlackForm extends Component {                                                                                                                        
  17 |                                                                                                                                                                                   
                                                                                                                                                                                         
 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 73:25-71                                                                                                      
 @ ./frontend/src/metabase/routes.jsx                                                                                                                                                    
 @ ./frontend/src/metabase/app-main.js                                                                                                                                                   
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js                                                                                          
                                                                                                                                                                                         
ERROR in ./frontend/src/metabase/admin/settings/selectors.js                                                                                                                             
Module build failed: Duplicate declaration "t"                                                                                                                                           
                                                                                                                                                                                         
  17 |                                                                                                                                                                                   
  18 | import { UtilApi } from "metabase/services";                                         
> 19 | import { t } from "c-3po";             
     |          ^                             
  20 |                                        
  21 | const SECTIONS = [                     
  22 |     {

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 111:17-40
 @ ./frontend/src/metabase/routes.jsx
 @ ./frontend/src/metabase/app-main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js

ERROR in ./frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx     
Module build failed: Duplicate declaration "t"                                              

  4 | import cx from "classnames";            
  5 | import _ from "underscore";             
> 6 | import { t, jt } from "c-3po";          
    |          ^       
  7 |                  
  8 | import Breadcrumbs from "metabase/components/Breadcrumbs.jsx";                        
  9 | import Input from "metabase/components/Input.jsx";                                    

 @ ./frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx 89:32-85         
 @ ./frontend/src/metabase/routes.jsx         
 @ ./frontend/src/metabase/app-main.js        
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app-main.js
Child html-webpack-plugin for "../../index.html":                                           
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
Child html-webpack-plugin for "../../public.html":                                          
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
Child html-webpack-plugin for "../../embed.html":                                           
     1 asset           
    [../../../node_modules/html-webpack-plugin/lib/loader.js!../../../resources/frontend_client/index_template.html] ./node_modules/html-webpack-plugin/lib/loader.js!./resources/frontend_client/index_template.html 4.39 kB {0} [built]
    [../../../node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [../../../node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
webpack: Failed to compile.
```

**Comment by Kuchitama** [comment]
This problem is solved by #6675
