### ISSUE TITLE
Filter columns when downloading CSV, Excel full result

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6828]
I have a big user table and want to export a specific column not all data, as data size grow, metabase goes down and I cannot export what I want. I filtered column using setting icon, but it seems that it filters out columns for displaying purposes.

Is there a way to filter columns when exporting result as CSV or Excel?

**Comment by tlrobinson** [comment]
Sadly, there's no way to do this in the UI yet. Here's an existing issue: #3992

You can hack it with the API in the browser console though:

```javascript
// find out the ids of the columns you want:
(await services.CardApi.query({ cardId: YOUR_CARD_ID })).data.cols.map(c => [c.name, c.id])
// load the card:
card = await services.CardApi.get({ cardId: YOUR_CARD_ID })
// update the query with desired field ids:
card.dataset_query.query.fields = [["field-id", FIELD_ID_1], ["field-id", FIELD_ID_2]]
// save the card
await services.CardApi.update(card)
```

More info on the query language here https://github.com/metabase/metabase/wiki/Query-Language-'98

**Comment by cqcn1991** [comment]
@tlrobinson How do I know the field ids? can you give me any example for this? Thanks!

**Comment by tlrobinson** [comment]
This has been resolved, we now set the `fields` property automatically when you hide columns, so hidden columns aren't present in downloads.

**Comment by cqcn1991** [comment]
@tlrobinson For which version of metabase? I just update metabase to 0.31.2 on heroku, but the problem persists....

Maybe we are not talking about the same problem?

My question is I can hide many columns when displaying them in tables as in 

![default](https://user-images.githubusercontent.com/2425141/50040114-53972280-0078-11e9-8ca6-56b7a97a81ed.png)

but when I click download as csv 

![default](https://user-images.githubusercontent.com/2425141/50040116-6873b600-0078-11e9-9c7f-925fe5bc9a2d.png)

the columns I hide are still downloaded.

Should I open another issue for this?

**Comment by tlrobinson** [comment]
@cqcn1991 There are two caveats:

1. this doesn't work for SQL questions, you'll have to edit the question to remove the columns
2. it doesn't apply to existing questions. if you modify the columns and close the settings it will then apply

Is either of those the case for that question?

**Comment by joe-at-startupmedia** [comment]
@tlrobinson I have a similar issue. I am using metabase v35 and the question is derived from a fact table. so it's not a dynamic question nor it it sql. my specific issue is that the column headers are not sorted as they are by the "Visible Fields" sorting configuration. Instead the seem to be alphabetically sorted.
