### ISSUE TITLE
Invalid parameters on embedding dashboards

### ISSUE THREAD

**Issue by carlessebastian** [metabase/metabase#7212]
Error on 0.28.2 and 0.28.3. Working on 0.28.0

From metabase log on sharing embedded question:
03-27 14:00:48 ERROR metabase.middleware :: GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjQ0fSwicGFyYW1zIjp7InJlcG9ydF9pZCI6IjQ2OCJ9LCJpYXQiOjE1MjIxNTIwNDgsIl9lbWJlZGRpbmdfcGFyYW1zIjp7InJlcG9ydF9pZCI6ImxvY2tlZCJ9fQ.HkwavTkmhPcKdoEYh09j2brlNQ6-_lqjQD7Cf2pWGbQ/dashcard/546/card/368 500 (26 ms) (4 DB calls).
{:message "Invalid param: ",
 :type java.lang.Exception,
 :stacktrace
 ["api.public$fn__40262$resolve_params__40267$fn__40268$iter__40269__40273$fn__40274$fn__40275.invoke(public.clj:131)"
  "api.public$fn__40262$resolve_params__40267$fn__40268$iter__40269__40273$fn__40274.invoke(public.clj:127)"
  "api.public$fn__40262$resolve_params__40267.invoke(public.clj:123)"
  "api.public$public_dashcard_results.invokeStatic(public.clj:147)"
  "api.public$public_dashcard_results.doInvoke(public.clj:135)"
  "api.embed$dashcard_results.invokeStatic(embed.clj:239)"
  "api.embed$dashcard_results.doInvoke(embed.clj:230)"
  "api.preview_embed$fn__46042$fn__46043.invoke(preview_embed.clj:50)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.preview_embed$fn__46042.invokeStatic(preview_embed.clj:46)"
  "api.preview_embed$fn__46042.invoke(preview_embed.clj:46)"
  "middleware$enforce_authentication$fn__37744.invoke(middleware.clj:117)"
  "api.routes$fn__46824.invokeStatic(routes.clj:78)"
  "api.routes$fn__46824.invoke(routes.clj:78)"
  "routes$fn__46887$fn__46888.doInvoke(routes.clj:106)"
  "routes$fn__46887.invokeStatic(routes.clj:101)"
  "routes$fn__46887.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__37843$fn__37845.invoke(middleware.clj:347)"
  "middleware$log_api_call$fn__37843.invoke(middleware.clj:346)"
  "middleware$add_security_headers$fn__37793.invoke(middleware.clj:249)"
  "core$wrap_streamed_json_response$fn__52072.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__37748.invoke(middleware.clj:138)"
  "middleware$maybe_set_site_url$fn__37797.invoke(middleware.clj:273)"]}

From metabase log on calling embedded question: 
03-27 13:52:24 DEBUG metabase.middleware :: GET /api/embed/dashboard/eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjQ3fSwicGFyYW1zIjp7InJlcG9ydF9pZCI6IjQ2NyJ9fQ.f4GMAmmYIT7P1sEEriXgtugZdMbX1e7TtVEfDbqLzq4/dashcard/552/card/397 400 (14 ms) (6 DB calls).
"Invalid param: "

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by briankalbster** [comment]
Mar 27 21:15:07 ERROR metabase.middleware :: GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjh9LCJwYXJhbXMiOnsiaWQiOiIyIn0sImlhdCI6MTUyMjE4NTMwNywiX2VtYmVkZGluZ19wYXJhbXMiOnsiaWQiOiJsb2NrZWQifX0.8iRAkdAOLzivvoIbr7PrdyO9GtdBDckFrIrIyWrm-Gs/dashcard/67/card/43 500 (7 ms) (4 DB calls).
{:message "Invalid param: ",
:type java.lang.Exception,
:stacktrace
["api.public$fn__40262$resolve_params__40267$fn__40268$iter__40269__40273$fn__40274$fn__40275.invoke(public.clj:131)"
"api.public$fn__40262$resolve_params__40267$fn__40268$iter__40269__40273$fn__40274.invoke(public.clj:127)"
"api.public$fn__40262$resolve_params__40267.invoke(public.clj:123)"
"api.public$public_dashcard_results.invokeStatic(public.clj:147)"
"api.public$public_dashcard_results.doInvoke(public.clj:135)"
"api.embed$dashcard_results.invokeStatic(embed.clj:239)"
"api.embed$dashcard_results.doInvoke(embed.clj:230)"
"api.preview_embed$fn__46042$fn__46043.invoke(preview_embed.clj:50)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
"api.preview_embed$fn__46042.invokeStatic(preview_embed.clj:46)"
"api.preview_embed$fn__46042.invoke(preview_embed.clj:46)"
"middleware$enforce_authentication$fn__37744.invoke(middleware.clj:117)"
"api.routes$fn__46824.invokeStatic(routes.clj:78)"
"api.routes$fn__46824.invoke(routes.clj:78)"
"routes$fn__46887$fn__46888.doInvoke(routes.clj:106)"
"routes$fn__46887.invokeStatic(routes.clj:101)"
"routes$fn__46887.invoke(routes.clj:101)"
"middleware$log_api_call$fn__37843$fn__37845.invoke(middleware.clj:347)"
"middleware$log_api_call$fn__37843.invoke(middleware.clj:346)"
"middleware$add_security_headers$fn__37793.invoke(middleware.clj:249)"
"core$wrap_streamed_json_response$fn__52072.invoke(core.clj:67)"
"middleware$bind_current_user$fn__37748.invoke(middleware.clj:138)"
"middleware$maybe_set_site_url$fn__37797.invoke(middleware.clj:273)"]}

**Comment by briankalbster** [comment]
Verified that this worked in 0.28.1. I had to rollback my environment to have embedding work properly

**Comment by salsakran** [comment]
@carlessebastian @briankalbster This is fixed and out in 0.28.4

Let us know if you see it on upgrade!

**Comment by JomMarn** [comment]
I just update from 0.28.1 to 0.28.4 and still have this error.

Would it help if I say I use non English character as parameter's name? Well, it works fine in normal dashboard, though.
![image](https://user-images.githubusercontent.com/11479764/38131507-926346d8-3431-11e8-9101-87ce79ddb475.png)

The logs:

Mar 30 15:18:42 WARN metabase.middleware :: Input to resolve-params does not match schema: 

 [nil (named [{:slug missing-required-key}] query-params)] 


Mar 30 15:18:42 WARN metabase.middleware :: Input to resolve-params does not match schema: 

 [nil (named [{:slug missing-required-key}] query-params)] 


Mar 30 15:18:42 DEBUG metabase.middleware :: GET /api/public/dashboard/2d9f3562-6bf3-4f31-aa90-095ccab4e746/card/5 400 (4 ms) (2 DB calls).
"An error occurred."

Mar 30 15:18:42 INFO metabase.api.card :: Question's average execution duration is 333 ms; using 'magic' TTL of 3 seconds 
Mar 30 15:18:42 DEBUG metabase.middleware :: GET /api/public/dashboard/2d9f3562-6bf3-4f31-aa90-095ccab4e746/card/6 400 (6 ms) (2 DB calls).
"An error occurred."

Mar 30 15:18:42 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Mar 30 15:18:43 INFO metabase.query-processor.middleware.cache :: Query took 262 ms to run; miminum for cache eligibility is 60000 ms
Mar 30 15:18:43 DEBUG metabase.middleware :: GET /api/public/dashboard/2d9f3562-6bf3-4f31-aa90-095ccab4e746/card/8 200 (447 ms) (17 DB calls). Jetty threads: 8/50 (6 busy, 3 idle, 0 queued)

**Comment by phpcodecrafting** [comment]
This is fixed for dashboards embedded using the JWT method. However, it is still broken for dashboards shared using the public share url.

For those links this time the error is what @JomMarn reported above, ie,

```
WARN metabase.middleware :: Input to resolve-params does not match schema:

[nil (named [{:slug missing-required-key}] query-params)]
```

**Comment by camsaul** [comment]
Repro'ed

**Comment by camsaul** [comment]
Fixed by #7248
