### ISSUE TITLE
Automatic Dashboards pre-0.29 Cleanup

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7414]
# Open
- [x] Wrong title for segment dashboards
- [x] GA Dashboards should include "table name" in the event of multiple properties
- [x] Ad Hoc questions shouldn't have the same titles as tables

# Later Versions
- [ ] Load yaml in a safe manner
- [ ] i18N extraction from YAML
- [ ] Move filter humanization to frontend  

# Verify

# Done
- [x] Doing a drill-down x-ray from the query builder on a query that contains an Is not or Is not equal to filter results in this error
- [x] Too aggressive entity type heuristics
- [x] MBQL warnings due to bare field ids instead of `[:field-id X]`
- [x] GA drill-down is broken due to duplicate filter clauses in the cell query 
- [x] Going to /explore from the add-db-success modal in the Admin Panel, the UI for /explore hangs indefinitely
- [x] Drill-through is ignoring filters applied (see below) [tom]
- [x] Can't save GA dashboards due to  #7399 
- [x] X-Raying a nested query fails (see below)
- [x] Can't map filters to cards in a saved automatically generated dashboard
- [x] clicking into a automatic dashboard is broken  when filters are applied

**Comment by salsakran** [comment]
X-raying a nested query

![nested-query-x-ray](https://user-images.githubusercontent.com/107439/39151422-0ce11a9a-46fa-11e8-9cc4-b52ea0178dcc.gif)

**Comment by salsakran** [comment]
It seems that drill-through x-rays don’t pay attention to applied dashboard filters. If I have a chart that I filter by state (e.g. CA or CO), and then x-ray one of the bars, the x-ray ignores my state filter. 

![dashboard-filters](https://user-images.githubusercontent.com/107439/39151458-21a7abe2-46fa-11e8-84c8-8eb30c95d1b3.gif)

**Comment by salsakran** [comment]
If I use one of the filter widgets on an x-ray, I can’t click through on any charts while the filter is active.

Getting this JS console error when I click on the title of any card:
```Card.js:282 Uncaught (in promise) TypeError: Cannot assign to read only property ‘id’ of object ‘#<Object>’
   at questionUrlWithParameters (Card.js:282)
   at dashboard.js:772
   at _callee$ (redux.js:19)
   at tryCatch (runtime.js:65)
   at Generator.invoke [as _invoke] (runtime.js:303)
   at Generator.prototype.(:3000/auto/dashboard/table/anonymous function) [as next] (http://localhost:8080/app/dist/vendor.hot.bundle.js?d86be7891394ffb81c9a:3454:21)
   at step (redux.js:13)
   at redux.js:13
   at new Promise (<anonymous>)
   at redux.js:13
```
![filter-bug](https://user-images.githubusercontent.com/107439/39151480-31c6b81a-46fa-11e8-8af8-aff7ad8837db.gif)

**Comment by salsakran** [comment]
Getting an error on query execution of 
```
04-23 13:33:59 DEBUG metabase.middleware :: GET /api/tiles/4/11/6/18/23/1/0/ 200 (203 ms) (10 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
04-23 13:33:59 WARN metabase.query-processor :: Query failure: Invalid query: Field 18 belongs to table 3. Since 3 is not the source table, it must be wrapped in a fk-> form, e.g. [fk-> 9 18].
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$eval43069$process_query_and_save_execution_BANG___43074$fn__43075.invoke(query_processor.clj:281)"
 "query_processor$eval43069$process_query_and_save_execution_BANG___43074.invoke(query_processor.clj:267)"
 "api.tiles$fn__55108$fn__55109.invoke(tiles.clj:134)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.tiles$fn__55108.invokeStatic(tiles.clj:113)"
 "api.tiles$fn__55108.invoke(tiles.clj:113)"
 "middleware$enforce_authentication$fn__44571.invoke(middleware.clj:117)"
 "api.routes$fn__57333.invokeStatic(routes.clj:90)"
 "api.routes$fn__57333.invoke(routes.clj:90)"
 "routes$fn__57378$fn__57379.doInvoke(routes.clj:108)"
 "routes$fn__57378.invokeStatic(routes.clj:103)"
 "routes$fn__57378.invoke(routes.clj:103)"
 "middleware$log_api_call$fn__44684$fn__44686.invoke(middleware.clj:347)"
 "middleware$log_api_call$fn__44684.invoke(middleware.clj:346)"
 "middleware$add_security_headers$fn__44620.invoke(middleware.clj:249)"
 "core$wrap_streamed_json_response$fn__58195.invoke(core.clj:67)"
 "middleware$bind_current_user$fn__44575.invoke(middleware.clj:138)"
 "middleware$maybe_set_site_url$fn__44624.invoke(middleware.clj:273)"]
```
for applying the "sales by coordinates" heuristic
```
 - CountByCoords:
      title: Sales by coordinates
      metrics: TotalOrders
      dimensions:
        - Long
        - Lat
      visualization: map
      score: 80
      height: 10
      width: 11
      group: Geographical
```
once I remove the binning.
@sbelak ?

**Comment by mazameli** [comment]
After connecting a new db with ~30 tables, the UI of /explore hangs even after sync and analysis appears to be done. Going to the data reference and x-raying one of the tables directly works fine, and even hitting /explore on subsequent occasions seems to work fine as well.

I took a screen recording that’s almost 2 minutes long and which shows js and server logs: https://drive.google.com/open?id=1m2GmLgPENlywxCYUO9qmP5SAcs2doT3y

**Comment by sbelak** [comment]
Re:"sales by coordinates" looks like an `:inside` clause gets added to the query above (if no binning) by the front end before it hits the /api/dataset and that doesn't take fks into account. See #7416

**Comment by mazameli** [comment]
Mentioned this one the other day, but if I save an x-ray and then try to add a dashboard filter to my new dashboard, I can't map the new filter to any of the cards, and saving the dashboard fails:

![x-ray-dash-filters](https://user-images.githubusercontent.com/2223916/39154603-b1147536-4703-11e8-93cf-f2bb79f7aafd.gif)

If I try just editing the new dashboard by doing simple stuff like moving/resizing cards, everything's fine. But if I then try to edit one of the filters that came from the x-ray, things get really screwy, like cards "sticking" to the cursor:

![weirdness](https://user-images.githubusercontent.com/2223916/39154633-d5c97fb6-4703-11e8-8bc8-805cfcf9a6a7.gif)

**Comment by mazameli** [comment]
Doing a drill-down x-ray from the query builder on a query that contains an `Is not` or `Is not equal to` filter results in this error (all other filters I tried seem to work fine).

`No method in multimethod 'humanize-filter-value' for dispatch value: :!=`

![is-not-filter](https://user-images.githubusercontent.com/2223916/39156433-f03ec782-470a-11e8-9a42-ff898b7bb75c.gif)

**Comment by tlrobinson** [comment]
"X-Raying a nested query fails (see below)" fixed in f23bf78

"clicking into a automatic dashboard is broken when filters are applied" fixed in 8a1444f

**Comment by sbelak** [comment]
"Can't map filters to cards in a saved automatically generated dashboard" fixed in 79ae7b0

**Comment by mazameli** [comment]
X-ray nested queries seems to be working now (🎉), but when x-raying a cell, the filter labels on resulting x-rays seems to lose the field information like its name and possibly its type:

**Category field:**

![category_field_label](https://user-images.githubusercontent.com/2223916/39219049-0c3b280e-47dd-11e8-8824-5df9cfb2c870.gif)

**Date field:**

![time_filed_filter_label](https://user-images.githubusercontent.com/2223916/39219052-0ed474e4-47dd-11e8-99da-ab7e4d24e68b.gif)

No JS errors of note, but the server log says:
`
04-24 16:33:25 WARN metabase.query-processor :: Query failure: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'dept_no' in where clause is ambiguous
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:211)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:204)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:244)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:237)"
 "query_processor$eval42210$process_query_and_save_execution_BANG___42215$fn__42216.invoke(query_processor.clj:283)"
 "query_processor$eval42210$process_query_and_save_execution_BANG___42215.invoke(query_processor.clj:269)"
 "query_processor$eval42234$process_query_and_save_with_max_BANG___42239$fn__42240.invoke(query_processor.clj:304)"
 "query_processor$eval42234$process_query_and_save_with_max_BANG___42239.invoke(query_processor.clj:300)"
 "api.dataset$fn__44059$fn__44062$fn__44063.invoke(dataset.clj:50)"
 "api.common$eval24069$invoke_thunk_with_keepalive__24074$fn__24075$fn__24076.invoke(common.clj:404)"]
`

**Comment by mazameli** [comment]
I'm still experiencing the problem where when going to /explore from the add-db-success modal in the Admin Panel, the UI for /explore hangs indefinitely. But I've come up with reliable steps to reproduce it:

- If you click the button to go to /explore before sync and analysis are done, the UI gets stuck
- But if you wait until the server logs say that sync analysis are done and _then_ hit the button, /explore loads up instantly.

**Comment by salsakran** [comment]
Another issue with the card x-ray titles is that if there are filters on the card, those filters aren't carried over. The title should really just use the question title rather than the title.

**Comment by salsakran** [comment]
Also I get errors if I go from a saved question -> autodash -> a linked "sub dashboard"
eg http://localhost:3000/auto/dashboard/question/20/TransactionTable/BySource?STATE=AK&STATE=AZ&STATE=CT returns a 404

Here question 20 is a gui question against the orders table of the sample dataset.

**Comment by sbelak** [comment]
> Also I get errors if I go from a saved question -> autodash -> a linked "sub dashboard"
eg http://localhost:3000/auto/dashboard/question/20/TransactionTable/BySource?STATE=AK&STATE=AZ&STATE=CT returns a 404
fixed via #7454

**Comment by sbelak** [comment]
"Too aggressive entity type heuristics" fixed in #7467

**Comment by salsakran** [comment]
seeing some errors on filtered questions -- eg x-raying
<img width="1298" alt="screen shot 2018-04-26 at 4 56 20 pm" src="https://user-images.githubusercontent.com/107439/39337629-d007ad7a-4972-11e8-8c61-afccd26f160e.png">

throws 
```
04-26 16:55:39 ERROR metabase.middleware :: GET /api/automagic-dashboards/adhoc/eyJkYXRhYmFzZSI6MSwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlX3RhYmxlIjoyLCJmaWx0ZXIiOlsiQU5EIixbIiE9IixbImZrLT4iLDExLDZdLCJEb29oaWNrZXkiXV19fQ== 500 (111 ms) (12 DB calls).
{:message "clj_time/format$parse$iter__738__742",
 :type java.lang.NoClassDefFoundError,
 :stacktrace
 ["automagic_dashboards.core$optimal_datetime_resolution.invokeStatic(core.clj:91)"
  "automagic_dashboards.core$optimal_datetime_resolution.invoke(core.clj:89)"
  "automagic_dashboards.core$eval47979$fn__47981.invoke(core.clj:114)"
  "automagic_dashboards.core$build_query$fn__48112.invoke(core.clj:307)"
  "automagic_dashboards.core$build_query.invokeStatic(core.clj:303)"
  "automagic_dashboards.core$build_query.invoke(core.clj:301)"
  "automagic_dashboards.core$card_candidates$fn__48138.invoke(core.clj:397)"
  "automagic_dashboards.core$make_cards$fn__48198.invoke(core.clj:497)"
  "automagic_dashboards.core$make_cards.invokeStatic(core.clj:501)"
  "automagic_dashboards.core$make_cards.invoke(core.clj:492)"
  "automagic_dashboards.core$apply_rule.invokeStatic(core.clj:521)"
  "automagic_dashboards.core$apply_rule.invoke(core.clj:514)"
  "automagic_dashboards.core$automagic_dashboard.invokeStatic(core.clj:578)"
  "automagic_dashboards.core$automagic_dashboard.invoke(core.clj:573)"
  "automagic_dashboards.core$eval48255$fn__48257.invoke(core.clj:660)"
  "api.automagic_dashboards$fn__65067$fn__65068.invoke(automagic_dashboards.clj:171)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.automagic_dashboards$fn__65067.invokeStatic(automagic_dashboards.clj:163)"
  "api.automagic_dashboards$fn__65067.invoke(automagic_dashboards.clj:163)"
  "middleware$enforce_authentication$fn__44580.invoke(middleware.clj:118)"
  "api.routes$fn__65127.invokeStatic(routes.clj:63)"
  "api.routes$fn__65127.invoke(routes.clj:63)"
  "routes$fn__65234$fn__65235.doInvoke(routes.clj:108)"
  "routes$fn__65234.invokeStatic(routes.clj:103)"
  "routes$fn__65234.invoke(routes.clj:103)"
  "middleware$log_api_call$fn__44693$fn__44695.invoke(middleware.clj:349)"
  "middleware$log_api_call$fn__44693.invoke(middleware.clj:348)"
  "middleware$add_security_headers$fn__44629.invoke(middleware.clj:251)"
  "core$wrap_streamed_json_response$fn__65262.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__44584.invoke(middleware.clj:139)"
  "middleware$maybe_set_site_url$fn__44633.invoke(middleware.clj:275)"]}
```

**Comment by salsakran** [comment]
closing as we've pushed out 0.29 and there are PRs in flight for a number of the remaining issues.
