### ISSUE TITLE
MSSQL - saved question with ordering can't be used as data source for another question

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7456]
When using a Saved Question as Question data source, MSSQL spits the dummy if the Saved Question has sorting in it. I assume this is because the Saved Question query is being used as a sub-query in the SELECT.

- Your databases: MSSQL
- Metabase version: 0.28.5

1. Create question using MSSQL as database. Question output should be a Count of rows, displayed as a table.
2. Apply ordering to the Count column in your table output. Save the question.
3. Create a new question using previous question as the source.
4. Attempt to 'Get Answer'. Query fails as MSSQL does not permit ordering within nested SELECTs

This is a DB specific requirement for SQL server. It won't allow ordering in Views, or nested SELECTs (ordering is applied to the final output).

**Comment by dfx413** [comment]
For MSSQL this could actually be solved quite easily, look at the error report:

`The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.`

That basically means the query should look like "SELECT TOP 100 PERCENT [whatever] FROM [whatever]

**Comment by flamber** [comment]
I'm pretty sure this was fixed by #8981, but has a side-effect detailed here:
https://discourse.metabase.com/t/when-update-to-0-32-1-with-data-view-problem-on-sql-server/5811

**Comment by dfx413** [comment]
Hi @flamber, 
I just tried it and the problem is still there. 
More specifically when I try to use 2 saved questions (both of them use the ORDER BY clause) and join them in the query builder, the generated SQL applies the "SELECT TOP [xyz]" to the first saved question but not to the second one. 

That means I end up with the classic `The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.` error.

Also I read the thread that you referenced in your previous post and I am not quite sure what that means. Specifically this: https://github.com/metabase/metabase/blob/b913f5f70d8103d80255ccfcc2e09ae502c08220/src/metabase/driver/sqlserver.clj#L159-L169
It states that in order to circumvent the the ORDER BY a max-results limit is applied to any non-top level query. If I understand it correctly, that affects the number of rows the subquery returns. Why not just use `SELECT TOP 100 PERCENT` as it never alters the query result and solves the problem just fine?

**Comment by flamber** [comment]
@dfx413 
Okay, joining data is a new thing since 0.33, so that's probably a different issue, but you've already created #10854, so that will be taken care of in that issue.
As for the original issue, it's fixed - but there are some side-effects - also noted in #9940

**Comment by dfx413** [comment]
@flamber Yes, I have read that. That why I said I am not sure I really understand why there must be these side effects. Correct me if I am wrong but does this mean that you are limiting the row count returned from subquery, which then leads to unexpected results?

**Comment by flamber** [comment]
@dfx413 Yes.

**Comment by dfx413** [comment]
Is there no other way around it?

**Comment by mazameli** [comment]
Seems that this issue should be closed, but ongoing, related issues have been noted.
