### ISSUE TITLE
In Collections 2.0, after I create a new collection I should be able to see it without hard refreshing

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7495]
I have to hit refresh before a new collection shows up. 

Also, I think this is already the behavior, but I think we should keep the user in the current collection after creating a new one in it, rather than navigating them inside the new collection after creating it, because after you make a folder you typically want to put things in the current parent folder into the new one.

![new-collection](https://user-images.githubusercontent.com/2223916/39443685-4088a172-4c6a-11e8-8005-c137797b609e.gif)

**Comment by tlrobinson** [comment]
@mazameli @kdoh This is fixed in `add-collection-id-to-dashboards-and-pulses`

**Comment by mazameli** [comment]
This is not fixed: it redirects you to the new collection, but when you go back to the home page, the collection is not present unless you hard refresh. 

Additionally, the redirect behavior should be the same as it is in master: after I create a new collection, I should be redirected to the collection's _parent_ collection (i.e. root for now until we have nested collections), so that I can see the collection in the list, and so that I can more immediately move items into the new collection.

Was the fix for this supposed to have been in `b0d809c`?

![new-collection](https://user-images.githubusercontent.com/2223916/39828763-151cfd54-5371-11e8-8c73-80157807ebc3.gif)

**Comment by mazameli** [comment]
This is now fixed, so I'll close it, but I'll open another issue for the incorrect behavior where it's redirecting you to go to the new collection after creating it (it should keep you in the parent collection).
