### ISSUE TITLE
Dashboard filters no longer working after 0.29.0 update

### ISSUE THREAD

**Issue by ryan-tangocard** [metabase/metabase#7543]
After upgrading our Metabase from 0.28.1 to 0.29.0 existing dashboard category filters no longer show a drop-down list of values. 

- Your browser and the version: Chrome Version 66.0.3359.139
- Your operating system: Windows 10
- Your databases: Redshift
- Metabase version: 0.29.0
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

Steps to recreate issue -

After upgrading, go to a dashboard with a filter and click on the Category filter. There is no longer drop-down values and typing in the field doesn't do anything.

I have attempted to resolve the issue by -

- Removing and adding the filter
- Resyncing the database schema and Re-scan field values through the Database management screen.
- Resync the individual fields through the Data Model section.

Upon re-sycn the values apear back in the drop-down, but after refreshing the page or waiting several minutes and going back to the dashboard the problem returns.

**Comment by mazameli** [comment]
A few follow-up questions for you, Ryan:

1. Are you seeing any errors in the JavaScript console in your browser, or in the server logs?
2. If you go to the Admin Panel > Data Model, then go to the field you're trying to filter on and click the gear icon to the far right of that field, you should see a field settings screen. If you scroll to the part of that page titled "filtering on this field," what is that drop down set to? If you manually change it to "a list of values," does that fix things?
3. What is the metadata type and underlying data type of the field(s) you connected to that dashboard filter? 
4. Does this problem happen for you if you connect a dashboard filter to a different field? 
5. Is this happening with Location or ID dashboard filter widgets as well?
6. What happens if you try to use that field in a filter in the graphical query builder (i.e. in a new custom question)?

**Comment by ryan-tangocard** [comment]
1. No errors in JS console or Logs (while attempting to use the broken filter)
2. These fields were defaulted to "a list of values" and when I re-select when selecting the "a list of values" from field settings page. it does temporarily resolve the issue, but after waiting a few minutes and loading the page, the drop down stops working again. During this operation I see the following warning in my browser console - Missing id: > {values: f} metadata.js:228. Additionally, for the short time it does work  I am seeing the following error in my browser - Uncaught TypeError: _this2._input.focus is not a function at ListSearchField.jsx:31
3. Type is Category under the field settings section.  The data type in the DB is varchar(7200). 
4. When adding a new filter to a dashboard I get more ListSearchField.jsx:31 errors. I am still able to add the filter and it seems to work. I did notice through adding and removing filters that when I am able to get the old filter to work, it's showing the old drop-down filter UI. 
5. I haven't used Location or ID as a filter.
6. The filter works fine in building questions.

**Comment by Poggen** [comment]
Step 2 is the exact error i get in #7542.

**Comment by camsaul** [comment]
Fixed by #7556

**Comment by ryan-tangocard** [comment]
Updated to 0.29.2 and I am still having issues with the filters on dashboards.

Still seeing the following error when  -
Uncaught TypeError: _this2._input.focus is not a function at ListSearchField.jsx:31

I also see this error when creating a custom question as soon as I hit Select a table.

Upon doing some additional testing, I am finding that if I keep my dashboard filter down to one tables questions it doesn't throw an error and works as expected. As soon as I add the filter to a question that is against another table with the same value it turns the filter back to the old look and throws an error and will stop working. I have tried going through all of the tables and ensuring that the value is set to list, but it's still not working.
