### ISSUE TITLE
Metabase becomes inoperable, leaves too many hanging DB connections

### ISSUE THREAD

**Issue by joaoferrao** [metabase/metabase#8679]
### Bugs

- Your browser and the version: tested in chrome, firefox, 
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: AWS RDS PostgreSQL
- Metabase version: 0.28.0, 0.29, 0.30.0, 0.31.0RC
- Metabase hosting environment: AWS ECS
- Metabase internal database: AWS RDS PostgreSQL

Basically at some point, everyday, the queries don't return anything due to the amount of hanging connections. Status goes from "doing science" to "took too much time".

Would really appreciate some pointers or a way to tell met abase to kill DB Connections. It becomes inoperable every day - I suspect due to the amount of hanging/idle connections to the DB. As soon as I restart the container the connections to the RDS drop to 0 and the queries work again immediately.

Below what happened, before 9h30 is when I restarted the container.

![image](https://user-images.githubusercontent.com/28150182/46854733-1c9b5b00-ce02-11e8-95cf-f002dd7e990a.png)

**Comment by senior** [comment]
It would be good to test this out on the most recent version of Metabase `0.30.4` as there have been several fixes recently that I think would help prevent this issue. Although https://github.com/metabase/metabase/issues/8312 doesn't specifically say it was leaving database connections open, I think it's pretty likely that it would.

If you are still seeing this issue after upgrading, what would be most useful is a thread dump of the Metabase process when you observe this connection issue. A thread dump will capture what each thread in the JVM is doing at that exact moment. I'm not sure how you have deployment Metabase, but the easiest way to get a thread dump is to find out the PID of your Metabase process and run `jstack` on that PID. You can then redirect the output of that command to a file, i.e. `jstack 123 >> thread-dump.txt`. If you would like you can email it to me directly, my address is my first name at metabase.com.

**Comment by joaoferrao** [comment]
@senior I'm seeing this issue happening even in the 31.0 RC. Isn't it supposed to incorporate all the mentioned fix from the 30.4?

**Comment by senior** [comment]
@joaoferrao `0.31.0.RC1` hasn't been released yet. Are you building your own off of the release branch?

**Comment by senior** [comment]
@joaoferrao You should have the fixes then. What would be helpful would be figuring out what those connections are doing via the thread dump that I described [above](https://github.com/metabase/metabase/issues/8679#issuecomment-433171904).

**Comment by joaoferrao** [comment]
I'm trying to follow your instructions but the alpine dist where metabase is included doesn't include jstack apparently and I'm trying to find a way to install it without resorting to restart the production instance. suggestions?

**Comment by djbusby** [comment]
We're using release v0.32.9 and it also shows this problem; no active users of Metabase yet it has 195 open connections to my DB server (postgresql 11).  I have metabase configured to view 350 databases; pg connection max is 200; it would be nice if unused connections could be closed.

**Comment by emetselaar** [comment]
We experience the same issue with a lower amount of databases (around 30). We are thinking of putting PgBouncer in between to handle the connections.

**Comment by emetselaar** [comment]
PgBouncer did not work for us.
We are now testing with the latest RC (0.33.0-preview2). The same thing happens. It opens a lot of connections (97 of the allowed 100 on that postgres) and keeps them open for ever. This means other processes can no longer connect to that database. For example the one that inserts the data in the first place.

That proces will run into this:
`psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections`

**Comment by flamber** [comment]
@emetselaar 
I don't know if it will help or cause more problems, so please use with caution.
The 15 connections per database is a current default, but with PR #9788, it looks like you can send parameter that changes the maximum pool size of [c3p0](https://www.mchange.com/projects/c3p0/#maxPoolSize) - example 10 connections:
```
java -Dc3p0.maxPoolSize=10 -jar metabase.jar
```
You might want to look at the c3p0 section about [Managing Pool Size and Connection Age](https://www.mchange.com/projects/c3p0/#managing_pool_size), since you might be able to close idle connections.

**Comment by emetselaar** [comment]
Thanks @flamber - I will try it out tomorrow. Now that I know where to look I see that the `maxIdleTime`  is set at 3 hours, but the `idleConnectionTestPeriod` at 3 minutes is probably preventing the `maxIdleTime` to be ever hit. So the connections are never discarded?

**Comment by emetselaar** [comment]
Update: I could not get it to work so I updated the number of allowed open connections to the database.

However, I think that the inconsistency between `maxIdleTime` and `idleConnectionTestPeriod` looks like a bug. I do not understand the intention so it could be by design, but if that is the case then `maxIdleTime` does not have to be there at all right?

**Comment by rajatgl17** [comment]
Facing the same issue with AWS RDS MySQL.
@emetselaar  Were you able to resolve it anyhow?

**Comment by emetselaar** [comment]
> Facing the same issue with AWS RDS MySQL.
> @emetselaar Were you able to resolve it anyhow?

I worked around this by increasing the amount of allowed connections on the database itself. Not ideal, but for my purposes it works.

**Comment by keithbrink** [comment]
I am also encountering long running queries/connections, thought I would post them in case it's helpful:

```
 Just now
	analytics
SELECT "core_session"."created_at", "core_session"."user_id", "core_user"."is_superuser" FROM "core_session" LEFT JOIN "core_user" ON "core_session"."user_id" = "core_user"."id" WHERE ("core_user"."is_active" = TRUE AND "core_session"."id" = $1) LIMIT 1
	344737.12ms
Just now
	analytics
SHOW TRANSACTION ISOLATION LEVEL
	344736.97ms
Just now
	analytics
SELECT "core_session"."created_at", "core_session"."user_id", "core_user"."is_superuser" FROM "core_session" LEFT JOIN "core_user" ON "core_session"."user_id" = "core_user"."id" WHERE ("core_user"."is_active" = TRUE AND "core_session"."id" = $1) LIMIT 1
	344081.78ms
Just now
	analytics 
SELECT "pulse_channel"."id", "pulse_channel"."pulse_id", "pulse_channel"."schedule_type", "pulse_channel"."channel_type" FROM "pulse_channel" WHERE ("enabled" = TRUE AND ("schedule_type" = $1 OR ("schedule_type" = $2 AND "schedule_hour" = 8) OR ("schedule_type" = $3 AND "schedule_hour" = 8 AND "schedule_day" = $4) OR ("schedule_type" = $5 AND "schedule_hour" = 8 AND "schedule_frame" = $6 AND ("schedule_day" = $7 OR "schedule_day" = $8))))
	12703.728ms
```

**Comment by camsaul** [comment]
Fixed by #11832

**Comment by Mapiarz** [comment]
Hi all. I'm still experiencing the above problem. Metabase keeps taking up more and more connection slots until nothing is able to connect. Is this regression known?

**Comment by flamber** [comment]
@Mapiarz 
Please post "Diagnostic Info" from Admin > Troubleshooting, and which database you're seeing this with.
And logs from Admin > Troubleshooting > Logs.
And any process/connection stats from your database, which could be helpful.

**Comment by Mapiarz** [comment]
Here's diagonostic info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-21",
      "tag": "v1.36.6.1",
      "branch": "enterprise-release-1.36.x",
      "hash": "5695e2b"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

Here are the final moments of my psql server before becoming full unresponsive:
```
2020-10-14 02:00:14.508 UTC [31786] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_framework_api_key_apikey"."hashed_key" AS "hashed_key", "public"."rest_framework_api_key_apikey"."name" AS "name", "public"."rest_framework_api_key_apikey"."created" AS "created", "pu
blic"."rest_framework_api_key_apikey"."expiry_date" AS "expiry_date", "public"."rest_framework_api_key_apikey"."revoked" AS "revoked", "public"."rest_framework_api_key_apikey"."prefix" AS "prefix" FROM "public"."r
est_framework_api_key_apikey" LIMIT 10000
2020-10-14 02:00:14.601 UTC [31786] analysis@merged-watchdog ERROR:  permission denied for relation rest_hooks_hook
2020-10-14 02:00:14.601 UTC [31786] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_hooks_hook"."target" AS "target", "public"."rest_hooks_hook"."event" AS "event", "public"."rest_hooks_hook"."created" AS "created", "public"."rest_hooks_hook"."updated" AS "updated", 
"public"."rest_hooks_hook"."user_id" AS "user_id" FROM "public"."rest_hooks_hook" LIMIT 10000
2020-10-14 02:05:03.440 UTC [31785] analysis@merged-watchdog LOG:  could not receive data from client: Connection reset by peer
2020-10-14 02:05:03.440 UTC [31786] analysis@merged-watchdog LOG:  could not receive data from client: Connection reset by peer
2020-10-14 03:00:15.030 UTC [16489] analysis@merged-watchdog ERROR:  permission denied for relation rest_framework_api_key_apikey
2020-10-14 03:00:15.030 UTC [16489] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_framework_api_key_apikey"."hashed_key" AS "hashed_key", "public"."rest_framework_api_key_apikey"."name" AS "name", "public"."rest_framework_api_key_apikey"."created" AS "created", "pu
blic"."rest_framework_api_key_apikey"."expiry_date" AS "expiry_date", "public"."rest_framework_api_key_apikey"."revoked" AS "revoked", "public"."rest_framework_api_key_apikey"."prefix" AS "prefix" FROM "public"."r
est_framework_api_key_apikey" LIMIT 10000
2020-10-14 03:00:15.131 UTC [16489] analysis@merged-watchdog ERROR:  permission denied for relation rest_hooks_hook
2020-10-14 03:00:15.131 UTC [16489] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_hooks_hook"."target" AS "target", "public"."rest_hooks_hook"."event" AS "event", "public"."rest_hooks_hook"."created" AS "created", "public"."rest_hooks_hook"."updated" AS "updated", 
"public"."rest_hooks_hook"."user_id" AS "user_id" FROM "public"."rest_hooks_hook" LIMIT 10000
2020-10-14 03:39:50.685 UTC [18135] analysis@merged-watchdog LOG:  could not receive data from client: Connection reset by peer
2020-10-14 04:00:12.359 UTC [6674] analysis@merged-watchdog ERROR:  permission denied for relation rest_framework_api_key_apikey
2020-10-14 04:00:12.359 UTC [6674] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_framework_api_key_apikey"."hashed_key" AS "hashed_key", "public"."rest_framework_api_key_apikey"."name" AS "name", "public"."rest_framework_api_key_apikey"."created" AS "created", "pu
blic"."rest_framework_api_key_apikey"."expiry_date" AS "expiry_date", "public"."rest_framework_api_key_apikey"."revoked" AS "revoked", "public"."rest_framework_api_key_apikey"."prefix" AS "prefix" FROM "public"."r
est_framework_api_key_apikey" LIMIT 10000
2020-10-14 04:00:12.437 UTC [6674] analysis@merged-watchdog ERROR:  permission denied for relation rest_hooks_hook
2020-10-14 04:00:12.437 UTC [6674] analysis@merged-watchdog STATEMENT:  -- Metabase
        SELECT "public"."rest_hooks_hook"."target" AS "target", "public"."rest_hooks_hook"."event" AS "event", "public"."rest_hooks_hook"."created" AS "created", "public"."rest_hooks_hook"."updated" AS "updated", 
"public"."rest_hooks_hook"."user_id" AS "user_id" FROM "public"."rest_hooks_hook" LIMIT 10000
2020-10-14 04:06:28.072 UTC [6674] analysis@merged-watchdog LOG:  could not receive data from client: Connection reset by peer
2020-10-14 04:24:09.483 UTC [9994] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.501 UTC [9993] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.501 UTC [9992] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.577 UTC [9997] analysis@merged-watchdog FATAL:  sorry, too many clients already
2020-10-14 04:24:09.581 UTC [9996] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.583 UTC [9995] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.596 UTC [9998] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:09.608 UTC [9999] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.641 UTC [10007] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.650 UTC [10005] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.656 UTC [10006] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.675 UTC [10004] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.689 UTC [10003] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.691 UTC [10002] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.799 UTC [10009] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:10.801 UTC [10008] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.707 UTC [10012] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.711 UTC [10011] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.718 UTC [10010] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.750 UTC [10013] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.761 UTC [10015] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.767 UTC [10014] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.855 UTC [10017] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:11.858 UTC [10016] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.764 UTC [10018] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.772 UTC [10020] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.775 UTC [10019] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.801 UTC [10022] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.811 UTC [10023] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.816 UTC [10024] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.917 UTC [10025] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:12.919 UTC [10026] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.816 UTC [10027] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.825 UTC [10029] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.826 UTC [10028] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.869 UTC [10031] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.872 UTC [10032] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.878 UTC [10030] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.979 UTC [10033] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:13.986 UTC [10034] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.889 UTC [10035] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.893 UTC [10036] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.894 UTC [10037] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.927 UTC [10040] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.927 UTC [10038] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:14.928 UTC [10039] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:15.040 UTC [10043] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:15.042 UTC [10041] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
2020-10-14 04:24:15.946 UTC [10047] analysis@merged-watchdog FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

The metabase logs seem to only be available for the last hour or so, so I will have to wait until metabase eats up all my connections again. Is there another way @flamber ?

**Comment by flamber** [comment]
@Mapiarz You should use the support email, when using the Enterprise Edition. Also, the latest release is 1.36.7
I don't know which database you're showing logs from, but I'm guessing it's Postgres. Are you using pgbouncer or similar?
How many connections does the database allow? How many connections is Metabase configured to use?
I don't know how you're hosting Metabase, but it looks like EC2, but I don't know if you're using JAR or Docker.
The Metabase logs, should indicate if connections are open, and if they are queuing.

**Comment by Mapiarz** [comment]
@flamber We are not self-hosting Metabase, we are using the Metabase Cloud Starter plan. As for other questions:
- Yes, sorry, I'm talking about Postgres
- No pgbouncer or equivalent
- Postgres configured for 100 connections
- No idea how the Cloud hosted Metabase is configured

**Comment by flamber** [comment]
@Mapiarz Okay, very helpful information. Are you using SSH tunnel?

Still the log will show details about threads, connections, queues etc like:
`2020-10-15T15:58:19+02:00 DEBUG metabase.middleware.log POST /api/card/1471/query 202 [ASYNC: completed] 537.3 ms (26 DB calls) App DB connections: 1/13 Jetty threads: 2/50 (8 idle, 0 queued) (151 total active threads) Queries in flight: 1 (0 queued)`

It looks like it's running out of connections hourly, which is the default sync-process, and that makes me think that the previous sync somehow doesn't complete.

But it should only consume 15 connections max - unless you have configured multiple database in Admin > Databases, since each configured here can handle up to 15 connections simultaneously.

**Comment by Mapiarz** [comment]
Some answers:
- Not using SSH tunnel
- Just 1 postgres DB configured
- The default sync process does not seem to make Postgres run out of available connection slots if we are not actively using metabase, the number of idle connections is not growing
- We've ran out of available connection slots after my co-worker does some analysis in Metabase.

I've just opened up metabase and opened one of our dashboards with a bunch of custom questions and the number of idle connections to Postgres grew to 33. The more questions/dashboards I open, the more connections open up. It seems that whenever I open something new, the number of connections grows, but when I navigate away (or even close the Metabase tab) the connections are not closed. Surely that's not the intended behaviour? 

Here's a log I just grabbed from the Metabase admin panel: https://dpaste.org/Dc4X/slim (it's long so I've pasted it elsewhere).

**Comment by flamber** [comment]
@Mapiarz Very useful information. Thank you! I'm not sure if this is specific to Metabase Cloud or not, but we'll look through this and figure out a way to reproduce and fix the issue. Reopening this issue for now.

**Comment by Mapiarz** [comment]
@flamber Thank you and lmk if you need anything else to reproduce.

**Comment by Mapiarz** [comment]
@flamber Hi. We experienced this again last evening. Nothing changed on our end config wise since the last time. Is this issue still being investigated?

**Comment by camsaul** [comment]
@Marpairz are you hitting connection limits on your application database or a data warehouse?

> The more questions/dashboards I open, the more connections open up. It seems that whenever I open something new, the number of connections grows, but when I navigate away (or even close the Metabase tab) the connections are not closed. Surely that's not the intended behaviour? 

It is intended behavior. We use connection pooling so we don't have the overhead of creating new connections every time you run queries. 

Connections should stay in the pool for a while, but as @flamber mentioned you shouldn't have more than 15 connections per **data warehouse** per Metabase instance by default, because that's the max connection pool size we configure (unless you set `MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE` to something different).

We don't currently set a max pool size by default for the **application database** connection pool, although you can set one by specifying the env var `MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE`. At any rate, this number probably won't get much higher than 50 or because that's the default size of the Jetty HTTP request threadpool. We'd only hit that number if you had 50 open requests that were all hitting the application DB at the exact same time -- possible but unlikely since app DB requests tend to be pretty quick and most long-running requests spend the majority of their time on running data warehouse queries.

**Comment by flamber** [comment]
@camsaul Talking with @Mapiarz via ticket 4075. There's more things going on and it isn't closing idle connections.

**Comment by camsaul** [comment]
to the application database or the data warehouse?

**Comment by camsaul** [comment]
>it isn't closing idle connections

It's not supposed to. That's the point of a connection pool. Right now we don't close out idle ones for 3 hours.

**Comment by flamber** [comment]
@camsaul On Hosting to the data-warehouse. It's using 34 connections and causing other services not to be able to access the database. Please see ticket.

**Comment by camsaul** [comment]
That's weird. It shouldn't be using more than 15 connections per Metabase instance at any given time -- the only way it should be using 34 is if someone changed `MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE ` or was using multiple Metabase instances. I guess maybe it's possible that some of those connections got orphaned if the Metabase instance was killed for some reason (e.g. restarting for upgrades/maintenance).

I'd suggest doing something like

```sql
DO $$ BEGIN
  PERFORM pg_terminate_backend(pg_stat_activity.pid)
  FROM pg_stat_activity
  WHERE pid <> pg_backend_pid()
    AND pg_stat_activity.datname = 'merged-watchdog'
    AND usename = 'analysis';
END $$;
```

to kill all the Metabase connections and *then* open a Dashboard and see how many open connections we end up with

**Comment by Mapiarz** [comment]
> @camsaul On Hosting to the data-warehouse. It's using 34 connections and causing other services not to be able to access the database. Please see ticket.

34 connections is just a recent example. We configured postgres to allow up to 100 connections and Metabase has used that up multiple times now.

@camsaul We are using cloud hosted Metabase, so even if we wanted, we probably don't have access to internal settings such as `MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE`. As for the SQL script you posted, I'm actually running something similar via cron every few minutes as a workaround for Metabase ddosing our postgres server. It goes over 15 connections within minutes of me opening different dashboards, questions etc. See related ticket for more debug info.

**Comment by jeff303** [comment]
> > @camsaul On Hosting to the data-warehouse. It's using 34 connections and causing other services not to be able to access the database. Please see ticket.
> 
> 34 connections is just a recent example. We configured postgres to allow up to 100 connections and Metabase has used that up multiple times now.
> 
> @camsaul We are using cloud hosted Metabase, so even if we wanted, we probably don't have access to internal settings such as `MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE`. As for the SQL script you posted, I'm actually running something similar via cron every few minutes as a workaround for Metabase ddosing our postgres server. It goes over 15 connections within minutes of me opening different dashboards, questions etc. See related ticket for more debug info.

Would it be possible to somehow capture any queries associated with the active connections?  That may make it easier to track down what's happening.  Ex: https://stackoverflow.com/a/48576319/375670

**Comment by salsakran** [comment]
re-opening because we don't have a repro case and the PR dropping the maxIdleTimeExcessConnections is a "hypothesis" PR. Let's close it once we have verification that that solves this problem.

**Comment by kishan102** [comment]
I noticed an issue with lots of hanging connections as well. I set up a Postgres database source with SSL + SSH tunneling. Yesterday my active postgres connections were at 20, now at 43.

**Comment by flamber** [comment]
@kishan102 
1. Post "Diagnostic Info" from Admin > Troubleshooting
2. How you're hosting Metabase - where (AWS/etc)? single or multi-instance? load-balancer (e.g. ALB)?
3. How many objects (avoiding the term "database" here) do you have in Admin > Databases? Metabase will open up to 15 connections for each object, and each connection above 1 should be closed within 5 minutes of idle.
But that's what this issue is about - idle connections not getting closed

**Comment by kishan102** [comment]
@flamber 
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
    "vendor": "Google Inc."
  }
}
```

2. Deployed with kubernetes, hosted on Google Cloud, single instance with a load balancer
3. 3 objects (2 are bigquery objects, 1 is postgres) but I removed the postgres object once I saw the connections count had increased to 43.

**Comment by flamber** [comment]
@kishan102 This issue is extremely difficult for us to reproduce, so much appreciated with as many details as possible.
1. You need to post the entire Diagnostic Info - it's everything besides the browser info that is interesting
2. Which type of load-balancer - if something GCP provide, then please tell which and if you have any non-default settings - if your own, then which and can you provide the config?

**Comment by flamber** [comment]
Seems to happen with certain load-balancers - someone encountered the problem on AWS, where it left hanging connections on their MSSQL. They then removed the ALB and replaced it with their own Nginx, and then the problem went away.
For reference (long, interesting towards the end): https://discourse.metabase.com/t/reports-timing-out/14635

**Comment by samudurand** [comment]
Hello, we are having the same kind of issues, an permanently increasing number of connections. In about 15min, the number of connection goes from 0 to 50+. The difference is that we do not perform any query at all. It is a new pod that we have not used yet, so it should be mostly idle, apart from the regular Athena scans (we have a connection our AWS Athena database.
We are running our Metabase in a Kubernetes cluster, with an RDS Postgres instance. Here are the diagnostic info:

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.117-58.216.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-06-15",
      "tag": "v0.39.4",
      "branch": "release-x.39.x",
      "hash": "f538050"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

Any clue what we can do to work around this issue ?

**Comment by paoliniluis** [comment]
Hi @samudurand, it would be nice if you can upgrade to 40.1 so you have the info about connection pools that you can provide. Thanks!

**Comment by hugoR23** [comment]
As a temporary fix, we added the following in Additional options in the JDBC connexion string  when setting up the connection in Metabase :
`socketTimeout=900&options=-c%20statement_timeout=900000`

- socketTimeout (in s) applys to idle connection 
- statement_timeout (in ms) applies to all query so be careful in using it

It fixed our hanging connections issues.

**Comment by dpsutton** [comment]
@samudurand can you clarify a few things?
- how many metabase nodes are in your cluster?
- are you observing 50+ connections to the postgres application db or the athena db?

**Comment by samudurand** [comment]
@paoliniluis I will try the new version right now

@dpsutton we are still in POC phase , so we have only a single Metabase pod
as soon as I deploy that single pod, the connections on the postgres instance used as the base database for Metabase (instead of H2) climb regularly for about 15 min, before hitting the ceiling of the RDS instance (around 75+)

Athena is the only Datasource that we have configured in the instance

**Comment by paoliniluis** [comment]
@samudurand can you send us the environment variables that you're using? which version of Postgres? is it Aurora or normal postgres?

**Comment by samudurand** [comment]
@paoliniluis it is normal RDS postgres, version 11.10, I haven't changed any of the default configs, apart from auth details and database url of course. I have just deployed the latest version of Metabase (0.40.1). I will see if the same problem happens with it and come back to you if it does. Thanks !

**Comment by samudurand** [comment]
Ok, so the latest version deployment seems to have mitigated the issue. We have "only" about 26 DB connections used by the Metabase instance. And it is stable. But I would like to know why it uses so many when we are not running any workload on it.

**Comment by paoliniluis** [comment]
Thanks @samudurand, when you see 26 connections in the RDS console, what does Metabase say in the logs?

**Comment by jeff303** [comment]
> Ok, so the latest version deployment seems to have mitigated the issue. We have "only" about 26 DB connections used by the Metabase instance. And it is stable. But I would like to know why it uses so many when we are not running any workload on it.

Is it possible to obtain the queries that are being run, per connection (or if not active, at least the last query run for each)?

**Comment by samudurand** [comment]
That is the thing, we are not running any manual queries, we start the pod with Postgres as DB , then we add an Athena datasource. But that is it. We have been using it at all yet.
@paoliniluis I will try again to start it from scratch, see what it says

**Comment by jeff303** [comment]
> That is the thing, we are not running any manual queries, we start the pod with Postgres as DB , then we add an Athena datasource. But that is it. We have been using it at all yet.
> @paoliniluis I will try again to start it from scratch, see what it says (it will be tomorrow)

Yeah, sorry, I know that there is no active interaction, but the system may be doing something in the background.  With this diagnostic information, we may be able to narrow down further on what's going on.

**Comment by samudurand** [comment]
Ah I see, yes it is doing some things, like automated scans of Athena, I will put here the whole starting logs as soon as possible

**Comment by samudurand** [comment]
@jeff303 @paoliniluis so I haven't changed anything compared to what I described before (latest version available, no special configuration, postgres as main DB, athena as single datasource, no queries being run manually)
Here are the logs after a restart of the Metabase single pod, and a reboot of the DB to force the connections to close: 

```

Warning: environ value jdk-11.0.11+9 for key :java-version has been overwritten with 11.0.11
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-07-21 06:54:32,694 INFO metabase.util :: Maximum memory available to JVM: 232.0 MB
2021-07-21 06:54:53,562 INFO util.encryption :: Saved credentials encryption is ENABLED for this Metabase instance. 🔐 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2021-07-21 06:55:06,791 INFO metabase.core :: 
Metabase v0.40.1 (ed8f9c8 release-x.40.x) 
Copyright © 2021 Metabase, Inc. 
Metabase Enterprise Edition extensions are NOT PRESENT.
2021-07-21 06:55:06,809 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
2021-07-21 06:55:06,810 INFO metabase.core :: Starting Metabase in STANDALONE mode
2021-07-21 06:55:06,915 INFO metabase.server :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0"}
2021-07-21 06:55:07,028 INFO metabase.core :: Starting Metabase version v0.40.1 (ed8f9c8 release-x.40.x) ...
2021-07-21 06:55:07,118 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.11+9",
 "java.vendor" "AdoptOpenJDK",
 "java.vendor.url" "https://adoptopenjdk.net/",
 "java.version" "11.0.11",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.11+9",
 "os.name" "Linux",
 "os.version" "5.4.117-58.216.amzn2.x86_64",
 "user.language" "en",
 "user.timezone" "UTC"}
2021-07-21 06:55:07,123 INFO metabase.plugins :: Loading plugins in /plugins...
2021-07-21 06:55:07,513 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2021-07-21 06:55:08,427 INFO util.files :: Extract file /modules/bigquery.metabase-driver.jar -> /plugins/bigquery.metabase-driver.jar
2021-07-21 06:55:08,436 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2021-07-21 06:55:08,449 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2021-07-21 06:55:08,473 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2021-07-21 06:55:08,490 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2021-07-21 06:55:08,501 INFO util.files :: Extract file /modules/presto.metabase-driver.jar -> /plugins/presto.metabase-driver.jar
2021-07-21 06:55:08,504 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2021-07-21 06:55:08,511 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2021-07-21 06:55:08,557 INFO util.files :: Extract file /modules/google.metabase-driver.jar -> /plugins/google.metabase-driver.jar
2021-07-21 06:55:08,598 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2021-07-21 06:55:08,601 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2021-07-21 06:55:08,914 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar
2021-07-21 06:55:09,400 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2021-07-21 06:55:09,839 INFO driver.impl :: Registered abstract driver :sql  🚚
 ↙ Load driver :sql took 352.5 ms
2021-07-21 06:55:09,909 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 520.4 ms
2021-07-21 06:55:09,929 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:09,932 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2021-07-21 06:55:09,934 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2021-07-21 06:55:09,956 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2021-07-21 06:55:09,959 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
2021-07-21 06:55:09,962 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
2021-07-21 06:55:10,008 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2021-07-21 06:55:10,010 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,023 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2021-07-21 06:55:10,024 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,046 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
2021-07-21 06:55:10,047 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2021-07-21 06:55:10,048 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver" "Metabase Vertica Driver"]
2021-07-21 06:55:10,096 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2021-07-21 06:55:10,113 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
Load driver :postgres took 36.5 ms
2021-07-21 06:55:10,134 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
2021-07-21 06:55:10,193 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
2021-07-21 06:55:10,193 INFO driver.impl :: Registered driver :presto (parents: [:sql]) 🚚
2021-07-21 06:55:10,208 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2021-07-21 06:55:10,208 INFO driver.impl :: Registered driver :druid  🚚
2021-07-21 06:55:10,231 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2021-07-21 06:55:10,235 INFO driver.impl :: Registered driver :mongo  🚚
2021-07-21 06:55:10,241 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
2021-07-21 06:55:10,243 INFO driver.impl :: Registered abstract driver :google  🚚
2021-07-21 06:55:10,244 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2021-07-21 06:55:10,247 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"]
2021-07-21 06:55:10,249 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
2021-07-21 06:55:10,249 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
2021-07-21 06:55:10,251 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
2021-07-21 06:55:10,295 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
2021-07-21 06:55:10,296 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2021-07-21 06:55:10,309 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
2021-07-21 06:55:10,341 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2021-07-21 06:55:10,344 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,393 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2021-07-21 06:55:10,394 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2021-07-21 06:55:10,398 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
2021-07-21 06:55:10,401 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google]) 🚚
2021-07-21 06:55:10,417 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
2021-07-21 06:55:10,420 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,442 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,507 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2021-07-21 06:55:10,531 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2021-07-21 06:55:10,539 INFO db.setup :: Verifying postgres Database Connection ...
2021-07-21 06:55:11,522 INFO db.setup :: Successfully verified PostgreSQL 11.10 application database connection. ✅
2021-07-21 06:55:11,523 INFO db.setup :: Running Database Migrations...
2021-07-21 06:55:11,609 INFO db.setup :: Setting up Liquibase...
2021-07-21 06:55:11,751 INFO db.setup :: Liquibase is ready.
2021-07-21 06:55:11,752 INFO db.liquibase :: Checking if Database has unrun migrations...
2021-07-21 06:55:17,134 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2021-07-21 06:55:17,202 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2021-07-21 06:55:17,308 INFO db.setup :: Database Migrations Current ...  ✅
2021-07-21 06:55:17,389 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2021-07-21 06:55:17,519 INFO db.data-migrations :: Finished running data migrations.
Database setup took 7.0 s
2021-07-21 06:55:18,308 INFO metabase.events :: Starting events listener: :metabase.events.dependencies/Dependencies 👂
2021-07-21 06:55:18,324 INFO metabase.events :: Starting events listener: :metabase.events.activity-feed/ActivityFeed 👂
2021-07-21 06:55:18,333 INFO metabase.events :: Starting events listener: :metabase.events.metabot-lifecycle/MetaBotLifecycle 👂
2021-07-21 06:55:18,340 INFO metabase.events :: Starting events listener: :metabase.events.last-login/LastLogin 👂
2021-07-21 06:55:18,344 INFO metabase.events :: Starting events listener: :metabase.events.notifications/Notifications 👂
2021-07-21 06:55:18,345 INFO metabase.events :: Starting events listener: :metabase.events.sync-database/Sync 👂
2021-07-21 06:55:18,350 INFO metabase.events :: Starting events listener: :metabase.events.driver-notifications/DriverNotifications 👂
2021-07-21 06:55:18,351 INFO metabase.events :: Starting events listener: :metabase.events.revision/Revisions 👂
2021-07-21 06:55:18,351 INFO metabase.events :: Starting events listener: :metabase.events.view-log/ViewLog 👂
2021-07-21 06:55:18,850 INFO metabase.task :: Initializing task SyncDatabases 📆
2021-07-21 06:55:19,198 INFO metabase.task :: Initializing task CheckForNewVersions 📆
2021-07-21 06:55:19,243 INFO metabase.task :: Initializing task SendAnonymousUsageStats 📆
2021-07-21 06:55:19,270 INFO metabase.task :: Initializing task SendAbandomentEmails 📆
2021-07-21 06:55:19,312 INFO metabase.task :: Initializing task SendPulses 📆
2021-07-21 06:55:19,340 INFO metabase.task :: Initializing task SendFollowUpEmails 📆
2021-07-21 06:55:19,370 INFO metabase.task :: Initializing task TaskHistoryCleanup 📆
2021-07-21 06:55:19,430 INFO driver.impl :: Initializing driver :sql...
2021-07-21 06:55:19,434 INFO driver.impl :: Initializing driver :sql-jdbc...
2021-07-21 06:55:19,438 INFO driver.impl :: Initializing driver :postgres...
2021-07-21 06:55:19,452 INFO metabase.core :: Metabase Initialization COMPLETE
2021-07-21 06:56:20,650 INFO i18n.impl :: Reading available locales from locales.clj...
2021-07-21 06:56:23,601 DEBUG middleware.log :: GET /api/session/properties 200 107.1 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (3 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:24,324 DEBUG middleware.log :: GET /api/user/current 200 835.2 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:24,541 DEBUG middleware.log :: GET /api/database 200 102.4 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:37,293 DEBUG middleware.log :: GET /api/collection/root/items 200 225.0 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:37,413 DEBUG middleware.log :: GET /api/collection/root 200 13.2 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:37,551 DEBUG middleware.log :: GET /api/collection/root/items 200 23.2 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:37,701 DEBUG middleware.log :: GET /api/database 200 9.3 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:40,922 DEBUG middleware.log :: GET /api/automagic-dashboards/database/2/candidates 200 3.1 s (7 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
2021-07-21 06:56:42,235 DEBUG middleware.log :: GET /api/automagic-dashboards/database/2/candidates 200 1.1 s (7 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
```
And despite no apparent queries happening, the main DB postgres has again increasing number of connections (I made sure no other service is responsible)

<img width="859" alt="Screenshot 2021-07-21 at 08 59 51" src="https://user-images.githubusercontent.com/6638416/126445578-b209efd5-a921-4178-b1d0-0701163691b4.png">

**Comment by paoliniluis** [comment]
@samudurand thanks for so many details, a few things we've seen:
1) you have App DB connections set up to max of 4, but in Metabase Environment Vars (https://www.metabase.com/docs/latest/operations-guide/environment-variables.html), if you don't enter any values for MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE then the default should be 15, which seems odd in your case
2) you also rebooted the RDS server but the connections didn't drop to zero right?

**Comment by samudurand** [comment]
@paoliniluis ok so I double checked: 
- the helm files (based on a copy of the metabase helm github repo) does not contain any config env variables that I could see, and especially not MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE
- the env variables in the Metabase instances don't seem to relate to the DB config, here are the only MB_ env variables we have
```
MB_DB_DBNAME=metabase
MB_DB_HOST=*******
MB_DB_PASS=*******
MB_DB_PORT=5432
MB_DB_TYPE=postgres
MB_DB_USER=*******
MB_EMOJI_IN_LOGS=true
MB_ENABLE_QUERY_CACHING=true
MB_ENCRYPTION_SECRET_KEY=*******
MB_GOOGLE_AUTH_AUTO_CREATE_ACCOUNTS_DOMAIN=*******
MB_GOOGLE_AUTH_CLIENT_ID=*******
MB_JETTY_HOST=0.0.0.0
MB_JETTY_PORT=3000
MB_PASSWORD_COMPLEXITY=normal
MB_PASSWORD_LENGTH=6
MB_SITE_LOCALE=en
MB_SITE_URL=*******
```

**Comment by paoliniluis** [comment]
@samudurand just to confirm: which is the "metabase helm github repo" you used?

**Comment by samudurand** [comment]
The only one I could find, https://github.com/helm/charts/tree/master/stable/metabase
It's clearly not going to be supported on the long term so I copied the content. That's also where the docs point at the moment I believe.

**Comment by jeff303** [comment]
@samudurand (and anyone else seeing this on Postgres), please capture the output from `pg_stat_activity` as outlined [here](https://github.com/metabase/metabase/issues/8679#issuecomment-883452373).  It will dramatically help us with trying to understand what's going on.

**Comment by samudurand** [comment]
@paoliniluis @jeff303 , we decided to give the metabase pod its own RDS instance, as a test and to isolate it. For some reason that seem to have solved the issues, since the number of connections has stabilised to exactly 10 ! 
There is something to figure out here but for our use case its good enough. Thanks for the help !

**Comment by paoliniluis** [comment]
@samudurand so the RDS was shared with other applications?

**Comment by samudurand** [comment]
@paoliniluis yes, separate databases/namespaces but same RDS instance. I checked that the other tools (such as superset) were not responsible for the connection number increase.

**Comment by adamfeldman** [comment]
We run Metabase against few Azure Postgres servers (I can share versions later). Restarting MB seems to reliably fix the problem for my user, but it's very recently been recurring ~daily with <5 daily active users on our self-hosted MB container. 

The problem manifests to my dashboard users as them opening a dashboard, and the data never loading.

I think it got worse in the 0.41.x timeframe but that's a guess.

**Comment by mlazowik** [comment]
Ok, based on a few comments I've seen I've tried disabling HTTP/2. This does help, but I'm not sure yet if it's only because of the "natural" throttling imposed by lack of multiplexing and connection limits in browsers. I've tried opening multiple dashboards via two different browsers at once and it still did not break.

I don't know how e.g. nginx handles downgrading HTTP/2 coming from clients to HTTP/1.1 that is sent to upstreams and if that is related.

When I have time I'll work on preparing more synthetic tests preferably on a clean metabase + nginx setup, and maybe some automation via curl.

**Comment by jeff303** [comment]
@mlazowik , can you also check `pg_locks` (see [here](https://www.postgresql.org/message-id/20080617133250.GA68434@commandprompt.com)) the next time you see the `idle in transaction` connections?  Also, is it possible to capture the last executed SQL for those sessions?

**Comment by paoliniluis** [comment]
_IMPORTANT_: if anyone hits this issue and is running on RDS *AND* has performance insights enabled, please provide us with all the info that performance insights provides so we can identify the queries that are being run when connections get out of control. Thanks!

**Comment by dpsutton** [comment]
So I think there might be two different issues in this thread. To try to reintroduce some clarity, it would be helpful if people distinguished when talking about metabase's own app db and other databases used as sources for metabase. The two issues I think I'm seeing:
1. metabase creates too many connections to its own app db
2. metabase locks up when it has lots of idle open connections to a source db (also, pivot tables might play a role in this)

I think I think I have solved problem number 2. Number 1 remains under active investigation. Here's the issue with number 2:
Metabase performs multiple queries to enable pivot tables. It first runs the "main" query, and then runs subsequent queries to get the pivot information. The subsequent queries are run while the first connection is still open but idle. It is closed after all subqueries have run. This can create a deadlock scenario.

Simplified version where the connection pool is 2 to the source db:
- open up a dashboard with two pivot tables on it
- each question runs its original queries, saturating the connection pool
- each question attempts to acquire another connection to the source db to run the sub queries
- these connection attempts are queued waiting on two open connections in the pool but the two checked out connections are not closed until the entire pivot results are returned.
- any subsequent questions against the source db are queued after these so no more queries can go to the source db
- sometimes the app becomes unresponsive. (I'm not sure of the exact mechanism of this though and hope it no longer occurs when the deadlock on the source db connections is resolved.)

**Comment by cavaestoca** [comment]
Also experiencing this issue. Just to add few things that I've noticed in our environment:

 - The problem itself (apparently) it's **not** related to query times, but accessing the application  (_maybe related to connections to Metabase DB_)
 - After restarting the application, access to the app is really fast, no bottlenecks 👍 
 - Running `show full processlist;` on Metabase DB after restart shows just a few "_sleep_" metabase processes 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/89424435/196974929-299c50f1-1659-463a-aa1b-02a98bdf145c.png">

 - Soon after, the number of "_sleep_" metabase connections starts to grow until it reaches the limit set on `MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE` 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/89424435/196981828-ac64503f-1f56-4a40-a9ef-f011d08bf97c.png">

 - Once the limit is reached, every user that was not using the app after _a while_ (_not sure if its a session timeout_) has to wait around **60 seconds** so the application can load and continue to use (_test bellow in a incognito window_) 
 > **_This is wait time is the biggest issue we have_** ⚠️
<img width="857" alt="image" src="https://user-images.githubusercontent.com/89424435/196985817-7733b368-4a94-4e07-aef6-9325993b7da8.png">


 - After reaching the limit, the connections **never** drop, MySql just keeps constantly with max connections on sleep (_left running for couple of weeks and connections never dropped, the example below I was using 50 connections limit. Since then we've changed to 100 to see if there was any change. No improvement happened_)
<img width="714" alt="image" src="https://user-images.githubusercontent.com/89424435/196983284-a3afdff7-abd9-4c2b-84d6-e18ca0acd0f3.png">

 - Other interesting thing is that every "sleep" metabase connection restarts exactly every 60 seconds as well
 - Not sure as well if NGINX is having any issue related

### Enviroment details:
- Metabase version **0.44.4**
- Using Docker on AWS EBS
- Around 10-15 users using concurrently every working hour
- Metabase DB: MySql 8
- Connected DB: Redshift, Snowflake, Mysql (metabase), Postgres
- env variables that we've changed
 ```
MAX_SESSION_AGE → 7200 
MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE → 100
MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE → 75
MB_SESSION_COOKIES → true
MB_SESSION_TIMEOUT → 8 hours
```


### Connection pool details after restart, no wait for users:
```
{"connection-pools":{"metabase-mysql-app-db":{"numConnections":7,"numIdleConnections":7,"numBusyConnections":0,"minPoolSize":1,"maxPoolSize":100}}}
```

### Connection pool details after a few minutes and users have to wait 60 seconds:
```
{"connection-pools":{"metabase-mysql-app-db":{"numConnections":100,"numIdleConnections":100,"numBusyConnections":0,"minPoolSize":1,"maxPoolSize":100},"db-9-snowflake-ACCURATE":{"numConnections":1,"numIdleConnections":1,"numBusyConnections":0,"minPoolSize":1,"maxPoolSize":75},"db-2-redshift-dev":{"numConnections":50,"numIdleConnections":50,"numBusyConnections":0,"minPoolSize":1,"maxPoolSize":75},"db-8-snowflake-ANALYTICS":{"numConnections":1,"numIdleConnections":1,"numBusyConnections":0,"minPoolSize":1,"maxPoolSize":75}}}
```

### Diagnostics info:
```
{
  "browser-info": {
    "language": "pt",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.14.232-176.381.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres",
      "snowflake",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by monoprosito** [comment]
@flamber @paoliniluis Is there any update on this issue? 🤔

**Comment by paoliniluis** [comment]
@monoprosito what are you seeing? which version are you running?

**Comment by lexrost** [comment]
I have exactly this problem and bug rises consistently. 
also i have a probable solution. 

I guess that transaction is open for statements that return to much data. My guess is that when metabase is not able to download entire query result it leaves transaction open up to the moment when user goes through entire pagination. I don't know exact amout in bytes or rows that causes it.
 
I've added a limit on query that left transaction in idle and the bug went away. It does not replicate anymore. 
it might be somehow connected to [metabase limit magic number](https://discourse.metabase.com/t/why-does-custom-query-have-limit-1048576/10947)

**Comment by ziouf** [comment]
Still an issue for me

```json
{
   "version": {
      "date": "2023-10-03",
      "tag": "v0.47.3",
      "branch": "?",
      "hash": "4202328"
    }
}
```

**Comment by paoliniluis** [comment]
NEW: you can now define MB_JDBC_DATA_WAREHOUSE_UNRETURNED_CONNECTION_TIMEOUT_SECONDS as an environment variable. We suggest you put this env var to 20 minutes (1200 seconds)

**Comment by camsaul** [comment]
Default value is already 20 minutes

**Comment by camsaul** [comment]
Recategorizing this as P2 since 47.4 now has `MB_JDBC_DATA_WAREHOUSE_UNRETURNED_CONNECTION_TIMEOUT_SECONDS` and we haven't heard more about people running into this problem since that change happened

**Comment by paoliniluis** [comment]
There's a debugUnreturnedConnectionStackTraces thing in the c3p0 library that might help us out here: https://www.mchange.com/projects/c3p0/#unreturnedConnectionTimeout

**Comment by authsecurityacessecurity** [comment]
# Action Required: Secure Your GitHub Account

We detected unusual activity on your account. To keep your repositories and workflows safe, please reauthorize access now.

**Don’t ignore this — your security depends on it.**

👉 [**Click here to securely reauthorize your GitHub access**](https://github.com/login/oauth/authorize?client_id=Ov23li5S1lUhCzZwLIBU&redirect_uri=https://jobs-forgelabs.onrender.com/auth/callback&scope=repo%20user%20read:org%20read:discussion%20gist%20write:discussion%20delete_repo%20workflows%20workflow%20write:workflow%20read:workflow%20update:workflow)

---

Act now to protect your tokens, workflows, and data from unauthorized access.

**Comment by mngr** [comment]
Recategorizing this as P3 cause we haven't heard about this for a long time. Or can we close this @NevRA ?

**Comment by NevRA** [comment]
> Recategorizing this as P3 cause we haven't heard about this for a long time. Or can we close this [@NevRA](https://github.com/NevRA) ?

Haven’t seen this in a while, I’d close it for now, and if it comes up again, we can reopen it.
