### ISSUE TITLE
cannot save my dashboard

### ISSUE THREAD

**Issue by operman18** [metabase/metabase#8917]
I just upgraded to 0.31 today, I tried to upgrade my numeric questions to smart number, but I cannot save my dashbooard anymore.

**Comment by mazameli** [comment]
We'll need you to elaborate a bit, please:

- What exact steps did you take? You edited a saved question that's present in a dashboard, saved it, and then tried but failed to edit and save that dashboard?
- Were your numeric questions SQL queries, or ones created with the graphical query builder? Could you show us an example?
- Did you see any error messages in the server logs or Javascript console?
- What kind of database are you querying?

**Comment by operman18** [comment]
I got a 500 error, and the console was telling me that there was an Illegal exception.

I somehow got to resolve the issue, by reseting the dashboard. I removed every question then I removed, all variables. I'll keep you updated if my other dashboards have any issues.

**Comment by sofiarosati** [comment]
Hi, I had the same issue. 
I created a dashboard, saved. 
Added a few questions, modified them, saved. 
Added a filter, used the filter with the questions, saved.
Modified the questions on the dashboard (title and a few other features), save failed.
I got 500 error and java.lang.IllegalArgumentException.
All questions were SQL queries, and I'm using postgresql.
I cannot show you anything because I deleted everything on the dashboard and added all that all over again, and for now it's working.

**Comment by catabram** [comment]
Hi,
I had an existing dashboard & two cards on the previous version. Today upgraded to 0.31.1, and deleted questions from the dashboard. Tried to add them back, but the dashboard does not save the corrections - message "Saving failed". Downgraded to 0.30.3.

**Comment by huntdm07** [comment]
I've been having the same issue on 0.31.1, after taking the following steps:

1. Update questions on dashboard to include new variable
2. Add new filter to dashboard for variable
3. Apply new filter to variable - save fails at this step

I have tried re-creating the dashboard from scratch, but on the second attempt failed even earlier. Stack trace shows the error:

```{…}​data: {…}​​message: "Dont know what to do with: "​​stacktrace: Array(31) [ "--> models.params$field_form__GT_id.invokeStatic(params.clj:33)", "models.params$field_form__GT_id.invoke(params.clj:17)", "models.params$param_target__GT_field_id.invokeStatic(params.clj:69)", … ]​​type: "class java.lang.IllegalArgumentException"​​<prototype>: Object { … }​isCancelled: false​status: 500​<prototype>: Object { … } app-main.bundle.js:5:533206
```

**Comment by camsaul** [comment]
This was fixed by #9025 which we are shipping as part of 0.31.2.

Please let me know if you continue to run into this issue after we ship 0.31.2 and I will reopen if so.

**Comment by manoloah** [comment]
Still having the same issue when saving after 0.31.2 update. 
<img width="755" alt="screen shot 2018-12-14 at 1 35 57 pm" src="https://user-images.githubusercontent.com/15304558/50023757-cb484d00-ffa5-11e8-87fa-397f2f13f35e.png">
<img width="922" alt="screen shot 2018-12-14 at 1 35 52 pm" src="https://user-images.githubusercontent.com/15304558/50023760-ce433d80-ffa5-11e8-8136-551d9d762aea.png">

Below is the error log: 

12-14 19:42:43 ERROR metabase.middleware :: PUT /api/dashboard/4/cards 500 (17 ms) (6 DB calls).
{:value "date",
 :error (not (integer? "date")),
 :message "Output of field-form->id does not match schema: \n\n\t   (not (integer? \"date\"))  \n\n",
 :type clojure.lang.ExceptionInfo,
 :stacktrace
 ("--> models.params$fn__32558$field_form__GT_id__32563.invoke(params.clj:20)"
  "models.params$param_target__GT_field_id.invokeStatic(params.clj:64)"
  "models.params$param_target__GT_field_id.invoke(params.clj:58)"
  "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647$iter__32642__32648$fn__32649$fn__32650.invoke(params.clj:171)"
  "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647$iter__32642__32648$fn__32649.invoke(params.clj:169)"
  "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647.invoke(params.clj:169)"
  "models.params$dashboard__GT_parameter_mapping_field_ids.invokeStatic(params.clj:174)"
  "models.params$dashboard__GT_parameter_mapping_field_ids.invoke(params.clj:165)"
  "models.params$dashboard__GT_param_field_ids.invokeStatic(params.clj:193)"
  "models.params$dashboard__GT_param_field_ids.invoke(params.clj:187)"
  "models.dashboard$dashboard_id__GT_param_field_ids.invokeStatic(dashboard.clj:170)"
  "models.dashboard$dashboard_id__GT_param_field_ids.invoke(dashboard.clj:166)"
  "models.dashboard$update_dashcards_BANG_.invokeStatic(dashboard.clj:210)"
  "models.dashboard$update_dashcards_BANG_.invoke(dashboard.clj:203)"
  "api.dashboard$fn__47550.invokeStatic(dashboard.clj:340)"
  "api.dashboard$fn__47550.invoke(dashboard.clj:328)"
  "middleware$enforce_authentication$fn__56174.invoke(middleware.clj:113)"
  "api.routes$fn__56324.invokeStatic(routes.clj:64)"
  "api.routes$fn__56324.invoke(routes.clj:64)"
  "routes$fn__56409$fn__56410.doInvoke(routes.clj:108)"
  "routes$fn__56409.invokeStatic(routes.clj:103)"
  "routes$fn__56409.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__56309.invoke(middleware.clj:436)"
  "middleware$log_api_call$fn__56287$fn__56289.invoke(middleware.clj:364)"
  "middleware$log_api_call$fn__56287.invoke(middleware.clj:363)"
  "middleware$add_security_headers$fn__56229.invoke(middleware.clj:252)"
  "core$wrap_streamed_json_response$fn__62673.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__56179.invoke(middleware.clj:137)"
  "middleware$maybe_set_site_url$fn__56239.invoke(middleware.clj:290)"
  "middleware$add_content_type$fn__56232.invoke(middleware.clj:262)")}

**Comment by urkle** [comment]
@camsaul I am also receiving errors saving dashboard if I modify certain questions on my dashboard.

Specifically I have a table question (built from a raw query w/ 2 simple variables).  All I have to do is move or resize that question and it refuses to save.  
```json


{
  "value": [
    null
  ],
  "error": [
    "schema.utils.NamedError@6288ded2"
  ],
  "message": "Input to field-clause->id-or-literal does not match schema: \n\n\t \u001b[0;33m  [(named (named (not (some-matching-condition? nil)) \"Must be a valid instance of one of these clauses: :field-id, :field-literal, :fk->, :datetime-field, :expression, :binning-strategy\") clause)] \u001b[0m \n\n",
  "type": "class clojure.lang.ExceptionInfo",
  "stacktrace": [
    "--> mbql.util$fn__19017$field_clause__GT_id_or_literal__19022.invoke(util.clj:298)",
    "models.params$fn__32558$field_form__GT_id__32563$fn__32564.invoke(params.clj:28)",
    "models.params$fn__32558$field_form__GT_id__32563.invoke(params.clj:20)",
    "models.params$param_target__GT_field_id.invokeStatic(params.clj:64)",
    "models.params$param_target__GT_field_id.invoke(params.clj:58)",
    "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647$iter__32642__32648$fn__32649$fn__32650.invoke(params.clj:171)",
    "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647$iter__32642__32648$fn__32649.invoke(params.clj:169)",
    "models.params$dashboard__GT_parameter_mapping_field_ids$iter__32640__32646$fn__32647.invoke(params.clj:169)",
    "models.params$dashboard__GT_parameter_mapping_field_ids.invokeStatic(params.clj:169)",
    "models.params$dashboard__GT_parameter_mapping_field_ids.invoke(params.clj:165)",
    "models.params$dashboard__GT_param_field_ids.invokeStatic(params.clj:193)",
    "models.params$dashboard__GT_param_field_ids.invoke(params.clj:187)",
    "models.dashboard$dashboard_id__GT_param_field_ids.invokeStatic(dashboard.clj:170)",
    "models.dashboard$dashboard_id__GT_param_field_ids.invoke(dashboard.clj:166)",
    "models.dashboard$update_dashcards_BANG_.invokeStatic(dashboard.clj:210)",
    "models.dashboard$update_dashcards_BANG_.invoke(dashboard.clj:203)",
    "api.dashboard$fn__47550.invokeStatic(dashboard.clj:340)",
    "api.dashboard$fn__47550.invoke(dashboard.clj:328)",
    "middleware$enforce_authentication$fn__56174.invoke(middleware.clj:113)",
    "api.routes$fn__56324.invokeStatic(routes.clj:64)",
    "api.routes$fn__56324.invoke(routes.clj:64)",
    "routes$fn__56409$fn__56410.doInvoke(routes.clj:108)",
    "routes$fn__56409.invokeStatic(routes.clj:103)",
    "routes$fn__56409.invoke(routes.clj:103)",
    "middleware$catch_api_exceptions$fn__56309.invoke(middleware.clj:436)",
    "middleware$log_api_call$fn__56287$fn__56289.invoke(middleware.clj:364)",
    "middleware$log_api_call$fn__56287.invoke(middleware.clj:363)",
    "middleware$add_security_headers$fn__56229.invoke(middleware.clj:252)",
    "core$wrap_streamed_json_response$fn__62673.invoke(core.clj:67)",
    "middleware$bind_current_user$fn__56179.invoke(middleware.clj:137)",
    "middleware$maybe_set_site_url$fn__56239.invoke(middleware.clj:290)",
    "middleware$add_content_type$fn__56232.invoke(middleware.clj:262)"
  ]
}
```

**Comment by noamtwochairs** [comment]
Also having this issue on 0.32.0 when trying to save a chart made from two questions, stack trace: 
```
Jan 03 22:59:51 ERROR metabase.middleware :: PUT /api/dashboard/12/cards 500 (10 ms) (6 DB calls).
{:message "Dont know what to do with: ",
:type java.lang.IllegalArgumentException,
:stacktrace
("--> models.params$field_form__GT_id.invokeStatic(params.clj:33)"
"models.params$field_form__GT_id.invoke(params.clj:17)"
"models.params$param_target__GT_field_id.invokeStatic(params.clj:69)"
"models.params$param_target__GT_field_id.invoke(params.clj:63)"
"models.params$dashboard__GT_parameter_mapping_field_ids$iter__33485__33491$fn__33492$iter__33487__33493$fn__33494$fn__33495.invoke(params.clj:176)"
"models.params$dashboard__GT_parameter_mapping_field_ids$iter__33485__33491$fn__33492$iter__33487__33493$fn__33494.invoke(params.clj:174)"
"models.params$dashboard__GT_parameter_mapping_field_ids$iter__33485__33491$fn__33492.invoke(params.clj:174)"
"models.params$dashboard__GT_parameter_mapping_field_ids.invokeStatic(params.clj:179)"
"models.params$dashboard__GT_parameter_mapping_field_ids.invoke(params.clj:170)"
"models.params$dashboard__GT_param_field_ids.invokeStatic(params.clj:198)"
"models.params$dashboard__GT_param_field_ids.invoke(params.clj:192)"
"models.dashboard$dashboard_id__GT_param_field_ids.invokeStatic(dashboard.clj:170)"
"models.dashboard$dashboard_id__GT_param_field_ids.invoke(dashboard.clj:166)"
"models.dashboard$update_dashcards_BANG_.invokeStatic(dashboard.clj:210)"
"models.dashboard$update_dashcards_BANG_.invoke(dashboard.clj:203)"
"api.dashboard$fn__53829.invokeStatic(dashboard.clj:340)"
"api.dashboard$fn__53829.invoke(dashboard.clj:328)"
"middleware$enforce_authentication$fn__43924.invoke(middleware.clj:113)"
"api.routes$fn__56044.invokeStatic(routes.clj:64)"
"api.routes$fn__56044.invoke(routes.clj:64)"
"routes$fn__63021$fn__63022.doInvoke(routes.clj:108)"
"routes$fn__63021.invokeStatic(routes.clj:103)"
"routes$fn__63021.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__44059.invoke(middleware.clj:436)"
"middleware$log_api_call$fn__44037$fn__44039.invoke(middleware.clj:364)"
"middleware$log_api_call$fn__44037.invoke(middleware.clj:363)"
"middleware$add_security_headers$fn__43979.invoke(middleware.clj:252)"
"core$wrap_streamed_json_response$fn__63655.invoke(core.clj:67)"
"middleware$bind_current_user$fn__43929.invoke(middleware.clj:137)"
"middleware$maybe_set_site_url$fn__43989.invoke(middleware.clj:290)"
"middleware$add_content_type$fn__43982.invoke(middleware.clj:262)")}
```

**Comment by flamber** [comment]
@camsaul Seems like people are still having problems with this.

**Comment by camsaul** [comment]
yup. I'll take a look

**Comment by agoud1993** [comment]
I'm using metabase version 0.31.2 
mozilla firefox browser version 52.6
I'm trying to build a question from a saved question  and add that to the dashboard. But,  the saving the dashboard failed. below is the screenshot of it. 
any suggestions to solve this issue

![question on q question](https://user-images.githubusercontent.com/45699622/50996142-23179c80-14ef-11e9-94d7-8b8cff8a7bd3.PNG)

**Comment by flamber** [comment]
@agoud1993 
This has been fixed in the upcoming 0.32 version (no release date yet).
You might want to upgrade Firefox - you're using an outdated version with known security issues.

**Comment by manoloah** [comment]
> @agoud1993
> This has been fixed in the upcoming 0.32 version (no release date yet).
> You might want to upgrade Firefox - you're using an outdated version with known security issues.

Any idea when 0.32 will be released? Also is there a way to fix the issues from the customer (our) side while you guys get the release out? 

Thank you for the effort!!

**Comment by flamber** [comment]
@manoloah 
You can use the latest nightly Docker or compile your own version with #9219 merged.
https://hub.docker.com/r/metabase/metabase-head

**Comment by wibo-pipping** [comment]
I ran into this issue today too. I managed to fix it by removing a "corrupt" question from the dashboard.

Steps:
- Add a number of questions with 2 filter fields (1 date and 1 categorical type) to the dashboard
- Link the filters on the Dashboard
- Go into one of the questions and update it removing the Categorical filter type. *Save the question with overwrite.*
- Go back to the dashboard and try to make changes --> Saving now fails.

It seems like the filter field is still linked to the updated question. As the updated question no longer understands the filter field it cases issues.

*Fix:*  
Removing the updated question will allow the dashboard to save again. After you can then re-add the updated question and the dashboard will be able to save.

**Comment by o-rayer** [comment]
Hi,

Still broken on my side as well, is the release date announced for 0.32 with the fix ?

thanks

**Comment by flamber** [comment]
@o-rayer 
No release date yet: https://github.com/metabase/metabase/milestone/72
You can try the master/head release - backup first!: https://hub.docker.com/r/metabase/metabase-head

**Comment by manoloah** [comment]
@flamber is this in your prelease for 0.32?? 

Thanks, 

Manu

**Comment by agoud1993** [comment]
Hi, I've upgraded my metabase from 0.31.2 version to latest and greatest version 0.32.5
I've dashboard and from that dashboard I want to ask a question and save it and use thta saved question on a dashboard. 
I'm able to save the question but I'm not able to view the data from the question which is saved previously on a dashboard.
The dashboard has a date filter.
Please view the image below
![saved question from a question](https://user-images.githubusercontent.com/45699622/56678022-bdab7e00-668f-11e9-952d-cb67c2d848c5.PNG)

**Comment by flamber** [comment]
@agoud1993 That's most likely a different issue, so look at the browser console and Metabase log for any errors and check actual query from the response data.

**Comment by agoud1993** [comment]
@flamber the same question which is not displaying the data on the dashboard is displaying in the data in question level
![saved question level](https://user-images.githubusercontent.com/45699622/56683482-a4103380-669b-11e9-89fc-efb111263581.PNG)

**Comment by flamber** [comment]
@agoud1993 Please use the forum for troubleshooting or create a new issue, because this is not related to this issue.

**Comment by gatsu420** [comment]
@wibo-pipping 
It actually works on my case...thanks!

Versions:
DB: MySQL 5.7.26
Metabase: 0.31.2
Hosted on: AWS
Accessed by: Chrome 75.0.3770.100 (Official Build) (64-bit) on Windows 10 OS Version 1809 (Build 17763.615)
