### ISSUE TITLE
0.31.0 DATE/DATETIME filtering produces error

### ISSUE THREAD

**Issue by dylanjnz** [metabase/metabase#8932]
- Metabase v0.31.0 on Docker, with PostgreSQL DB.
- Databases are in BigQuery.
- Chrome 70.0.3538.77

I've just upgraded to v0.31.0 and have found an issue when trying to run (new and existing) reports with date filters, specifically when using Before/After, Between, and On:

Before/After:
```
No matching signature for operator > for argument types: DATETIME, TIMESTAMP. Supported signatures: ANY > ANY at [2:1123]
```

Between:
```
No matching signature for operator BETWEEN for argument types: DATETIME, TIMESTAMP, TIMESTAMP. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [2:1169]
```

The columns being filtered are either `DATE` and `DATETIME` types.

**Comment by bcbob** [comment]
Have updated to 0.31.0 and questions using DATETIME filters are broken. Filters using DATE field work.

**Comment by bcbob** [comment]
DATE field filters work in Question Builder. 
But are also broken (like DATETIMEs) when accessed via dashboard filters.

Filters for custom sql questions seem to work as before.

This is a serious bug needing an urgent fix! 

Will need to revert to 0.30.4 so long...

**Comment by mazameli** [comment]
@bcbob Are you also querying BigQuery? Haven't been able to reproduce this so far with the Created At field in the Sample Dataset, which is a DATETIME field in an H2 DB.

**Comment by dylanjnz** [comment]
Confirming DATE does fail (with BigQuery):

```
No matching signature for operator > for argument types: DATE, TIMESTAMP. Supported signatures: ANY > ANY at [2:1123]
```

Happy to help debug where possible.

**Comment by bcbob** [comment]
The problem I’m having is not identical to this.

I’m querying MySQL. Question builder queries using datetime filters are no longer producing results on 0.31.0. 
Those using Date are. 

However, dashboard date filters linked to question builder queries fail both with date and datetime types. 

I’m referring to long existing questions and dashboards that worked smoothly on earlier versions and now simply do not produce results. The problem I’m referring to does not produce an error. Just no results where there were results before.

**Comment by lukecarazzo** [comment]
I am having the same issue when upgrading to Metabase V0.31.0 on Windows server running custom install. Pointing to mysql database.

![untitled](https://user-images.githubusercontent.com/43365834/48613596-df902e80-e994-11e8-8eb5-78f43cd68b29.png)

**Comment by mazameli** [comment]
I feel like this issue might be related to https://github.com/metabase/metabase/issues/8927

**Comment by mazameli** [comment]
I'm having trouble reproducing this still. I've tried both with MySQL and BigQuery DBs, with both GUI and SQL questions, both in the query builder and in dashboards, but the only issue I've reproduced is the one reported in #8927. All of my tests have been with _new_ questions though, so I can try creating some questions in an app db with an old version and then upgrading it. Otherwise I'm stumped. Let me know if you have any ideas, @camsaul or @tlrobinson.

**Comment by daneren2005** [comment]
We are having the same issue.  The solution for us was to just take the filter out of the Dashboard altogether.  Is there some way for us to grab exactly what you need to reproduce?  Is there log information or something else that would help?

**Comment by ans-4175** [comment]
I know the problem
0.31.0
```
WHERE `taskforce.ar_payment_recap`.`Tanggal` BETWEEN timestamp('2018-11-01T00:00:00.000Z') AND timestamp('2018-11-10T00:00:00.000Z') ORDER BY `Tanggal` DESC LIMIT 2000
```
0.30.4
```
WHERE timestamp_trunc(CAST(`taskforce.ar_payment_recap`.`Tanggal` AS timestamp), day) BETWEEN timestamp_trunc(CAST(timestamp('2018-11-01T00:00:00.000Z') AS timestamp), day) AND timestamp_trunc(CAST(timestamp('2018-11-17T00:00:00.000Z') AS timestamp), day) LIMIT 2000
```

In 0.31.0 they didn't use timestamp_trunc again for `between` and `on` date filter and our table value format is DATE. That's why.

I wonder which files or lines being refactored from 0.30.4 in 0.31.0?

**Comment by camsaul** [comment]
Same underlying issue as #8927. Closing as a duplicate.

This will be fixed by #8973

**Comment by lukecarazzo** [comment]
Hi Guys, Has anyone found a solution to this as yet? will the fix only be available in the new version?

**Comment by mazameli** [comment]
@lukecarazzo We just released an updated version with a bunch of bug fixes, 0.31.1, [available here](https://github.com/metabase/metabase/releases/tag/v0.31.1), which contains #8973 which we believe should fix this issue.

**Comment by lukecarazzo** [comment]
@maz

Thanks so much.

**Comment by bcbob** [comment]
This particular date problem may be solved.

But on 0.31.1 my dashboard date filters are still broken for GUI question builder questions. There is a "! There was a problem displaying this chart" error on each card on the dashboard. Clicking through to the underlying question passes through the date filter correctly and produces the correct result.

**Comment by lukecarazzo** [comment]
@mazameli 

I use the custom install metabase.jar on windows server. Do you perhaps have a link to the new version in the jar format.

**Comment by lukecarazzo** [comment]
@mazameli

My date filters are also broken even with the latest version applied. I have the same issue as @bcbbob. If I revert back to older version. My date filters work.

**Comment by bcbob** [comment]
My dashboard date filters for GUI questions are broken for single date type filters.
Changing the filter to a date range, and specifying a single date as a date range (eg expressing today as "date between 25-11-2018 and 25-11-2018") causes the dashboard filter to work.

(but this of course breaks custom sql questions on the dashboard that expect a single date type variable to be passed through)

**Comment by lukecarazzo** [comment]
Please see below, this is what I am getting on the Latest version.  metabase v0.31.1 (Latest) - None of the dates filters work at all. If I revert back to version v0.30.4 then all works fine.

![capture1](https://user-images.githubusercontent.com/43365834/48997062-3d700380-f157-11e8-83c3-4e3552989b7a.PNG)
![capture2](https://user-images.githubusercontent.com/43365834/48997063-3d700380-f157-11e8-8ae7-3717a6752dd7.PNG)
![capture3](https://user-images.githubusercontent.com/43365834/48997064-3e089a00-f157-11e8-98bb-1b57dd62e5d0.PNG)
![capture4](https://user-images.githubusercontent.com/43365834/48997065-3e089a00-f157-11e8-85a8-7021a924a732.PNG)
![error](https://user-images.githubusercontent.com/43365834/48997066-3e089a00-f157-11e8-8e5c-1b8c90978c42.PNG)

**Comment by bcbob** [comment]
Great news that this issue is fixed and closed.
When is the next release expected to drop? 
There must be a large number of broken dashboard filters out there longing to get rocking again...

**Comment by bcbob** [comment]
Dashboard date filters still broken for query builder questions on 0.31.2 😌
Have started new issue to avoid confusion.
