### ISSUE TITLE
metabase 0.32.0 can't connect to mysql with SSL

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#9629]
the datawarehouse is MariaDB version 5.5.5-10.0.20 which require SSL.
I use this for "Additional JDBC connection string options:" and it works for v0.31.2

"useSSL=true&requireSSL=true&verifyServerCertificate=no"

so it works great for v0.31.2 but for v0.30.2 I get (after pressing "Save" on the "Add database" page)

java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'LCD_ro'@'10.109.192.100' (using password: YES)

Which I think can be caused by not enabling SSL.

Tip which may or not be relevant:

If I change useSSL=true to useSSL=truex, on v0.31.2 I get 

java.sql.SQLException: The connection property 'useSSL' only accepts values of the form: 'true', 'false', 'yes' or 'no'. The value 'truex' is not in this set.

but of v0.32.0 I still get 

java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'LCD_ro'@'10.109.192.100' (using password: YES)

So it's as if useSSL is not being delivered to the JDBC driver and/or being ignored.

I use the docker image
Browser = Version 73.0.3683.86 (Official Build) (32-bit)
METABASE DB APP is Postgres

**Comment by eladeyal-intel** [comment]
Cam Saul @camsaul 18:59 wrote:

In 0.32.0 we switched to using the MariaDB JDBC driver instead of the MySQL one. Some of the connection options are slightly different. I think you need to use trustServerCertificate=true instead of verifyServerCertificate=no. Give that a try. If that doesn't work this page is probably a good starting point for investigating further. https://mariadb.com/kb/en/library/using-tls-ssl-with-mariadb-java-connector/

**Comment by RobertLowe** [comment]
I can confirm this with MongoDB Atlas BI Connector, and had to fork repos to deploy to heroku with `0.31` in addition to using `useSSL=true&useLocalTransactionState=true`

**Comment by camsaul** [comment]
From that page I linked: The Java system property "-Djavax.net.debug=all" permits logging all TLS exchanges.

**Comment by camsaul** [comment]
Also from that page:

> The Java system property "-Djavax.net.debug=all" permits logging all TLS exchanges.

**Comment by camsaul** [comment]
Let me try to repro this

**Comment by camsaul** [comment]
Ok, reproed. I really wish we could have found out about this  from one of the RC builds 😫 

Fixed with #9631. Please try that branch and verify that it fixes your issue. I'll discuss with the rest of the team tomorrow and see what the plan is for shipping a new build after we're sure it fixes things.

In the meantime you should be able to fix the issue manually if you modify the entry for your database in the `metabase_database` table as follows:

```sql
-- Get the current details. This is a JSON-encoded string
SELECT details 
FROM metabase_database 
WHERE engine = 'mysql' AND name = 'my_db';
-- -> '{"name": "my_db", "password": "bad-password", "host": ...}'

-- Modify the JSON to add a "ssl": true property
-- e.g. '{"ssl": true, "name": "my_db", "password": "bad-password", "host": ...}'

-- Save the modified JSON details
UPDATE metabase_database
SET details = '{"ssl": true, "name": "my_db", "password": "bad-password", "host": ...}'
WHERE engine = 'mysql' AND name = 'my_db';
```

If anyone tries that out ping please let us know if it worked for you.

**Comment by camsaul** [comment]
Fixed by #9631

**Comment by eladeyal-intel** [comment]
Unfortunately this still does not work for me - using "version v0.32.1 Built on 2019-03-29" (from dockerhub) 

I tried various connection strings..

With only "trustServerCertificate=1" I get "java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'gnss_ft_dev_ro'@'10.109.192.100' (using password: YES)" which I learnt to associate with client trying to not use SSL.

with "useSSL=1&trustServerCertificate=1" I get the same

with "useSSL=true&trustServerCertificate=1" (see the difference? true instead of 1) I get "java.sql.SQLNonTransientConnectionException: Could not connect to maria3021-is-lc-in.icloud.intel.com:3307 : Unsupported record version Unknown-0.0
"

I shall now test v0.32.4

**Comment by camsaul** [comment]
can you try `trustServerCertificate=true`?

**Comment by eladeyal-intel** [comment]
@camsaul 

useSSL=true&requireSSL=true&trustServerCertificate=1
and also useSSL=true&requireSSL=true&trustServerCertificate=true  ==> java.sql.SQLNonTransientConnectionException: Could not connect to HOSTNAME:3307 : Unsupported record version Unknown-0.0

useSSL=1&requireSSL=true&trustServerCertificate=true ==> java.sql.SQLNonTransientConnectionException: Could not connect to HOSTNAME:3307 : Unsupported record version Unknown-0.0

useSSL=1&requireSSL=true&trustServerCertificate=1 ==> 
java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'USERNAME'@'10.109.192.100' (using password: YES)

requireSSL=true&trustServerCertificate=1 
and also requireSSL=true&trustServerCertificate=true

==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'USERNAME'@'10.109.192.100' (using password: YES)


trustServerCertificate=1 and also trustServerCertificate=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'USERNAME'@'10.109.192.100' (using password: YES)

**Comment by eladeyal-intel** [comment]
@camsaul please unclose ... help would be appreciated

**Comment by camsaul** [comment]
How about with the `useLocalTransactionState` option like suggested?

**Comment by camsaul** [comment]
Did that work @eladeyal-intel ?

**Comment by eladeyal-intel** [comment]
@camsaul it's complicated, still checking :-)

**Comment by eladeyal-intel** [comment]
@camsaul  

No help (version v0.32.4)

```
useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

useSSL=true&useLocalTransactionState=true ==> java.sql.SQLNonTransientConnectionException: Could not connect to HOSTNAME:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true ==> java.sql.SQLNonTransientConnectionException: Could not connect to HOSTNAME:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true ==> java.sql.SQLNonTransientConnectionException: Could not connect to HOSTNAME:3307 : Unsupported record version Unknown-0.0

useSSL=1&requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

useSSL=1&requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

trustServerCertificate=1&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

trustServerCertificate=true&useLocalTransactionState=true ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'UUUU'@'10.109.192.100' (using password: YES)

```

**Comment by camsaul** [comment]
The MariaDB website has an entire page discussing JDBC driver/SSL connection issues:

https://mariadb.com/kb/en/library/using-tls-ssl-with-mariadb-java-connector/

**Comment by camsaul** [comment]
Most interesting things from that page:

#### Getting SSL protocol version & cipher for a given user

> java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user
> This can occur for a number of reasons:
> 
> *  The user / password is incorrect.
> *  Some SSL options have been set on the user. Can be checked using
> 
> ```sql
> select SSL_TYPE, SSL_CIPHER, X509_ISSUER, X509_SUBJECT 
> FROM mysql.user u 
> where u.User = '<myUser>'; 
> ```
> and the connection attempt doesn't meet those requirements.

#### `enabledSslProtocolSuites` option

> During TLS/SSL negotiation, the client normally indicates the maximum level supported, but before 10.2, YaSSL doesn't recognize the TLSv1.2 flag and then doesn't fallback to theTLSv1.1 protocol.

> The MariaDB Java driver by default uses only TLSv1, TLSv1.1 protocol. If the servers are MariaDB on Unix or version >= 10.2 , consider adding TLSv1.2 protocol. This can be set using the "enabledSslProtocolSuites" option (example: enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2).

#### `enabledSSLCipherSuites` option

> In addition to the protocol, the driver relies on the Java default cipher list. The Java default enabled ciphers are listed here. JAVA allows cipher suites to be removed/excluded from use in the security policy using the Java system property "jdk.tls.disabledAlgorithms". The specific list of ciphers to be used can be set using the "enabledSslCipherSuites" driver option (example : "enabledSSLCipherSuites=TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,...")
> 
> Due to import regulations in some countries, the Java Oracle implementation provides a default cryptographic jurisdiction policy file that limits the strength of cryptographic algorithms.

#### `-Djavax.net.debug=all` 
> The Java system property "-Djavax.net.debug=all" permits logging all TLS exchanges.

@eladeyal-intel @s-higuma  (and everyone else still having problems) can you please run the first query to get the protocol version and cipher the server expects and then try setting the appropriate `enabledSslProtocolSuites` and `enabledSSLCipherSuites` options? It sounds like if we can figure those out then the connections should work. Once we figure that out I'll try to come up with a way for Metabase to figure these out automatically

**Comment by eladeyal-intel** [comment]
When I try this I get `ERROR 1142 (42000): SELECT command denied to user 'XXX'@'YYY' for table 'user'` . This is enterprise environment so I don't have root access to the DB. I submitted a request to get this data.

**Comment by eladeyal-intel** [comment]
@camsaul 
In the meantime I tried running this with `-Djavax.net.debug=all`  . So this is v0.32.5 JAR running on Java 9.0.1 on Windows 10 

```
04-27 13:25:26 DEBUG middleware.log :: GET /api/database 200 5 ms (3 DB calls) Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (42 total active threads)
trigger seeding of SecureRandom
done seeding SecureRandom
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
%% No cached client session
update handshake state: client_hello[1]
upcoming handshake states: server_hello[2]
*** ClientHello, TLSv1.2
RandomCookie:  random_bytes = {***}
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension status_request_v2
CertStatusReqItemV2: ocsp_multi, OCSPStatusRequest
    ResponderIds: <EMPTY>
    Extensions: <EMPTY>
CertStatusReqItemV2: ocsp, OCSPStatusRequest
    ResponderIds: <EMPTY>
    Extensions: <EMPTY>
Extension status_request: ocsp, OCSPStatusRequest
    ResponderIds: <EMPTY>
    Extensions: <EMPTY>
***
clojure-agent-send-off-pool-6, WRITE: TLSv1.2 Handshake, length = 232
[Raw write]: length = 237
<stuff deleted>
[Raw read]: length = 5
0000: 16 00 00 02 FF                                     .....
[Raw read]: length = 21
0000: 13 04 23 30 38 53 30 31   42 61 64 20 68 61 6E 64  ..#08S01Bad hand
0010: 73 68 61 6B 65                                     shake
clojure-agent-send-off-pool-6, received EOFException: error
clojure-agent-send-off-pool-6, handling exception: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
clojure-agent-send-off-pool-6, SEND TLSv1.2 ALERT:  fatal, description = handshake_failure
clojure-agent-send-off-pool-6, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 02 28                               ......(
clojure-agent-send-off-pool-6, called closeSocket()
04-27 13:25:35 DEBUG middleware.log :: POST /api/database 400 733 ms (0 DB calls) Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (42 total active threads) 
{:valid false,
 :dbname "java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'USERNAME'@'xx.xx.xx.xx' (using password: YES)",
 :message "java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'USERNAME'@'xx.xx.xx.xx' (using password: YES)"}

04-27 13:25:35 DEBUG middleware.log :: GET /api/database 200 6 ms (3 DB calls) Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (42 total active threads)

**Comment by eladeyal-intel** [comment]
@camsaul - I don't know how much help this gives
```
select SSL_TYPE, SSL_CIPHER, X509_ISSUER, X509_SUBJECT FROM mysql.user u WHERE u.User = 'UUUUUUUUU';
+----------+------------+-------------+--------------+
| SSL_TYPE | SSL_CIPHER | X509_ISSUER | X509_SUBJECT |
+----------+------------+-------------+--------------+
| ANY      |            |             |              |
+----------+------------+-------------+--------------+
1 row in set (0.00 sec)
```

**Comment by eladeyal-intel** [comment]
@camsaul any ideas?

**Comment by camsaul** [comment]
Sorry @eladeyal-intel, I'm really not sure what we need to do to get this working. Can you try 

```
enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2
```

as suggested in the MariaDB debugging page I linked?

**Comment by eladeyal-intel** [comment]
@camsaul no help:

```
enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

useSSL=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=1&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=1&requireSSL=true&trustServerCertificate=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

useSSL=1&requireSSL=true&trustServerCertificate=1&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

requireSSL=true&trustServerCertificate=1&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

requireSSL=true&trustServerCertificate=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

trustServerCertificate=1&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

trustServerCertificate=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

useSSL=true&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=true&requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLNonTransientConnectionException: Could not connect to xxxxx.com:3307 : Unsupported record version Unknown-0.0

useSSL=1&requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

useSSL=1&requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

requireSSL=true&trustServerCertificate=1&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

requireSSL=true&trustServerCertificate=true&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

trustServerCertificate=1&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)

trustServerCertificate=true&useLocalTransactionState=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2 ==> java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'uuuuuu'@'xx.xx.xx.xx' (using password: YES)
```

**Comment by yoginitiate** [comment]
@eladeyal-intel @camsaul i have the same problem and it's still unsolved.

The funny thing is, I create another connection with same configuration and it's work.

**Comment by eladeyal-intel** [comment]
I did not get to testing this in v0.33

@yoginitiate If you still have the 2 catabase connections - maybe you can try to connect to the metabase app database and run `SELECT * FROM metabase_database;` and look to see the differences?

If you attach the print to this ticket then make sure you delete passwords and other sensitive information!

**Comment by yoginitiate** [comment]
now is working (both) :confused: 

@eladeyal-intel  this is the configuration

`old`
![Selection_436](https://user-images.githubusercontent.com/24633363/60708035-4f105980-9f37-11e9-868d-961715142a0a.png)

`new`
![Selection_435](https://user-images.githubusercontent.com/24633363/60708046-55063a80-9f37-11e9-996a-87cd8794ce59.png)

**Comment by hankaaron** [comment]
I had the same problem as discussed above. I'm running metabase in a Docker environment and  connecting to a MySQL database on Google Cloud Platform. I solved the problem (somewhat) using the following connection string:

useSSL=true&requireSSL=true&trustServerCertificate=true&serverSslCert=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/server-ca.pem

The only problem is that it only works if I allow unsecured connections on the MySQL Server database side. So I'm then using the client (in this case, the Metabase App) to initiate the secure connection. I'm still concerned because I can't tell if I'm actually using an encrypted channel. I checked the logs on GCP and apparently connections to the database are not logged.

**Comment by renanceratto** [comment]
> I had the same problem as discussed above. I'm running metabase in a Docker environment and connecting to a MySQL database on Google Cloud Platform. I solved the problem (somewhat) using the following connection string:
> 
> useSSL=true&requireSSL=true&trustServerCertificate=true&serverSslCert=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/server-ca.pem --- (after I copied my server-ca to that location)
> 
> The only problem is that it only works if I allow unsecured connections on the MySQL Server database side. So I'm then using the client (in this case, the Metabase App) to initiate the secure connection. I'm still concerned because I can't tell if I'm actually using an encrypted channel. I checked the logs on GCP and apparently connections to the database are not logged.

Hankaaron, did you try to use local IP connection rather then external IP connection? its much easier and it don't need to use ssl connection, because its internal.
If your docker is running on GCP, it could be an option.
I'm using this way and didn't have problem to connect to my Cloud SQL (MySQL). No connection parameters needed

**Comment by ogeagla** [comment]
What's your load balancing situation, if there is any in the mix? It could be that SSL is being terminated at the load balancer layer: https://cloud.google.com/load-balancing/docs/ssl/

**Comment by hankaaron** [comment]
This is a dev database to test out metabase. But the production database will be external to GCP, so local ip connections in GCP are a nogo.

**Comment by hankaaron** [comment]
> What's your load balancing situation, if there is any in the mix? It could be that SSL is being terminated at the load balancer layer: https://cloud.google.com/load-balancing/docs/ssl/

No load balancers or proxy  servers are between Metabase and the MySQL database.

**Comment by renanceratto** [comment]
Is your Mysql Cloud SQL 2nd generation?
I think this error is all about mysql version.
I've tryied with my mysql cloud sql using external IP and works

**Comment by eladeyal-intel** [comment]
Tested again on `v0.32.9`... Still doesn't work.

**Comment by eladeyal-intel** [comment]
I tested now with `v0.32.10` and also `v0.33.0-RC1` and I got it to work by specifying either `enabledSslProtocolSuites=TLSv1.1&trustServerCertificate=true` or `enabledSslProtocolSuites=TLSv1&trustServerCertificate=true`. You would think that specifying `enabledSslProtocolSuites=TLSv1.1,TLSv1.2&trustServerCertificate=true` would fallback to v1.1 if v1.2 fails but it does not seem to work that way.

**Comment by kurrestahlberg** [comment]
@eladeyal-intel's tip got this working for me too. It definitely seems that TLS v1.2 does not work, but fallback to v1.2 does not work either.

**Comment by willeeh** [comment]
is this issue still happening on v0.33.6? I just checked and I'm not able to connect with all suggestions mentioned above.

**Comment by flamber** [comment]
@willeeh So are you using 0.33.6 - can you post Diagnostic Info from Admin > Troubleshooting?
Which errors are you seeing the Metabase log and the MySQL log?
Which version of MySQL?

**Comment by willeeh** [comment]
@flamber Diagnostic info:
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-heroku-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "4.4.0-1048-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "h2"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

We are using BI Connector (hosted in MongoDB Atlas), I could connect from MySQL Workbench following this tutorial: https://docs.mongodb.com/bi-connector/current/connect/mysql/

The problem is related with SSL, I got the following error:
```
2019-11-25T19:11:58.972393+00:00 app[web.1]: 11-25 19:11:58 ERROR driver.util :: Database connection error
2019-11-25T19:11:58.972404+00:00 app[web.1]: java.sql.SQLException: Could not connect to address=(host=xyz-cluster-biconnector-rxlun.mongodb.net)(port=27015)(type=master) : ssl is required when using cleartext authentication
2019-11-25T19:11:58.972406+00:00 app[web.1]: at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:262)
2019-11-25T19:11:58.972410+00:00 app[web.1]: at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
2019-11-25T19:11:58.972411+00:00 app[web.1]: at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:610)
2019-11-25T19:11:58.972413+00:00 app[web.1]: at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
2019-11-25T19:11:58.972415+00:00 app[web.1]: at org.mariadb.jdbc.Driver.connect(Driver.java:86)
2019-11-25T19:11:58.972416+00:00 app[web.1]: at java.sql.DriverManager.getConnection(DriverManager.java:664)
2019-11-25T19:11:58.972417+00:00 app[web.1]: at java.sql.DriverManager.getConnection(DriverManager.java:208)
2019-11-25T19:11:58.972419+00:00 app[web.1]: at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
2019-11-25T19:11:58.972420+00:00 app[web.1]: at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
2019-11-25T19:11:58.972421+00:00 app[web.1]: at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
2019-11-25T19:11:58.972422+00:00 app[web.1]: at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
2019-11-25T19:11:58.972424+00:00 app[web.1]: at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
2019-11-25T19:11:58.972425+00:00 app[web.1]: at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
2019-11-25T19:11:58.972427+00:00 app[web.1]: at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
2019-11-25T19:11:58.972428+00:00 app[web.1]: at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
2019-11-25T19:11:58.972430+00:00 app[web.1]: at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
2019-11-25T19:11:58.972431+00:00 app[web.1]: at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
2019-11-25T19:11:58.972432+00:00 app[web.1]: at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:159)
2019-11-25T19:11:58.972434+00:00 app[web.1]: at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
2019-11-25T19:11:58.972435+00:00 app[web.1]: at metabase.driver.sql_jdbc$fn__67312.invokeStatic(sql_jdbc.clj:35)
2019-11-25T19:11:58.972436+00:00 app[web.1]: at metabase.driver.sql_jdbc$fn__67312.invoke(sql_jdbc.clj:34)
2019-11-25T19:11:58.972438+00:00 app[web.1]: at clojure.lang.MultiFn.invoke(MultiFn.java:234)
2019-11-25T19:11:58.972439+00:00 app[web.1]: at metabase.driver.util$can_connect_with_details_QMARK_$fn__19311.invoke(util.clj:31)
2019-11-25T19:11:58.972440+00:00 app[web.1]: at metabase.util$do_with_timeout$fn__6284.invoke(util.clj:334)
2019-11-25T19:11:58.972442+00:00 app[web.1]: at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
2019-11-25T19:11:58.972443+00:00 app[web.1]: at clojure.lang.AFn.call(AFn.java:18)
2019-11-25T19:11:58.972444+00:00 app[web.1]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-11-25T19:11:58.972446+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-11-25T19:11:58.972447+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-11-25T19:11:58.972449+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748)
2019-11-25T19:11:58.972450+00:00 app[web.1]: Caused by: java.sql.SQLException: ssl is required when using cleartext authentication
2019-11-25T19:11:58.972452+00:00 app[web.1]: at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:729)
2019-11-25T19:11:58.972453+00:00 app[web.1]: at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:507)
2019-11-25T19:11:58.972454+00:00 app[web.1]: at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
2019-11-25T19:11:58.972456+00:00 app[web.1]: ... 28 more
```

Additional JDBC parameters configured: `useSSL=true&trustServerCertificate=true`. I've tried all possible options discussed in this thread without success.

**Comment by flamber** [comment]
@willeeh Okay, that looks like a completely different problem. See the error:
`ssl is required when using cleartext authentication`
https://docs.mongodb.com/bi-connector/master/connect/mysql/#connect-from-mysql-with-authentication-and-tls-ssl
Looks like Metabase would need to support the BI Connector as a specific driver. You can upvote the driver request by clicking :+1: on the first post of #6584.

**Comment by camsaul** [comment]
I've spent a lot of time looking at this when the issue first happened and I had trouble reproducing it... it might be a tricky bug to diagnose and fix.

**Comment by paoliniluis** [comment]
Just hit this one, the full reproduction is here: https://github.com/paoliniluis/metabase-mysql-ssl

**Comment by osrl** [comment]
We're trying to connect to MongoDB Atlas BI Connector and can't connect to it using 0.45. I've tried every JDBC connection strings options above but no luck

**Comment by jjchiw** [comment]
I have the same issue trying to connect to `mongosqld` from `mongo bi connector`.

From DBeaver I can't connect using the `maria driver` the same issue as in `metabase` `(conn=11) ssl is required when using cleartext authentication`

I tried to use https://github.com/lokyGit/metabase-mongobi-connector but it ends using the `maria driver` then I said, ok let's fork it with using https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj and create it with `mysql-connector` but no :( it was beyond my time and comprehension of how to make it work :/

At the end I just went back to `metabase/metabase:v0.31.2` and it's working with this jdbc parameters `useSSL=true&useLocalTransactionState=true&verifyServerCertificate=no`

I think there should be a way to override the `maria` driver with the `mysql-connector` something like copying the `jar` in the plugins folder or something like that.

Thanks :)

**Comment by paoliniluis** [comment]
Closing this since I just connected to MySQL with SSL a few days ago
