### ISSUE TITLE
If instance was set up with HTTPS, log in over HTTP stops working

### ISSUE THREAD

**Issue by anandabudi** [metabase/metabase#9630]
Hi Metabase team,

I just tried the latest build of 0.32.0 this morning, I upgraded from Metabase 0.30.5 to 0.32.0. But I found another problem.

After I  upgraded  to the latest version, I can't log in with my credential or even by using Google SSO. When I checked the log, it only showed me this line without any explanation

> 03-29 03:59:10 DEBUG middleware.log :: GET /api/user/current 401 (387 µs) (0 DB calls).
"Unauthenticated"

When I checked my browser, the console showed me this error 
![Screen Shot 2019-03-29 at 11 18 54](https://user-images.githubusercontent.com/8414151/55209347-a6a27900-5214-11e9-9c04-447982f4d682.png)

I tried to clear the cookies in my browser and also try to login to the website with incognito mode. The same problem with authentication still persist.

Since I can't downgrade to 0.30.5 anymore, I decided to downgrade Metabase to 0.31.2 version, and I can login without any problem, so probably somethings wrong with the 0.32.0 ? 

Thanks !

**Comment by camsaul** [comment]
Are you blocking cookies?

**Comment by anandabudi** [comment]
@camsaul not really, I tried it also with different browser (Safari), and the result is still the same. I also tried it in different computer, but the result is still the same. I can't log in.

**Comment by anandabudi** [comment]
@camsaul or maybe I built the jar from the source code in the wrong way ?

I use this command to build the JAR though

> ./bin/build no-translations

**Comment by camsaul** [comment]
Does it work with the JAR from our Downloads page?

**Comment by camsaul** [comment]
Can you include the response for the `google_auth` request before the `current_user` request?

**Comment by danaivehr** [comment]
Hi!

I'm experiencing a similar problem after upgrading from 0.30 to 0.32 and 0.32.1 (JAR).
Tryed on clean run with all setup process and empty base too: i can pass throug all setup process, but login doesn't work then.

In my case problem seems to be concerned with apache ProxyPass:
* I use apache proxing from (let's say) my-domain.org/metabase to http://localhost:3000
* **Locally through http://localhost:3000 login in is working fine**
* With proxing from my-domain.org/metabase i get ```GET /api/user/current 401 (357 µs) (0 DB calls). "Unauthenticated"```

I can provide some additional data on your request to help in investigation

**Comment by danaivehr** [comment]
Oh, okay, localhost:3000 now have the same issue. Seems to be some cache trick...

**Comment by atranel** [comment]
Same issue. I download new version 0.32.1 and started as usually instead of 0.31.2. I get to login page and it fails to auth even tho password is correct and page is not showing actual password fail. I use PostgreSQL as database for Metabase.

**Comment by anandabudi** [comment]
Hi @camsaul, sorry for the late reply.

Here is the screenshot from the `google_auth` response

![Screen Shot 2019-04-01 at 09 36 18](https://user-images.githubusercontent.com/8414151/55300486-e611d500-5461-11e9-86a8-0c7b3e4f139a.png)

And yes, I used the source code from the release page, and build the JAR by myself.

**Comment by anandabudi** [comment]
> Oh, okay, localhost:3000 now have the same issue. Seems to be some cache trick...

I used localhost:3000 with `liquibase` as the default database, and there's no problem with the login. But yes, my main database is PostgreSQL, and it seems, this is a problem with PostgreSQL.

**Comment by anandabudi** [comment]
@camsaul @atranel @danaivehr 

It's the problem with the certificate, right now, I'm using a real domain with a valid certificate, and I can login without any problem.

🤔 I think, this is going to be a problem if someone wants to use Metabase in their development environment without any valid certificate.

**Comment by atranel** [comment]
Hmm, yes, I have the issue on development server without certificate which is used on production server.

**Comment by jlisyc** [comment]
Also tried with standar already user admin (from metadata 0.31.2) with 0.32.1 and can not login.

**Comment by atranel** [comment]
Problem is in api/user.clj file?
![image](https://user-images.githubusercontent.com/42370527/55329213-559db980-548e-11e9-8d91-fae3d05a0c89.png)

**Comment by camsaul** [comment]
Ok, I see what your problem is.

If Metabase was accessed over HTTPS when you first set up the instance, it assumes (incorrectly in your case) future authentication requests will be made over HTTPS; it sets a session cookie with the `Secure` attribute, [which means the cookie will not be sent over HTTP requests](https://en.wikipedia.org/wiki/Secure_cookie). Of course, logging in over HTTP is super-insecure; sending your session token back to your Metabase server over HTTP is pretty bad too, because a bad actor could use it to assume your identity and access your Metabase instance. This is why we set the `Secure` attribute.

Try changing the http:// to an https:// in your browser, and it should fix your issue. I'd highly recommend setting up the environment you use to host Metabase to always redirect HTTP requests to HTTPS, and using HTTPS Everywhere plugin.

For a local development instance (e.g. http://localhost:3000) Metabase will set Session cookies without the `Secure` attribute, and things will work normally. Thus you will not run into issues unless you attempt to access an instance that was already proven to be accessible over HTTPS over HTTP.

If you're doing some weird development things where this is necessary, you can update the value of `site-url` Setting in the `setting` Table by changing `https://` to `http://`. Keep in mind doing so will make your Metabase instance less secure.

There are definitely a few things that should be improved to make weird development edge cases less confusing -- perhaps disabling insecure logins entirely if Metabase is set up over HTTPS, or adding support within Metabase to automatically redirect HTTP requests to HTTPS, or adding an option to allow both secure and insecure logins and only include the `Secure` attribute if the actual login request was made over HTTPS (again, this makes your security worse, but insecure and working is probably a better experience for you guys than secure and confusingly seeming like it's not working).

**Comment by anandabudi** [comment]
Ah I see, thanks for the detailed explanation @camsaul.

That's why, when I set up the instance directly in the dev environment with HTTP, the login is working without any problem. But, if I use my backup database, which is set up with HTTPS instance, the login is not working until I use the HTTPS domain over my development environment.

**Comment by atranel** [comment]
hmm, I turned developer server to http only, turned all SSL/http in starting bash, but got same problem. Maybe it is because I dump-restore database from production server running https version?

**Comment by camsaul** [comment]
@atranel Metabase keeps a "site URL" stored in the `setting` table in a row with `key = 'site-url'`. This is what it looks at when it decides whether to include the `Secure` attribute.

Having things break in weird ways like this isn't a good experience for anyone so I'm looking at what tweaks I should make to get things working for everyone in this situation without sacrificing security for the majority of Metabase users. Simply looking at the protocol used to make the login request can be tricky because people very commonly deploy Metabase behind `nginx` or a load balancer that handles SSL termination rather than having Metabase handle it itself. Looking at `X-Forwarded-For` and adding `Secure` based on that might be the way to go.

**Comment by danaivehr** [comment]
@camsaul 

I've just reproduced issue in my case. It doesn't seem to be exactly like your descriprtion.

Environment:
* Some site on address https://somesite.somedomain.org on apache2
* SSL certificate on the main site
* ProxyPass /metabase to http://localhost:3000
* Please note, that metabase is http (w/o ssl), so ProxyPass is from outer https to local http

Reproducing:
* Take old metabase database v0.30 - login is working
* **It's important, that it has default link "http://localhost:3000" in general admin setting** (http://localhost:3000/admin/settings/general)
* Replace old JAR v0.30 with new jar v0.32
* Run JAR and wait for all update procedures
* -> Now i can login from http://localhost:3000 and **can't** login from https://somesite.somedomain.org/metabase
* Then change link to "https://somesite.somedomain.org/metabase" in general admin setting (http://localhost:3000/admin/settings/general)
* -> Now i can't login neither from https://somesite.somedomain.org/metabase nor from http://localhost:3000

Reproduced 3 times.

Could this base link setting be used in login process?

**Comment by camsaul** [comment]
Yeah @danaivehr that's exactly the problem I've described here. If you tell Metabase the site URL is something with HTTPS it adds a `Secure` attribute to session cookies so they aren't sent back to the server over HTTP. It's a big security improvment but if you do something like what you're describing it breaks things.

**Comment by danaivehr** [comment]
So it should be some explicit checkbox like "Don't send cookies to http" with description and warning about reverse proxing, if one set some "https://" string in that field...

**Comment by camsaul** [comment]
@danaivehr we set that field automatically for most people and ideally we don't want to add any more knobs for people to configure if we can avoid them. The more configuration options Metabase has, the harder it gets to use. I'm working on a way to have this work automatically in a way where no one besides me has to think about it

**Comment by atranel** [comment]
> 
> 
> @atranel Metabase keeps a "site URL" stored in the `setting` table in a row with `key = 'site-url'`. This is what it looks at when it decides whether to include the `Secure` attribute. So you'd have to edit that row in the Metabase application database to get it to stop making all logins secure.
> 
> Something like
> 
> ```sql
> UPDATE setting
> SET value = 'http://localhost:3000'
> WHERE key = 'site-url'
> ```
> 
> Having things break in weird ways like this isn't a good experience for anyone so I'm looking at what tweaks I should make to get things working for everyone in this situation without sacrificing security for the majority of Metabase users.
> 
> Simply looking at the protocol used to make the login request can be tricky because people very commonly deploy Metabase behind `nginx` or a load balancer that handles SSL termination, rather than having Metabase handle it itself.
> 
> Looking at `X-Forwarded-For` and adding `Secure` based on that might be the way to go. Open to any other suggestions
Hello,
I know, I changed the site-url in the table to http://10.31.1.1:3000 and restarted Metabase and it started. I have the issue now with production server as it is also private server getting https from apache reverse proxy on another machine. site-url is https:\\something.eu\mb-aux, but actual server running metabase is 10.34.1.203 and not server with apache2.

**Comment by camsaul** [comment]
@atranel Metabase is really not set up to serve a dev instance and production instance from the same database. I would very highly recommend against doing that. Clone the database or something first.

Anyways I think I'm going to tweak the logic so it adds the `Secure` attribute based on the protocol in the `Origin` header of the authentication request, which means logins over HTTPS will get `Secure` cookies and if you are logging in over HTTP for whatever reason (hopefully only for local development purposes) you will get a cookie without the `Secure` attribute. Then everything should work for everybody with no more confusion. Expect that change in a 0.32.2 release later today

**Comment by danaivehr** [comment]
@camsaul that the best way for sure, if you manage to work this case around. Hope there is a common way to understand, that you get request through reverse proxy from https to http

**Comment by camsaul** [comment]
@danaivehr yup,  `Origin` works in that case, I've verified that locally in the past with a Metabase instance I've set up on Elastic Beanstalk where the Elastic Load Balancer to handle SSL termination (i.e., HTTPS requests are sent to the ELB and the ELB forwards them as HTTP requests to the Metabase instances)

**Comment by atranel** [comment]
@camsaul Yeah, database is not same. Basically two servers running Metabase and once a day is database for Metabase dump-restored to backup server together with databases feeding data. It is prepared for failure switching.

**Comment by danaivehr** [comment]
> @danaivehr yup, `Origin` works in that case

Great! Looking forward for this improvement

**Comment by camsaul** [comment]
Fixed by #9668

**Comment by atranel** [comment]
hmm, reverse proxy scenario is still not working for me (logging). Development copy is running and logging ok. Should I set some ProxyPassReverseCookiePath into reverse proxy setting in Apache2?

**Comment by atranel** [comment]
hmm, reverse proxy scenario is still not working for me (logging). Development copy is running and logging ok. Should I set some ProxyPassReverseCookiePath into reverse proxy setting in Apache2?

**Comment by yaey** [comment]
hey, we have the same problem as atranel (metabse sits behind nginx).
we tried setting the x-forwarded-proto and origin headers manualy to http
and also changing the scheme to http .. still didnt work.
Are we missing some cookie forwarding rules?

alternative, may i propose adding a custom header? something like X-Use-Https?
then you can avoid having to add a checkbox in the UI, but the nginx admins can still override the settings?

**Comment by danaivehr** [comment]
Can confirm, problem with reverse proxy still exsists on a fresh 0.32.2

**Comment by jonty-comp** [comment]
I'm not sure if i'm getting the same issue, but just tried setting Metabase up for the first time in Docker behind an nginx SSL proxy, and whilst all the routes and assets are correctly reading my subdirectory of `/metabase/` from the site URL setting, the `/api/session` call is returning a set-cookie with a path of `/api` instead of `/metabase/api`, so the subsequent call to `/api/user/current` is failing as no cookie is passed.

**Comment by danaivehr** [comment]
@camsaul 
from last comments it seems the issue still exists. Are we all have some misconfiguration issue? Should we reopen this or create a new one?

**Comment by danaivehr** [comment]
Hurray, login works well on 0.32.3

**Comment by madhurk** [comment]
Hi all, 

I updated from v0.31.2 to v0.32.3 and Google SSO stopped working. Don't think it's related to this change, but wondering if anyone else is seeing the issue. We were setup to use https:// from the very beginning. What I'm seeing is that after Google authentication goes through, but the application fails to redirect and stays on on the login screen. 

Any help will be much appreciated. Thanks!

**Comment by anandabudi** [comment]
And now, I have problem with Google SSO when upgrading Metabase to 0.32.3 😅

**Comment by camsaul** [comment]
@anandabudi the Google Auth issue will be fixed in Metabase 0.32.4 which will be out in the next hour or so

**Comment by anandabudi** [comment]
@camsaul ah thanks for the quick reply ! 😄 Yes, hopefully it will be stable in the next version
