### ISSUE TITLE
Stacking Bar Chart has issue with displaying added questions in different colours. All questions in the chart have the same description

### ISSUE THREAD

**Issue by shrike71** [metabase/metabase#9636]
Adding a second question to a barchart to display as a stack seems to have broken (this used to work). The effect seems to be that although the question data seems to be available and working, the labels and colours identifying the two questions are IDENTICAL, and don't seem to be able to be changed.

![stacked_bar_issue](https://user-images.githubusercontent.com/748514/55235599-d7d77500-5225-11e9-9935-64f3e0a107f3.png)

I first saw this in a recent build of 0.32.0-RC, and it seems to have propagated into the 0.32 version.

Database is PostGres 10.4.
System is Ubuntu 18.04 with Docker version 18.09.3, build 774a1f4
Issue evident in both jar file and Docker image version
Both jar and docker image produced from latest git master (0.32) without visible issues to either

I can see this in both the Docker version and the jar file version.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by bgaillard** [comment]
Hi, we also encoutered color problems after updating Metabase from version `0.31.0` to version `0.32.0`.

Most of the charts where we used colors have now only one color. 

For example on the following charts it seems that one of the series / questions disappeared. 

**With version `0.31.0`**

![before-update-2](https://user-images.githubusercontent.com/1327782/55247076-f863f700-5246-11e9-92fa-255015ec1705.png)


**With version `0.32.0`**

![after-update-2](https://user-images.githubusercontent.com/1327782/55247063-ef732580-5246-11e9-8806-e50505df34a2.png)

We use the Docker image using an explicit `0.32.0` version.

We have lot's of report, this issue is critical for us so we came back to version `0.31.0` for now.

**Comment by ibruque** [comment]
Same here!

**Comment by javiercr** [comment]
We're also experiencing problems with colors and series on bar chats.

**Comment by camsaul** [comment]
@shrike71 if you saw this in the RC build, why didn't you open an issue then 😓

**Comment by tlrobinson** [comment]
I believe this only applies to "dashboard multiseries" (not single questions with 2+ metrics or 1 metric + 2 breakouts) where the aggregation column name is the same. Can you confirm that is the case?

Commit 84f8e8cf4bfa5b1792a5be5e43150fe5404b78ce likely introduced this. 

PR #9673

**Comment by contradironee** [comment]
> I believe this only applies to "dashboard multiseries" (not single questions with 2+ metrics or 1 metric + 2 breakouts) where the aggregation column name is the same. Can you confirm that is the case?
> 
> Commit [84f8e8c](https://github.com/metabase/metabase/commit/84f8e8cf4bfa5b1792a5be5e43150fe5404b78ce) likely introduced this.
> 
> PR #9673

Yes, this is the case for me. Happens when you add multiple questions to one view, whereas questions that are "grouped by" already are fine.

**Comment by shrike71** [comment]
@camsaul 

re originally seeing it in 0.32.0-RC ... apologies. I thought that it had been fixed, but it turned out that what i was checking on 0.32 was a multiple breakout, and not a superimposed multiseries, as i had originally tried.

**Comment by camsaul** [comment]
Fixed by #9673

**Comment by AndrewMBaines** [comment]
Still a problem with the y-axis labels being the same. One of these should be Volume, not value.
![image](https://user-images.githubusercontent.com/35726871/55538269-f91ce300-56b5-11e9-9713-3182e5e31d78.png)

**Comment by MchlUh** [comment]
> I believe this only applies to "dashboard multiseries" (not single questions with 2+ metrics or 1 metric + 2 breakouts) where the aggregation column name is the same. Can you confirm that is the case?
> 
> Commit [84f8e8c](https://github.com/metabase/metabase/commit/84f8e8cf4bfa5b1792a5be5e43150fe5404b78ce) likely introduced this.
> 
> PR #9673

I am experiencing similar issue with one single question : 
https://discourse.metabase.com/t/issue-with-stacked-bar-charts/13039
