### ISSUE TITLE
Had to roll back to 0.31 - dashboards stop populating

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#9693]
Just wanted to give you a heads up. 

I tested in our staging environment with a much smaller Metabase instance and it works well and is still running. However, once deployed to our production environment with many more clients, dashboards, queries, as well as large amount of data - after initially working and displaying correctly, Metabase stops populating dashboards with each slide displaying "this is taking longer than usual". If I restart the service it starts working again for a short while, but stops responding soon after. I had to respond quickly and go back to previous version and in the rush did not retain the logs, sorry about that. After rolling back to 0.31.2 and restoring Metabase store from backup the problem no longer manifested.

The problem was encountered company-wide on all workstations.

- Your browser and the version: all versions of Chrome in our environment.
- Your operating system: Ubuntu 16 and up.
- Your databases: PG 10.
- Metabase version: 0.32.1
- Metabase hosting environment: Gentoo running in KVM.
- Metabase internal database: PG 10

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by flamber** [comment]
Hi @vi-vsn Without logs, it's difficult to know what is going on. It would be great if you could try again outside normal working hours, so you have time to check the logs.

**Comment by AndrewBarba** [comment]
We're experiencing similar issues on 0.32.2, will try and get logs but the logs screen in Metabase is pretty un-usable, jumps all of over the place with no way to pause

**Comment by vi-vsn** [comment]
It also writes the logs to file, if that helps.

**Comment by AndrewBarba** [comment]
<img width="2672" alt="Screen Shot 2019-04-04 at 3 01 36 PM" src="https://user-images.githubusercontent.com/1316152/55581488-f1c3fc80-56ea-11e9-940a-85c968993a44.png">

**Comment by AndrewBarba** [comment]
[metabase_logs.zip](https://github.com/metabase/metabase/files/3045085/metabase_logs.zip)

**Comment by AndrewBarba** [comment]
There are around 20 cards on that dashboard, 10 of them completed the others never returned a response. Not sure if it matters but we use Fastly in front of metabase, Fastly never received any content from metabase so it returns a 504 after 60 seconds

**Comment by AndrewBarba** [comment]
Okay so pretty interesting, I tried pointing DNS direct at Elastic Beanstalk instead of through Fastly, working much better. Then just for the heck of it, I tried enabling Cloudflare's proxy feature which pointed at EBS and same issue as before. I think the web server might be returning responses incorrectly. The browser seems to handle it, but Fastly and Cloudflare do not like it.

**Comment by vi-vsn** [comment]
If that’s relevant - I have nginx in front of Metabase.

**Comment by AndrewBarba** [comment]
After disabling Fastly/Cloudflare and Nginx on Elastic Beanstalk it happens a lot less but definitely still an issue. Now maybe 1 or 2 cards will fail instead of 10 or more

**Comment by mallchin** [comment]
+1

**Comment by camsaul** [comment]
These API endpoints are supposed to write a blank character to keep the connection alive every second or so to prevent nginx timeouts and the like. It seems like it's not working correctly however, or not starting to write the keepalive characters right away. I will take a look at this and hopefully have a fix today

**Comment by AndrewBarba** [comment]
@camsaul I think there may be a misunderstanding here. The requests that are timing out out are really normally < 1 sec calls. I don't think this is an issue of writing not writing a keep alive character, if anything it's the opposite where the actual sql query is done and the response is trying to be returned but for some reason the browser thinks the request is still pending.

**Comment by camsaul** [comment]
Thanks for the clarification @AndrewBarba. I'll try to figure out how to repro this and see if I can get a fix out as part of the 0.32.3 release we're planning on pushing today.

**Comment by camsaul** [comment]
Should be fixed in 0.32.3. Will reopen if issue still exists. 

Fixed by #9704

**Comment by pro100filipp** [comment]
Updated to 0.32.3 but it still takes too long for queries to be run. Switched to 0.31.2 and all is OK again.

**Comment by bayerls** [comment]
Hello everyone. 
@AndrewBarba @camsaul  can you confirm that this actually fixed the given problem? I am still seeing the same problematic behaviour with a dockerized Metabase with a nginx proxy (no fastly/cloudflare). 

Maybe same additional information: At the point when the dashboard is empty all database connections from metabase are actually closed.

Can you reopen the ticket, if you consider this still being a metabase issue?

**Comment by AndrewBarba** [comment]
This did not fix the problem. It’s now become a pretty major issue for us, we really need a resolution.

**Comment by mallchin** [comment]
Many questions still fail to load properly for me.  This wasn't an issue until the most recent builds.

**Comment by mazameli** [comment]
@camsaul Reopened this as it seems folks are still experiencing it after upgrading to 0.32.3.

**Comment by camsaul** [comment]
He everyone, I'm working on a fix for this, but still trying to figure out how to repro it. Once I repro it it should be a quick fix and I will hopefully be able to push out a release today.

I could use as much detail as possible about the dashboards where this issue is happening. Most specifically if you guys could tell me:
*  the Number of Cards on the Dashboard where you're seeing this
*  How long the Cards usually took to load on older versions of Metabase (e.g. "2 seconds" or "5 of them took about 3 minutes but the reset took about 2 seconds")
*  How many of them are now loading slowly
*  Whether the ones that load slowly every finish loading, and if so, how long

This will help me figure out a test case for the issue and get a fix out ASAP

**Comment by camsaul** [comment]
Also whether everyone here is using a reverse proxy in front of their Metabase instance such as nginx would be helpful for me as well

**Comment by vi-vsn** [comment]
I am using nginx. 

Many dashboards are large with 20 cards or so, with many cards that take long (30 seconds or more) to generate - I usually set caching to pretty high values, like 60 (as a matter of fact I wish I could have better control over cache retention on a per-dashboard basis as opposed to the current multiplier behavior).

However once the problem appears - even the small dashboards ( and  even standalone questions! ) no longer load, unless the service is restarted. Following the restart - it works for a little bit and then the problem re-occurs.

**Comment by camsaul** [comment]
Ok, thanks @vi-vsn. I've figured out how to repro this. Expect a fix later today

**Comment by camsaul** [comment]
Ok,

So it seems there are a couple of things going on here.

The biggest issue is that `nginix` seems to be waiting for the entire response to complete before forwarding it. Here's the expected behavior, with the keepalive bytes being written once a second (no nginx)

![image](https://user-images.githubusercontent.com/1455846/56064432-da0df900-5d26-11e9-8ec1-0081543fccba.png)

Here's what I'm seeing on an instance running on Elastic Beanstalk (with nginx):

![image](https://user-images.githubusercontent.com/1455846/56064339-a3d07980-5d26-11e9-8e58-9042d25e618a.png)

Which is causing the timeouts.

We have a another problem where cached queries are subjected to asynchronous waiting which is not needed which is why normally fast queries are taking longer and sometimes timing out

**Comment by camsaul** [comment]
One last question 
Is everyone here using caching ?

**Comment by camsaul** [comment]
So I think one issue I'm seeing with my Elastic Beanstalk instance is that `nginx` is buffering responses, and then the ELB we have in front of that is using a 60-second timeout and closing the connection entirely. Turning `proxy_buffering` off in nginx might be the solution for that problem, I'll look at that more in a bit. In the past the connection keepalive functionality was only enabled for ad-hoc queries, so if even if it's not working now behind reverse proxies as expected it isn't the root cause of the problem.

I think making sure cached queries don't get stuck doing async waiting should fix the issues we're seeing here. I will try that fix and report back

**Comment by camsaul** [comment]
Fix is slightly more complicated hoping to wrap it up and push out new build Monday.

**Comment by pro100filipp** [comment]
> One last question
> Is everyone here using caching ?

The problem first occurred with caching disabled. My thoughts were that it's something wrong with my database at first, so I turned caching on then, but figured out that other tools (psql, Redash) executed queries pretty fast.

I also use Metabase (docker version) behind nginx.

**Comment by camsaul** [comment]
Fixed by #9780, #9793, #9806, #9815, #9817

**Comment by camsaul** [comment]
Hi everyone, this is fixed in Metabase 0.32.5, which has just been released. We've actually made a few big improvements to prevent long-running queries from getting canceled when running Metabase behind reverse proxies (specifically nginx + an Elastic Load Balancer or nginx + something else). This has been an issue for a very long time, so Metabase 0.32.5 should be a big improvement over all previous versions.

Please give it a try and let us know how it works for you!

**Comment by tuaris** [comment]
I'm still seeing some issues.  For example, some questions have lost their customization in regards to display and series labels.  This is best explained by a picture:

With 0.32.5

![Question Visualization](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-22T17-47-43.034Z.png)


With 0.31.2

![Question Visualization](http://venus.morante.net/downloads/unibia/screenshots/Firefox_Screenshot_2019-04-22T17-54-00.708Z.png)

**Comment by flamber** [comment]
Hi @tuaris That's a different issue. Maybe #9189 or #9785

**Comment by camsaul** [comment]
@tuaris does that mean you’re not seeing the “dashboards stop populating” issue anymore?

**Comment by tuaris** [comment]
@camsaul I haven't come across the dashboard populating issue in 0.32.5.

**Comment by AndrewBarba** [comment]
@camsaul Looks like 0.32.5 broke the "Download full results" functionality, now when downloading full-results its still capped to 2,000 rows

**Comment by bayerls** [comment]
@camsaul I am still seeing the same problem with dashboards not populating after some hours. How can i help you here by providing more information?

**Comment by camsaul** [comment]
@bayerls do these queries usually take hours to run?

**Comment by bayerls** [comment]
The queries (roughly 20) on the dashboard take at most 30 seconds each. In general, there should be no query that takes longer than 2 minutes. The problem with dashboards not populating starts to appear after 2-4 hours.

**Comment by camsaul** [comment]
To confirm, this happens on 0.32.5 but not on 0.31.x?

**Comment by bayerls** [comment]
Yes, it happens with all versions 0.32.1 to 0.32.5 (probably also 0.32.0 but i skipped that one). With 0.31.x or earlier the problem never occurred.

**Comment by DenisMakagonov** [comment]
it might  be related with connection pool configuration if you have 15 connections in a pull but you have 20 long running questions on your dashboard,  first 15 questions  will use available 15 connections and all the rest will wait in a queue. If you have several users running the same Dashboard... just multiple amount of questions on amount of users ... all your queries  will stuck

**Comment by camsaul** [comment]
@DenisMakagonov that's right. But after those first 15 finish the other ones will start running, unless they were canceled first. 

To keep the connections from being considered timed out we write a byte every second until the query results come back. However, some reverse proxies can buffer our responses, and if you have more than one reverse proxy (for example Elastic Beanstalk with both an Elastic Load Balancer and nginx in front of Metabase) the second reverse proxy might not be getting the bytes and kill the connection because it considers it "timed out"

**Comment by DenisMakagonov** [comment]
ok, thanks sounds reasonable. Is it relevant for any databases available?

**Comment by mallchin** [comment]
Rolled back to 0.31.2; now loading dashboards okay.

**Comment by camsaul** [comment]
Fixed by #9915

**Comment by tuaris** [comment]
Sadly, I'm still seeing random cards fail to load at random moments.

Here's one example:

```
05-10 20:15:51 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class java.sql.SQLNonTransientConnectionException,
 :error "(conn=4) unexpected end of stream, read 0 bytes from 7 (socket was closed by server)",
 :stacktrace
 ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:234)"
  "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
  "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
  "org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)"
  "org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:530)"
  "org.mariadb.jdbc.MariaDbConnection.getTransactionIsolation(MariaDbConnection.java:951)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.getTransactionIsolation(NewProxyConnection.java:277)"
  "clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:790)"
  "clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)"
  "clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)"
  "clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)"
  "clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)"
  "clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)"
  "--> driver.sql_jdbc.execute$do_in_transaction.invokeStatic(execute.clj:243)"
  "driver.sql_jdbc.execute$do_in_transaction.invoke(execute.clj:242)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invokeStatic(execute.clj:260)"
  "driver.sql_jdbc.execute$run_query_without_timezone.invoke(execute.clj:259)"
  "driver.sql_jdbc.execute$execute_query$fn__62556.invoke(execute.clj:289)"
  "driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:219)"
  "driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:213)"
  "driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:286)"
  "driver.sql_jdbc.execute$execute_query.invoke(execute.clj:280)"
  "driver.sql_jdbc$fn__62799.invokeStatic(sql_jdbc.clj:48)"
  "driver.sql_jdbc$fn__62799.invoke(sql_jdbc.clj:47)"
  "query_processor$fn__40378$execute_query__40383$fn__40384.invoke(query_processor.clj:61)"
  "query_processor$fn__40378$execute_query__40383.invoke(query_processor.clj:55)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__34658.invoke(mbql_to_native.clj:36)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__32695.invoke(annotate.clj:368)"
  "query_processor.middleware.annotate$add_column_info$fn__32600.invoke(annotate.clj:303)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__34138.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.limit$limit$fn__34631.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__40243.invoke(results_metadata.clj:86)"
  "query_processor.middleware.format_rows$format_rows$fn__34619.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__31752.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__32146.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__34380.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__37209.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550$fn__33551.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__40268$fn__40269.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
  "query_processor.store$do_with_new_store.invoke(store.clj:31)"
  "query_processor.middleware.store$initialize_store$fn__40268.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__33146.invoke(async.clj:19)"
  "query_processor.middleware.async_wait$runnable$fn__33277.invoke(async_wait.clj:71)"),
 :query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:userland-query? true},
  :native
  {:query
   "SELECT ......."},
  :info
  {:executed-by 1,
   :context :question,
   :card-id 225,
   :dashboard-id nil,
   :query-hash [108, -52, 59, -87, -123, 48, -19, -60, 88, 81, 80, -120, 115, -1, 18, -95, -80, -43, 2, 114, -118, -83, -69, 119, 10, 77, 99, 59, 18, 61, -76, 127]},
  :parameters [],
  :async? true,
  :cache-ttl 1}}
```

**Comment by tuaris** [comment]
Ah, this may be issue #9885 ?

**Comment by camsaul** [comment]
@tuaris it is the same issue as #9885. What version of MySQL are you using?

**Comment by tuaris** [comment]
This looks like the same issue.  I'm using MariaDB 10.2
