### ISSUE TITLE
Metabase only downloading the first 2,000 results after upgrading to 0.32.5

### ISSUE THREAD

**Issue by LukeAbell** [metabase/metabase#9831]
After upgrading to metabase 0.32.5, regardless of the "none" limit set, only 2,000 rows are downloaded for CSV/xlsx exports.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by AndrewBarba** [comment]
@camsaul We're experiencing the same issue

**Comment by jlisyc** [comment]
Related https://github.com/metabase/metabase/issues/9651

**Comment by fmartoche** [comment]
Any update on that ? It's severely impacting our users :(

**Comment by camsaul** [comment]
We should have a fix for this shortly.

**Comment by camsaul** [comment]
Fixed #9872

**Comment by vivekaditya** [comment]
Looks like this issue is not fixed in v0.32.7
Anyone else having the same issue in v0.32.7 ?

**Comment by mrowek** [comment]
In version 0.32.8 issue still appears while metabase is sending .csv file to mail using pulse. While testing the same queries using "Native Query", the downloaded file is  correct

**Comment by flamber** [comment]
@mrowek So you're saying it works like it should, but when using a Pulse, it only returns 2000 rows?
But that's how attachments in Pulse work - it's limited and the little yellow message should say that too:
> We'll show the first 10 columns and 20 rows of this table in your Pulse. If you email this, we'll add a file attachment with all columns and up to 2,000 rows.

**Comment by robertobitbond** [comment]
@camsaul 

We are running  0.32.8, unfortunately this issue is still present and affecting heavily our analytic system. 

We use this API call to extract data from Metabase:
**"https://metabase-bitbond.eu-central-1.elasticbeanstalk.com/api/card/" + query_id + "/query"**

Any suggestion?

**Comment by robertobitbond** [comment]
@camsaul 

We are running 0.32.8, unfortunately this issue is still present and affecting heavily our analytic system.

We use this API call to extract data from Metabase:
**"POST /api/card/" + query_id + "/query"**

Any suggestion?

**Comment by camsaul** [comment]
Hey @robertobitbond, a limit of 2000 rows is done by default when using that endpoint. You can add `/json`, `/csv`, or `/xlsx` to the endpoint if you want to *download* rows without the usual 2000-rows limit. See #4532 for rationale behind why this is the case.

**Comment by camsaul** [comment]
Hey @tlrobinson, what's the reason you made this P1? It sounds like things are working exactly as expected as far as I can tell. Unless I'm misunderstanding something?

**Comment by camsaul** [comment]
Ok, this issue was reopened by mistake. Limiting rows to 2000 is normal behavior for the `POST /api/card/:id/query` endpoint and for Pulses, you can use `POST /api/card/:id/query/:format` (where format is one of `json`, `csv`, or `xlsx` to *download* results if you want more than the usual 2000.

**Comment by robertobitbond** [comment]
> Ok, this issue was reopened by mistake. Limiting rows to 2000 is normal behavior for the `POST /api/card/:id/query` endpoint and for Pulses, you can use `POST /api/card/:id/query/:format` (where format is one of `json`, `csv`, or `xlsx` to _download_ results if you want more than the usual 2000.

@camsaul  thanks for the update.
While running 0.31 we have no need to add :format, instead with 0.32 there is the need to add it to the URL.

**Comment by guyzir** [comment]
**Exports limited to 2000 Rows** 
CSV / XLSX
From Embedded dashboards. 
Postgres database. 
Dockerised version of 0.32.9

Downloading from question (not the dashboard) does not limit export.

**Comment by superainovacoes** [comment]
@camsaul , looks like that option to download without limit isn't working on embed dashboards.
I tried to download a XLS ou CSV with the url ("api/embed/dashboard") and the 2000 limit it is applied!
![image](https://user-images.githubusercontent.com/16561866/62165010-e0cf7480-b2f3-11e9-9d1f-63653c85dd56.png)

**Comment by flamber** [comment]
@superainovacoes Go and follow this issue, which is specific to embedded dashboard - #10399

**Comment by superainovacoes** [comment]
thanks @flamber !!

**Comment by jlisyc** [comment]
Hi all,
related with downloading...

When downloading, I think it make sense to use the name for a field in datamodel 
![image](https://user-images.githubusercontent.com/33416503/62784283-73270380-babe-11e9-8436-0db2db0a9db0.png)
,
instead of the field/column database.

By now if the field in database is k_field_id , it is this one which is going to be in the xls/csv.
But should be interesting for final user to show k_id (in the image example).

Is it possible?

Thanks a lot,

**Comment by flamber** [comment]
@jlisyc That's fixed in the upcoming 0.33. There's an issue for it, #7902
