### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by azeemdin** [metabase/metabase#9929]
I have updated metabase jar from version **v0.30.4** to **v0.32.6**. Everything looks fine except the "Settings" page under Admin area. While accessing "Settings" page "/admin/settings/setup" I am getting following error and page is displayed as blank

`vendor.bundle.js?a1b98b8c6ab664290336:1 Uncaught TypeError: Cannot read property 'version' of undefined
    at Object.newVersionAvailable (app-main.bundle.js?a1b98b8c6ab664290336:5)
    at app-main.bundle.js?a1b98b8c6ab664290336:5
    at vendor.bundle.js?a1b98b8c6ab664290336:1
    at vendor.bundle.js?a1b98b8c6ab664290336:1
    at vendor.bundle.js?a1b98b8c6ab664290336:1
    at vendor.bundle.js?a1b98b8c6ab664290336:1
    at Function.mapToProps (app-main.bundle.js?a1b98b8c6ab664290336:5)
    at i (vendor.bundle.js?a1b98b8c6ab664290336:1)
    at Function.i.mapToProps (vendor.bundle.js?a1b98b8c6ab664290336:1)
    at i (vendor.bundle.js?a1b98b8c6ab664290336:1)`

I am running metabase with jar file using following command

`java -jar -Xmx2048m metabase.jar`

**Comment by vimagick** [comment]
The same problem occured to me (v0.32.5 -> v0.32.6).

**Comment by camsaul** [comment]
@tlrobinson do you have any idea about this?

**Comment by zolee** [comment]
Same issue here. I have downgraded to version 0.32.5 that seems to fix this problem.

**Comment by camsaul** [comment]
Fixed by #9933

**Comment by vimagick** [comment]
I still cannot open several settings after upgraded to 0.32.7

- /admin/settings/general
- /admin/settings/updates
- /admin/settings/maps
- ...

**Comment by zolee** [comment]
> I still cannot open several settings after upgraded to 0.32.7
> 
> * /admin/settings/general
> * /admin/settings/updates
> * /admin/settings/maps
> * ...

Quite the same for me. :( I have upgraded from `0.32.5` to `0.32.7` and **Updates** page still broken for me. If I click on the **Updates** menu item I can see the following error printout in the Chrome dev tools console:

```
app-main.bundle.js?a36a3806cede064f5de3:5 Uncaught TypeError: Cannot read property 'version' of undefined
    at t.value (app-main.bundle.js?a36a3806cede064f5de3:5)
    at t.value (app-main.bundle.js?a36a3806cede064f5de3:5)
    at u._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?a36a3806cede064f5de3:1)
    at u._renderValidatedComponent (vendor.bundle.js?a36a3806cede064f5de3:1)
    at u.performInitialMount (vendor.bundle.js?a36a3806cede064f5de3:1)
    at u.mountComponent (vendor.bundle.js?a36a3806cede064f5de3:1)
    at Object.mountComponent (vendor.bundle.js?a36a3806cede064f5de3:1)
    at Object.updateChildren (vendor.bundle.js?a36a3806cede064f5de3:1)
    at J._reconcilerUpdateChildren (vendor.bundle.js?a36a3806cede064f5de3:1)
    at J._updateChildren (vendor.bundle.js?a36a3806cede064f5de3:1)

```
Seem that all menu items work until you click on the **Updates** menu item. After clicking on the broken **Updates** menu non of the setting page will load until you refresh the page.

So a temporary workaround for using the settings is not to click on the **Updates** menu item.

**Comment by camsaul** [comment]
It sounds like the Updates page needs the same fix as #9933. Are we checking version info twice? @tlrobinson

**Comment by azeemdin** [comment]
version 0.32.7 fixes the issue for me. Thanks

**Comment by camsaul** [comment]
@tlrobinson I figured out the cause of this issue. We *are* checking the version info twice. Fixed in #9959
